msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: POEditor.com\n"
"Project-Id-Version: friendly-traceback\n"
"Language: ta\n"

#: __init__.py:191 __main__.py:169
msgid "The file {filename} does not exist."
msgstr "கோப்பு {filename} வட்டில் இல்லை."

#: base_formatters.py:148 base_formatters.py:154
msgid "I have no suggestion to offer."
msgstr "நான் வழங்க எந்த பரிந்துரையும் இல்லை."

#: base_formatters.py:152
msgid "I have no suggestion to offer; try `why()`."
msgstr "நான் வழங்க எந்த ஆலோசனையும் இல்லை; `why()` முயற்சிக்கவும்."

#: config.py:77
msgid "Are you using a regular Python console instead of a Friendly console?\n"
"If so, to continue, try: `start_console(local_vars=locals())`.\n"
"You will need to import `start_console` if you have not already done so.\n"
""
msgstr "நீங்கள் நட்பு பணியகத்துக்குப் பதிலாக வழக்கமான பைதான் பணியகத்தைப் பயன்படுத்துகிறீர்களா?\n"
"அப்படியானால், தொடர, முயற்சிக்கவும்: `start_console(local_vars=locals())`.\n"
"நீங்கள் ஏற்கனவே அவ்வாறு செய்யவில்லை என்றால், `start_console` ஐ இறக்குமதி செய்ய வேண்டும்.\n"
""

#: config.py:106 config.py:215 console_helpers.py:29
msgid "Nothing to show: no exception recorded."
msgstr "காட்ட எதுவும் இல்லை: விதிவிலக்கு பதிவு செய்யப்படவில்லை."

#: config.py:359
msgid "An exception occurred before friendly-traceback was imported.\n"
"Some information is available."
msgstr "friendly-traceback இறக்குமதி செய்யப்படுவதற்கு முன்பு ஒரு விதிவிலக்கு ஏற்பட்டது.\n"
"சில தகவல்கள் கிடைக்கின்றன."

#: console_helpers.py:39
msgid "Nothing to go back to: no exception recorded."
msgstr "திரும்பிச் செல்வதற்கு எதுவும் இல்லை: விதிவிலக்கு பதிவு செய்யப்படவில்லை."

#: console_helpers.py:121 console_helpers.py:125
msgid "{exception} is not an exception."
msgstr "{exception} என்பது விதிவிலக்கல்ல."

#: console_helpers.py:207
msgid "Invalid argument for `www()`.\n"
"Valid arguments include `None` or one of `{sites}`.\n"
""
msgstr "`www()` க்கான தவறான மதிப்புரு.\n"
"செல்லுபடியாகும் வாதங்களில் `None` அல்லது `{sites}`இல் ஒன்று அடங்கும்.\n"
""

#: console_helpers.py:231
msgid "The default web browser cannot be used for searching."
msgstr "தேடலுக்கு இயல்புநிலை இணைய உலாவியைப் பயன்படுத்த முடியாது."

#: console_helpers.py:421
msgid "The following methods of the Friendly object should also be available as functions."
msgstr "நட்பு பொருளின் பின்வரும் முறைகள் செயல்பாடுகளாகவும் இருக்க வேண்டும்."

#: core.py:440
msgid "More lines not shown."
msgstr "மேலும் வரிகள் காட்டப்படவில்லை."

#: core.py:441 core.py:482
msgid "Python exception:"
msgstr "பைதான் விதிவிலக்கு:"

#: core.py:498
msgid "Warning: improperly formed exception.\n"
"I suspect that a custom exception has been raised\n"
"with a non-string value used as a message.\n"
"This can occur if a `__repr__` or a `__str__` method\n"
"raises an exception or does not return a string.\n"
""
msgstr "முன்னறிவிப்பு: முறையற்ற விதிவிலக்கு.\n"
"ஒரு சரம் அல்லாத மதிப்பை செய்தியாகப் பயன்படுத்தி ஒரு \n"
"தனிப்பயன் விதிவிலக்கு எழுப்பப்பட்டதாக நான் சந்தேகிக்கிறேன்.\n"
"`__repr__` அல்லது `__str__` முறை விதிவிலக்கை எழுப்பினால் \n"
"அல்லது சரத்தை வழங்கவில்லை என்றால் இது நிகழலாம்.\n"
""

#: core.py:551
msgid "The encoding of the file was not valid.\n"
""
msgstr "கோப்பின் குறியாக்கம் தவறானது.\n"
""

#: core.py:627
msgid "{filename} is not a regular Python file whose contents can be analyzed.\n"
""
msgstr "{filename} என்பது வழக்கமான பைதான் கோப்பு அல்ல, அதன் உள்ளடக்கங்களை பகுப்பாய்வு செய்யலாம்.\n"
""

#: core.py:632
msgid "Exception raised on line {linenumber} of code block {filename}.\n"
""
msgstr "குறியீட்டுப் பகுதி {filename} இன் {linenumber} வரியில் விதிவிலக்கு எழுப்பப்பட்டது.\n"
""

#: core.py:636
msgid "Exception raised on line {linenumber} of file {filename}.\n"
""
msgstr "{filename} கோப்பின் {linenumber} ஆம் வரியில் விதிவிலக்கு எழுப்பப்பட்டது.\n"
""

#: core.py:665
msgid "Execution stopped on line {linenumber} of code block {filename}.\n"
""
msgstr "குறியீட்டுப் பகுதி {filename} இன் {linenumber} ஆம் வரியில் செயல்படுத்தல் நிறுத்தப்பட்டது.\n"
""

#: core.py:669
msgid "Execution stopped on line {linenumber} of file {filename}.\n"
""
msgstr "{filename} கோப்பின் {linenumber} ஆம் வரியில் செயல்படுத்தல் நிறுத்தப்பட்டது.\n"
""

#: core.py:700
msgid "Python could not understand the code in the code block {filename}\n"
""
msgstr "{filename} குறியீட்டுப் பகுதியில் உள்ள குறியீட்டை பைத்தானால் புரிந்து கொள்ள முடியவில்லை\n"
""

#: core.py:704
msgid "Python could not understand the code in the file\n"
"'{filename}'\n"
""
msgstr "'{filename}' \n"
"கோப்பில் உள்ள குறியீட்டைப் பைத்தானால் புரிந்து கொள்ள முடியவில்லை\n"
""

#: core.py:709
msgid "at the location indicated by ^.\n"
""
msgstr "^ ஆல் சுட்டிக்காட்டப்பட்ட இடத்தில்.\n"
""

#: core.py:941
msgid "Unfortunately, no additional information is available:\n"
"the content of file '<stdin>' is not accessible.\n"
""
msgstr "எதிர்பாராதவிதமாக, கூடுதல் தகவல்கள் எதுவும் கிடைக்கவில்லை:\n"
"'<stdin>' ​​கோப்பின் உள்ளடக்கத்தை அணுக முடியாது.\n"
""

#: frame_info.py:31
msgid "Problem: source of `{filename}` is not available\n"
""
msgstr "சிக்கல்: `{filename}` இன் ஆதாரம் கிடைக்கவில்லை\n"
""

#: ft_console.py:29
msgid "Type 'Friendly' for help on special functions/methods."
msgstr "சிறப்பு செயல்பாடுகள்/முறைகள் பற்றிய உதவிக்கு 'Friendly' என தட்டச்சு செய்யவும்."

#: ft_gettext.py:82
msgid "Please report this example to\n"
"https://github.com/friendly-traceback/friendly-traceback/issues/new\n"
"If you are using a REPL, use `www('bug')` to do so.\n"
"\n"
""
msgstr "தயவுசெய்து இந்த உதாரணத்தைப் புகாரளிக்கவும்\n"
"https://github.com/friendly-traceback/friendly-traceback/issues/new\n"
"நீங்கள் REPL ஐப் பயன்படுத்தினால், அவ்வாறு செய்ய `www('bug')` ஐப் பயன்படுத்தவும்.\n"
"\n"
""

#: ft_gettext.py:90
msgid "Friendly-traceback does not know the cause of this error.\n"
""
msgstr "நட்பு-மீண்டும்கண்டுபிடிக்க Friendly-tracebackக்கு இந்த பிழைக்கான காரணம் தெரியவில்லை.\n"
""

#: ft_gettext.py:96
msgid "No information is known about this exception.\n"
""
msgstr "இந்த விதிவிலக்கு பற்றி எந்த தகவலும் தெரியவில்லை.\n"
""

#: ft_gettext.py:98
msgid "If you are using the Friendly console, use `www()` to\n"
"do an Internet search for this particular case.\n"
""
msgstr "நீங்கள் நட்பு பணியகத்தை பயன்படுத்துகிறீர்கள் என்றால், அதற்கு `www()` ஐப் \n"
"பயன்படுத்தி இந்த குறிப்பிட்ட வழக்கை இணையத்தில் தேடுங்கள்.\n"
""

#: ft_gettext.py:107
msgid "Internal error for Friendly.\n"
""
msgstr "நட்புக்கு உள் பிழை.\n"
""

#: functions_help.py:10
msgid "Removes the last recorded traceback item."
msgstr "கடைசியாகப் பதிவுசெய்யப்பட்ட மீண்டும்கண்டுபிடிக்கும் உருப்படியை நீக்குகிறது."

#: functions_help.py:11
msgid "Shows all the information about the last traceback."
msgstr "கடைசி மீண்டும்கண்டுபிடிப்பு பற்றிய அனைத்து தகவல்களையும் காட்டுகிறது."

#: functions_help.py:12
msgid "Shows a list of recorded traceback messages."
msgstr "பதிவுசெய்யப்பட்ட மீண்டும்கண்டுபிடிக்கும் செய்திகளின் பட்டியலைக் காட்டுகிறது."

#: functions_help.py:13
msgid "Sets the language to be used."
msgstr "பயன்படுத்த வேண்டிய மொழியை அமைக்கிறது."

#: functions_help.py:14
msgid "Shows the paths corresponding to synonyms used."
msgstr "பயன்படுத்தப்படும் ஒத்த சொற்களுடன் தொடர்புடைய பாதைகளைக் காட்டுகிறது."

#: functions_help.py:17
msgid "Shows where an exception was raised."
msgstr "விதிவிலக்கு எங்கு எழுப்பப்பட்டது என்பதைக் காட்டுகிறது."

#: functions_help.py:18
msgid "Shows the likely cause of the exception."
msgstr "விதிவிலக்கான சாத்தியமான காரணத்தைக் காட்டுகிறது."

#: functions_help.py:19
msgid "Opens a web browser at a useful location."
msgstr "பயனுள்ள இடத்தில் இணைய உலாவியைத் திறக்கும்."

#: functions_help.py:20
msgid "Suggestion sometimes added to a friendly traceback."
msgstr "பரிந்துரை சில சமயங்களில் நட்பு மீண்டும்கண்டுபிடிப்பில் சேர்க்கப்படும்."

#: functions_help.py:21
msgid "Shows a normal Python traceback."
msgstr "சாதாரண பைதான் மீண்டும்கண்டுபிடிப்பைக் காட்டுகிறது."

#: functions_help.py:22
msgid "Shows a simplified Python traceback."
msgstr "எளிமைப்படுத்தப்பட்ட பைதான் மீண்டும்கண்டுபிடிப்பை காட்டுகிறது."

#: functions_help.py:23
msgid "Returns the current value used for items to include by default."
msgstr "இயல்புநிலையில் சேர்க்கப்படும் உருப்படிகளுக்குப் பயன்படுத்தப்படும் தற்போதைய மதிப்பை வழங்கும்."

#: functions_help.py:26
msgid "Sets the items to show by default when an exception is raised."
msgstr "விதிவிலக்கு எழுப்பப்படும்போது, ​​இயல்புநிலையாகக் காண்பிக்க உருப்படிகளை அமைக்கிறது."

#: functions_help.py:29
msgid "Returns the language currently used."
msgstr "தற்போது பயன்படுத்தப்படும் மொழியை வழங்குகிறது."

#: functions_help.py:30
msgid "Sets the formatter to use for display."
msgstr "காட்சிக்கு பயன்படுத்த வடிவமைப்பை அமைக்கிறது."

#: info_generic.py:39
msgid "An exception of type `{name}` is a subclass of `{parent}`.\n"
""
msgstr "`{name}` வகை விதிவிலக்கு என்பது `{parent}` இன் துணைப்பிரிவாகும்.\n"
""

#: info_generic.py:64
msgid "`ArithmeticError` is the base class for those built-in exceptions\n"
"that are raised for various arithmetic errors.\n"
"It is unusual that you are seeing this exception;\n"
"normally, a more specific exception should have been raised.\n"
""
msgstr "எண்கணிதப்பிழை `ArithmeticError` என்பது உள்ளமைக்கப்பட்ட விதிவிலக்குகளுக்கான அடிப்படை வகுப்பாகும்\n"
"பல்வேறு எண்கணிதப் பிழைகளுக்காக எழுப்பப்பட்டவை.\n"
"இந்த விதிவிலக்கை நீங்கள் பார்ப்பது அசாதாரணமானது;\n"
"பொதுவாக, ஒரு குறிப்பிட்ட விதிவிலக்கு எழுப்பப்பட்டிருக்க வேண்டும்.\n"
""

#: info_generic.py:74
msgid "In Python, the keyword `assert` is used in statements of the form\n"
"`assert condition`, to confirm that `condition` is not `False`,\n"
"nor equivalent to `False` such as an empty list, etc.\n"
"\n"
"If `condition` is `False` or equivalent, an `AssertionError` is raised.\n"
""
msgstr "பைத்தானில், நிபந்தனை `condition` என்பது தவறு `False` அல்ல, \n"
"அல்லது வெற்றுப் பட்டியல் போன்ற தவறு `False` என்பதற்குச் சமமானதாக இல்லை என்பதை உறுதிப்படுத்த, உறுதிப்படுத்துதல் `assert` என்ற முக்கிய சொல் \n"
"உறுதிப்படுத்தல் நிபந்தனை `assert condition` படிவத்தின் அறிக்கைகளில் பயன்படுத்தப்படுகிறது.\n"
"\n"
"நிபந்தனை `condition` என்பது தவறு `False` அல்லது அதற்கு சமமானதாக இருந்தால், உறுதிப்படுத்தல்பிழை `AssertionError` எழுப்பப்படும்.\n"
""

#: info_generic.py:84
msgid "An `AttributeError` occurs when the code contains something like\n"
"    `object.x`\n"
"and `x` is not a method or attribute (variable) belonging to `object`.\n"
""
msgstr "பின்வரும் குறியீடு போல ஏதாவது இருந்தால் பண்புப்பிழை `AttributeError` ஏற்படுகிறது\n"
"    `object.x`\n"
"மேலும் `x` என்பது `object`க்கு சொந்தமான ஒரு முறை அல்லது பண்புக்கூறு (மாறி) அல்ல.\n"
""

#: info_generic.py:93
msgid "An `EOFError` is raised when the `input()` function hits\n"
"an end-of-file condition (EOF) without reading any data.\n"
""
msgstr "`input()` செயல்பாடு  எந்த தரவையும் படிக்காமல் ஒரு இறுதி கோப்பு நிலை (EOF) \n"
"படிக்கும்போது  இறுதிகோப்புநிலைபிழை `EOFError` எழுப்பப்படுகிறது.\n"
""

#: info_generic.py:101
msgid "A `FileNotFoundError` exception indicates that you\n"
"are trying to open a file that cannot be found by Python.\n"
"This could be because you misspelled the name of the file.\n"
""
msgstr "கோப்புகிடைக்கவில்லைபிழை `FileNotFoundError` விதிவிலக்கு நீங்கள் பைத்தானால் கண்டுபிடிக்க முடியாத \n"
"கோப்பைத் திறக்க முயற்சி செய்கிறார்கள் என்பதைக் குறிக்கிறது.\n"
"நீங்கள் கோப்பின் பெயரை தவறாக எழுதியதால்  இது நிகழலாம்.\n"
""

#: info_generic.py:110
msgid "An `ImportError` exception indicates that a certain object could not\n"
"be imported from a module or package. Most often, this is\n"
"because the name of the object is not spelled correctly.\n"
""
msgstr "ஒரு குறிப்பிட்ட பொருளை ஒரு தொகுதி அல்லது தொகுப்பிலிருந்து \n"
"இறக்குமதி செய்ய முடியாது என்பதை இறக்குமதிப்பிழை `ImportError` விதிவிலக்கு குறிக்கிறது. \n"
"பெரும்பாலும், பொருளின் பெயர் சரியாக எழுதப்படாததே இதற்குக் காரணம்.\n"
""

#: info_generic.py:119
msgid "An `IndentationError` occurs when a given line of code is\n"
"not indented (aligned vertically with other lines) as expected.\n"
""
msgstr "கொடுக்கப்பட்ட குறியீட்டு வரி எதிர்பார்த்தபடி உள்தள்ளப்படாமல் \n"
"(பிற வரிகளுடன் செங்குத்தாக சீரமைக்கப்பட்டது) இருக்கும்பொழுது உள்தள்ளல்பிழை `IndentationError`  ஏற்படுகிறது.\n"
""

#: info_generic.py:127
msgid "An `IndexError` occurs when you try to get an item from a list,\n"
"a tuple, or a similar object (sequence), and use an index which\n"
"does not exist; typically, this happens because the index you give\n"
"is greater than the length of the sequence.\n"
""
msgstr "பட்டியல், மடங்கு அல்லது ஒத்த பொருளிலிருந்து (வரிசை) ஒரு பொருளைப் பெற முயலும்போது, \n"
"இல்லாத குறியீட்டைப் பயன்படுத்தும்போது குறியீட்டுபிழை `IndexError` ஏற்படுகிறது; \n"
"பொதுவாக, நீங்கள் கொடுக்கும் குறியீட்டு\n"
"வரிசையின் நீளத்தை விட அதிகமாக இருப்பதால் இது நிகழ்கிறது.\n"
""

#: info_generic.py:137
msgid "A `KeyError` is raised when a value is not found as a\n"
"key in a Python dict or in a similar object.\n"
""
msgstr "பைதான் அகராதியிலோ அல்லது அதைப் போன்ற பொருளிலோ ஒரு மதிப்பு\n"
"திறவுகோலாக காணப்படும்போது திறவுகோல்பிழை `KeyError` எழுப்பப்படுகிறது.\n"
""

#: info_generic.py:145
msgid "`LookupError` is the base class for the exceptions that are raised\n"
"when a key or index used on a mapping or sequence is invalid.\n"
"It can also be raised directly by codecs.lookup().\n"
""
msgstr "தேடல்பிழை `LookupError` என்பது அட்டவணை அல்லது வரிசைமுறையில் பயன்படுத்தப்படும் திறவுகோல் அல்லது குறியீட்டு தவறானதாக இருக்கும் போது\n"
"எழுப்பப்படும் விதிவிலக்குகளுக்கான அடிப்படை வகுப்பாகும்.\n"
"இது codecs.lookup() மூலமாகவும் நேரடியாக எழுப்பப்படலாம்.\n"
""

#: info_generic.py:154
msgid "Like the name indicates, a `MemoryError` occurs when Python\n"
"runs out of memory. This can happen if you create an object\n"
"that is too big, like a list with too many items.\n"
""
msgstr "பெயர் குறிப்பிடுவது போல, பைதான் நினைவகம் தீர்ந்துவிட்டால் நினைவகபிழை `MemoryError` ஏற்படுகிறது.\n"
"பல உருப்படிகளைக் கொண்ட பட்டியல் போன்ற மிகப் பெரிய பொருளை நீங்கள்\n"
"உருவாக்கினால் இது நிகழலாம்.\n"
""

#: info_generic.py:163
msgid "A `ModuleNotFoundError` exception indicates that you\n"
"are trying to import a module that cannot be found by Python.\n"
"This could be because you misspelled the name of the module\n"
"or because it is not installed on your computer.\n"
""
msgstr "ஒரு தொகுதிகண்டறியப்படவில்லைபிழை `ModuleNotFoundError` விதிவிலக்கு,\n"
"பைத்தானால் கண்டுபிடிக்க முடியாத ஒரு தொகுதியை நீங்கள் இறக்குமதி செய்ய முயற்சிக்கிறீர்கள் என்பதைக் குறிக்கிறது.\n"
"நீங்கள் தொகுதியின் பெயரை தவறாக எழுதியதாலோ அல்லது உங்கள் கணினியில்\n"
"நிறுவப்படாததாலோ இது நிகழலாம்.\n"
""

#: info_generic.py:173
msgid "A `NameError` exception indicates that a variable or\n"
"function name is not known to Python.\n"
"Most often, this is because there is a spelling mistake.\n"
"However, sometimes it is because the name is used\n"
"before being defined or given a value.\n"
""
msgstr "ஒரு பெயர்ப்பிழை `NameError` விதிவிலக்கு என்பது ஒரு மாறி அல்லது \n"
"செயல்பாட்டுப் பெயர் பைத்தானுக்குத் தெரியாது என்பதைக் குறிக்கிறது.\n"
"பெரும்பாலும், எழுத்துப் பிழை இருப்பதே இதற்குக் காரணம்.\n"
"இருப்பினும், சில நேரங்களில் பெயர் வரையறுக்கப்படுவதற்கு முன்பு அல்லது\n"
"மதிப்பைக் கொடுப்பதற்கு முன்பு பயன்படுத்தப்படுவதால் வருகிறது.\n"
""

#: info_generic.py:184
msgid "An `OSError` exception is usually raised by the Operating System\n"
"to indicate that an operation is not allowed or that\n"
"a resource is not available.\n"
""
msgstr "ஒரு முறைமைபிழை `OSError` விதிவிலக்கு பொதுவாக ஒரு செயல்பாடு \n"
"அனுமதிக்கப்படவில்லை அல்லது ஆதாரம் இல்லை என்பதைக் குறிக்க இயக்க \n"
"முறைமையால் எழுப்பப்படுகிறது.\n"
""

#: info_generic.py:193
msgid "An `OverflowError` is raised when the result of an arithmetic operation\n"
"is too large to be handled by the computer's processor.\n"
""
msgstr "ஒரு எண்கணிதச் செயல்பாட்டின் விளைவு கணினியின் செயலியால் கையாள \n"
"முடியாத அளவுக்குப் பெரிதாக இருக்கும்போது வழிதல்பிழை `OverflowError` எழுப்பப்படுகிறது.\n"
""

#: info_generic.py:201
msgid "A `RecursionError` is raised when a function calls itself,\n"
"directly or indirectly, too many times.\n"
"It almost always indicates that you made an error in your code\n"
"and that your program would never stop.\n"
""
msgstr "ஒரு செயல்பாடு நேரடியாகவோ அல்லது மறைமுகமாகவோ பல முறை தன்னை\n"
"அழைக்கும் போது மறுநிகழ்வுபிழை `RecursionError` எழுப்பப்படுகிறது.\n"
"உங்கள் குறியீட்டில் நீங்கள் பிழை செய்துள்ளீர்கள் என்பதையும் உங்கள் நிரல்\n"
"ஒருபோதும் நிறுத்தப்படாது என்பதையும் இது எப்போதும் குறிக்கிறது.\n"
""

#: info_generic.py:219
msgid "`StopIteration` is raised to indicate that an iterator has no more\n"
"item to provide when its `__next__` method is called by\n"
"the `next()` builtin function.\n"
""
msgstr "`__next__` முறையானது `next()` உள்ளமைக்கப்பட்ட செயல்பாட்டின் மூலம்\n"
"அழைக்கப்படும் போது, மறு செய்கைக்கு வழங்க வேண்டிய உருப்படி எதுவும்\n"
"இல்லை என்பதைக் குறிக்க மறுசெய்கையைநிறுத்து `StopIteration` உயர்த்தப்பட்டது.\n"
""

#: info_generic.py:228
msgid "A `SyntaxError` occurs when Python cannot understand your code.\n"
""
msgstr "பைத்தானால் உங்கள் குறியீட்டைப் புரிந்து கொள்ள முடியாதபோது தொடரியல்பிழை `SyntaxError` ஏற்படுகிறது.\n"
""

#: info_generic.py:233
msgid "A `TabError` indicates that you have used both spaces\n"
"and tab characters to indent your code.\n"
"This is not allowed in Python.\n"
"Indenting your code means to have block of codes aligned vertically\n"
"by inserting either spaces or tab characters at the beginning of lines.\n"
"Python's recommendation is to always use spaces to indent your code.\n"
""
msgstr "ஒரு தாவல்பிழை `TabError` என்பது உங்கள் குறியீட்டை உள்தள்ளுவதற்கு இடைவெளிகள் மற்றும் தாவல் எழுத்துகள் இரண்டையும்\n"
"பயன்படுத்தியுள்ளீர்கள் என்பதைக் குறிக்கிறது.\n"
"பைத்தானில் இதற்கு அனுமதி இல்லை.\n"
"உங்கள் குறியீட்டை உள்தள்ளுவது என்பது வரிகளின் தொடக்கத்தில்\n"
"இடைவெளிகள் அல்லது தாவல் எழுத்துக்களைச் செருகுவதன் மூலம் செங்குத்தாக சீரமைக்கப்பட்ட குறியீடுகளின் தொகுதியைக் கொண்டிருப்பதாகும்.\n"
"உங்கள் குறியீட்டை உள்தள்ள எப்போதும் இடைவெளிகளைப் பயன்படுத்த வேண்டும் என்பதே பைத்தானின் பரிந்துரை.\n"
""

#: info_generic.py:245
msgid "A `TypeError` is usually caused by trying\n"
"to combine two incompatible types of objects,\n"
"by calling a function with the wrong type of object,\n"
"or by trying to do an operation not allowed on a given type of object.\n"
""
msgstr "ஒரு வகைப்பிழை `TypeError` என்பது பொதுவாக பொருந்தாத இரண்டு\n"
"வகையான பொருள்களை இணைக்க முயற்சிப்பதாலோ, ஒரு செயல்பாட்டை\n"
"தவறான வகைப் பொருளுடன் அழைப்பதாலோ அல்லது கொடுக்கப்பட்ட\n"
"வகைப் பொருளில் அனுமதிக்கப்படாத செயலைச் செய்ய முயற்சிப்பதாலோ ஏற்படுகிறது.\n"
""

#: info_generic.py:255
msgid "A `ValueError` indicates that a function or an operation\n"
"received an argument of the right type, but an inappropriate value.\n"
""
msgstr "ஒரு மதிப்புப்பிழை `ValueError` என்பது ஒரு செயல்பாடு அல்லது செயல்பாடு\n"
"சரியான வகையின் வாதத்தைப் பெற்றது, ஆனால் ஒரு பொருத்தமற்ற மதிப்பைக் குறிக்கிறது.\n"
""

#: info_generic.py:263
msgid "In Python, variables that are used inside a function are known as \n"
"local variables. Before they are used, they must be assigned a value.\n"
"A variable that is used before it is assigned a value is assumed to\n"
"be defined outside that function; it is known as a `global`\n"
"(or sometimes `nonlocal`) variable. You cannot assign a value to such\n"
"a global variable inside a function without first indicating to\n"
"Python that this is a global variable, otherwise you will see\n"
"an `UnboundLocalError`.\n"
""
msgstr "பைத்தானில், ஒரு செயல்பாட்டிற்குள் பயன்படுத்தப்படும் மாறிகள் உள்ளூர் மாறிகள் எனப்படும்.\n"
"அவற்றைப் பயன்படுத்துவதற்கு முன், அவற்றிற்கு ஒரு மதிப்பு ஒதுக்கப்பட வேண்டும்.\n"
"ஒரு மதிப்பு ஒதுக்கப்படுவதற்கு முன் பயன்படுத்தப்படும் ஒரு மாறி கருதப்படுகிறது\n"
"அந்த செயல்பாட்டிற்கு வெளியே வரையறுக்கப்பட வேண்டும்;\n"
"இது ஒரு உலகளாவிய `global` (அல்லது சில நேரங்களில் உள்ளூர்அல்லாத `nonlocal`) மாறி என அறியப்படுகிறது.\n"
"இது ஒரு உலகளாவிய மாறி என்பதை பைத்தானுக்கு முதலில் குறிப்பிடாமல் ஒரு செயல்பாட்டிற்குள் அத்தகைய உலகளாவிய மாறிக்கு நீங்கள் மதிப்பை ஒதுக்க முடியாது, \n"
"இல்லையெனில் நீங்கள் பார்ப்பீர்கள்\n"
"ஒரு வரம்பற்றஉள்ளூர்பிழை `UnboundLocalError`.\n"
""

#: info_generic.py:277
msgid "No information is available about this warning.\n"
""
msgstr "இந்த முன்னறிவிப்பு குறித்து எந்த தகவலும் இல்லை.\n"
""

#: info_generic.py:282
msgid "A `ZeroDivisionError` occurs when you are attempting to divide a value\n"
"by zero either directly or by using some other mathematical operation.\n"
""
msgstr "ஒரு மதிப்பை சுழியத்தால் நேரடியாகவோ அல்லது வேறு சில கணிதச் \n"
"செயல்பாட்டைப் பயன்படுத்தியோ வகுக்க முயற்சிக்கும்போது சுழியவகுத்தல்பிழை `ZeroDivisionError` ஏற்படுகிறது.\n"
""

#: info_variables.py:32
msgid "a complex number"
msgstr "ஒரு சிக்கலான எண்"

#: info_variables.py:33
msgid "a dictionary (`dict`)"
msgstr "ஒரு அகராதி (`dict`)"

#: info_variables.py:34
msgid "a number (`float`)"
msgstr "ஒரு மிதவைப்புள்ளிஎண் (`float`)"

#: info_variables.py:35
msgid "a `frozenset`"
msgstr "ஒரு `உறைந்ததொகுப்பு`"

#: info_variables.py:36
msgid "an integer (`int`)"
msgstr "ஒரு முழுஎண் (`int`)"

#: info_variables.py:37
msgid "a `list`"
msgstr "ஒரு `பட்டியல்`"

#: info_variables.py:38
msgid "a variable equal to `None` (`NoneType`)"
msgstr "இல்லை`None` (`NoneType`) க்கு சமமான மாறி"

#: info_variables.py:39
msgid "a `set`"
msgstr "ஒரு `தொகுப்பு`"

#: info_variables.py:40 info_variables.py:41
msgid "a string (`str`)"
msgstr "ஒரு சரம் (`str`)"

#: info_variables.py:42
msgid "a `tuple`"
msgstr "ஒரு `மடங்கு`"

#: info_variables.py:446
msgid "A type hint found for `{name}` in the {scope} scope.\n"
"Perhaps you had used a colon instead of an equal sign and wrote\n"
"\n"
"    {name} : {hint}\n"
"\n"
"instead of\n"
"\n"
"    {name} = {hint}\n"
""
msgstr "{scope} வாய்ப்பில் `{name}` க்கான வகை குறிப்பு உள்ளது.\n"
"ஒருவேளை நீங்கள் சமமான அடையாளத்திற்குப் பதிலாக முக்காற்புள்ளிப் பயன்படுத்தி எழுதியிருக்கலாம்\n"
"\n"
"     {name} : {hint}\n"
"\n"
"அதற்கு பதிலாக\n"
"\n"
"     {name} = {hint}\n"
""

#: path_info.py:208
msgid "The default directory is {dirname}."
msgstr "இயல்பு கோப்பகம் {dirname}."

#: runtime_errors\attribute_error.py:32 runtime_errors\attribute_error.py:80
#: runtime_errors\attribute_error.py:118
msgid "Did you give your program the same name as a Python module?\n"
""
msgstr "உங்கள் நிரலுக்கு பைதான் தொகுதிக்கு அதே பெயரைக் கொடுத்தீர்களா?\n"
""

#: runtime_errors\attribute_error.py:33 runtime_errors\attribute_error.py:81
msgid "I suspect that you used the name `{module}.py` for your program\n"
"and that you also wanted to import a module with the same name\n"
"from Python's standard library.\n"
"If so, you should use a different name for your program.\n"
""
msgstr "உங்கள் நிரலுக்கு `{module}.py` என்ற பெயரைப் பயன்படுத்தியுள்ளீர்கள் என்றும்,\n"
"அதே பெயரில் பைத்தானின் நிலையான நூலகத்திலிருந்து ஒரு தொகுதியை\n"
"இறக்குமதி செய்ய விரும்புவதாகவும் சந்தேகிக்கிறேன்.\n"
"அப்படியானால், உங்கள் நிரலுக்கு வேறு பெயரைப் பயன்படுத்த வேண்டும்.\n"
""

#: runtime_errors\attribute_error.py:42 runtime_errors\import_error.py:75
msgid "You have a circular import.\n"
""
msgstr "உங்களிடம் ஒரு வட்ட இறக்குமதி உள்ளது.\n"
""

#: runtime_errors\attribute_error.py:46 runtime_errors\attribute_error.py:89
msgid "You likely have a circular import.\n"
""
msgstr "உங்களிடம் வட்ட இறக்குமதி இருக்கலாம்.\n"
""

#: runtime_errors\attribute_error.py:47
msgid "Python indicated that the module `{module}` was not fully imported.\n"
""
msgstr "`{module}` தொகுதி முழுமையாக இறக்குமதி செய்யப்படவில்லை என்று பைதான் சுட்டிக்காட்டியது.\n"
""

#: runtime_errors\attribute_error.py:48 runtime_errors\attribute_error.py:90
msgid "This can occur if, during the execution of the code in module `{module}`\n"
"an attempt is made to import the same module again.\n"
""
msgstr "தொகுதி `{module}` இல் குறியீட்டை செயல்படுத்தும் போது, \n"
"அதே தொகுதியை மீண்டும் இறக்குமதி செய்ய முயற்சித்தால் இது நிகழலாம்.\n"
""

#: runtime_errors\attribute_error.py:73
msgid "This should not happen:\n"
"Python tells us that module `{module}` does not have an attribute named `{attribute}`.\n"
"However, it does not appear that module `{module}` was imported.\n"
""
msgstr "இது நடக்கக்கூடாது:\n"
"`{module}` தொகுதிக்கு `{attribute}` என்ற பண்புக்கூறு இல்லை என்று பைதான் நமக்குச் சொல்கிறது.\n"
"இருப்பினும், தொகுதி `{module}` இறக்குமதி செய்யப்பட்டதாகத் தெரியவில்லை.\n"
""

#: runtime_errors\attribute_error.py:99 runtime_errors\attribute_error.py:107
#: runtime_errors\attribute_error.py:140 runtime_errors\attribute_error.py:394
#: runtime_errors\import_error.py:118 runtime_errors\key_error.py:194
#: runtime_errors\key_error.py:201 runtime_errors\module_not_found_error.py:129
#: runtime_errors\name_error.py:97 runtime_errors\name_error.py:99
#: runtime_errors\unbound_local_error.py:55
#: syntax_errors\message_analyzer.py:405 syntax_errors\message_analyzer.py:999
#: syntax_errors\statement_analyzer.py:1221
msgid "Did you mean `{name}`?\n"
""
msgstr "`{name}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\attribute_error.py:100
msgid "Perhaps you meant to write `{module}.{correct}` instead of `{module}.{typo}`\n"
""
msgstr "`{module}.{typo}` என்பதற்குப் பதிலாக `{module}.{correct}` என்று எழுத நினைத்திருக்கலாம்\n"
""

#: runtime_errors\attribute_error.py:108
msgid "Instead of writing `{module}.{typo}`, perhaps you meant to write one of \n"
"the following names which are attributes of module `{module}`:\n"
"`{names}`\n"
""
msgstr "`{module}.{typo}` என்று எழுதுவதற்குப் பதிலாக, அதில் ஒன்றை எழுத நினைத்திருக்கலாம்\n"
"பின்வரும் பெயர்கள் தொகுதியின் பண்புக்கூறுகள் `{module}`:\n"
"`{names}`\n"
""

#: runtime_errors\attribute_error.py:119
msgid "You imported a module named `{module}` from `{mod_path}`.\n"
"There is also a module named `{module}` in Python's standard library.\n"
"Perhaps you need to rename your module.\n"
""
msgstr "`{mod_path}` இலிருந்து `{module}` என்ற தொகுதியை இறக்குமதி செய்துள்ளீர்கள்.\n"
"பைத்தானின் நிலையான நூலகத்தில் `{module}` என்ற பெயருடைய ஒரு தொகுதியும் உள்ளது.\n"
"ஒருவேளை நீங்கள் உங்கள் தொகுதிக்கு மறுபெயரிட வேண்டும்.\n"
""

#: runtime_errors\attribute_error.py:141
msgid "Perhaps you meant to use the attribute `{attribute}` of \n"
"module `{mod_name}` instead of module `{module}`.\n"
""
msgstr "ஒருவேளை நீங்கள் `{attribute}` என்ற பண்புக்கூறைப் பயன்படுத்த நினைத்திருக்கலாம்\n"
"தொகுதி `{module}` என்பதற்குப் பதிலாக `{mod_name}` தொகுதி.\n"
""

#: runtime_errors\attribute_error.py:147
msgid "Did you mean one of the following modules: `{names}`?"
msgstr "பின்வரும் தொகுதிக்கூறுகளில் ஒன்றைக் குறிப்பிடுகிறீர்களா: `{names}`?"

#: runtime_errors\attribute_error.py:150
msgid "Instead of the module `{module}`, perhaps you wanted to use\n"
"the attribute `{attribute}` of one of the following modules:\n"
"`{names}`.\n"
""
msgstr "தொகுதிக்கு பதிலாக `{module}`, ஒருவேளை நீங்கள் பயன்படுத்த வேண்டும்\n"
"பின்வரும் தொகுதிகளில் ஒன்றின் பண்பு `{attribute}`:\n"
"`{names}`.\n"
""

#: runtime_errors\attribute_error.py:159
msgid "Python tells us that no object with name `{attribute}` is\n"
"found in module `{module}`.\n"
""
msgstr "`{attribute}` என்ற பெயரில் எந்தப் பொருளும் `{module}` தொகுதியில்\n"
"காணப்படவில்லை என்று பைதான் நமக்குச் சொல்கிறது.\n"
""

#: runtime_errors\attribute_error.py:190
msgid "You are attempting to access the attribute `{attr}`\n"
"for a variable whose value is `None`."
msgstr "நீங்கள் `{attr}` என்ற பண்புக்கூறை அணுக முயற்சிக்கிறீர்கள், \n"
"அதன் மதிப்பு `None`."

#: runtime_errors\attribute_error.py:211
msgid "The value of attribute `{attribute}` of objects of type `{obj_type}`\n"
"cannot be changed.\n"
"I have no further information.\n"
""
msgstr "`{obj_type}` வகையின் பொருள்களின் `{attribute}` பண்புக்கூறின்\n"
"மதிப்பை மாற்ற முடியாது.\n"
"எனக்கு மேலும் எந்த தகவலும் இல்லை.\n"
""

#: runtime_errors\attribute_error.py:230
msgid "Object `{name}` uses an empty `__slots__` to prevent the modification\n"
"of any of its attributes.\n"
""
msgstr "பொருள் `{name}` அதன் பண்புக்கூறுகளில் ஏதேனும் மாற்றத்தைத் தடுக்க\n"
"வெற்று `__slots__` ஐப் பயன்படுத்துகிறது.\n"
""

#: runtime_errors\attribute_error.py:236
msgid "Object `{name}` uses `__slots__` to specify which attributes can\n"
"be changed. The value of attribute `{name}.{attribute}` cannot be changed.\n"
""
msgstr "எந்தப் பண்புக்கூறுகளை மாற்றலாம் என்பதைக் குறிப்பிட `{name}` பொருள் `__slots__` ஐப் பயன்படுத்துகிறது.\n"
"பண்புக்கூறின் மதிப்பை `{name}.{attribute}` மாற்ற முடியாது.\n"
""

#: runtime_errors\attribute_error.py:261
msgid "`{obj_name}` is a function. Perhaps you meant to write\n"
"`{obj_name}({attribute})`\n"
""
msgstr "`{obj_name}` என்பது ஒரு செயல்பாடு. ஒருவேளை நீங்கள் \n"
"`{obj_name}({attribute})` என்று எழுத நினைத்திருக்கலாம்\n"
""

#: runtime_errors\attribute_error.py:265
msgid "Did you mean `{obj_name}({attribute})`?\n"
""
msgstr "`{obj_name}({attribute})` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\attribute_error.py:270
msgid "`{obj_name}` is a Python built-in function or method\n"
"which does not have an attribute named `{attribute}.`\n"
""
msgstr "`{obj_name}` என்பது பைதான் உள்ளமைக்கப்பட்ட செயல்பாடு அல்லது \n"
"முறையானது `{attribute}' என்ற பண்புக்கூறைக் கொண்டிருக்கவில்லை.\n"
""

#: runtime_errors\attribute_error.py:289
msgid "An object of type `{obj_type}` has no attribute named `{attr}`.\n"
"Unfortunately I cannot find such an object on the line where\n"
"the problem occurs.\n"
""
msgstr "`{obj_type}` வகைப் பொருளில் `{attr}` என்ற பண்புக்கூறு இல்லை.\n"
"எதிர்பாராதவிதமாக, சிக்கல் ஏற்படும் இடத்தில் இதுபோன்ற ஒரு பொருளை \n"
"என்னால் கண்டுபிடிக்க முடியவில்லை.\n"
""

#: runtime_errors\attribute_error.py:317
msgid "An object of type `{obj_type}` has no attribute named `{attr}`.\n"
"\n"
"I cannot give additional information:\n"
"I found one object of this type in the current scope\n"
"but it does not appear to be the object causing the problem.\n"
""
msgstr "`{obj_type}` வகைப் பொருளில் `{attr}` என்ற பண்புக்கூறு இல்லை.\n"
"\n"
"கூடுதல் தகவல்களை என்னால் கொடுக்க முடியாது:\n"
"தற்போதைய நோக்கத்தில் இந்த வகைப் பொருளைக் கண்டேன் \n"
"ஆனால் அது சிக்கலை ஏற்படுத்தும் பொருளாகத் தெரியவில்லை.\n"
""

#: runtime_errors\attribute_error.py:326
msgid "An object of type `{obj_type}` has no attribute named `{attr}`.\n"
"\n"
"The following objects might be the cause of the problem: \n"
"{names}.\n"
""
msgstr "`{obj_type}` வகைப் பொருளில் `{attr}` என்ற பண்புக்கூறு இல்லை.\n"
"\n"
"பின்வரும் பொருள்கள் சிக்கலுக்கு காரணமாக இருக்கலாம்:\n"
"{names}.\n"
""

#: runtime_errors\attribute_error.py:366
msgid "The object `{obj}` has no attribute named `{attr}`.\n"
""
msgstr "`{obj}` பொருளில் `{attr}` என்ற பண்புக்கூறு இல்லை.\n"
""

#: runtime_errors\attribute_error.py:370
msgid "Note that object `{obj}` uses `__slots__` which prevents\n"
"the creation of new attributes.\n"
""
msgstr "`{obj}` பொருள் `__slots__` ஐப் பயன்படுத்துகிறது, இது புதிய \n"
"பண்புக்கூறுகளை உருவாக்குவதைத் தடுக்கிறது.\n"
""

#: runtime_errors\attribute_error.py:378
msgid "The following are some of its known attributes:\n"
"`{names}`."
msgstr "அதன் அறியப்பட்ட சில பண்புக்கூறுகள் பின்வருமாறு:\n"
"`{names}`."

#: runtime_errors\attribute_error.py:390
msgid "The object `{obj_name}` has no attribute named `{attribute}`.\n"
""
msgstr "`{obj_name}` என்ற பொருளுக்கு `{attribute}` என்ற பண்புக்கூறு இல்லை.\n"
""

#: runtime_errors\attribute_error.py:395
msgid "Perhaps you meant to write `{obj}.{correct}` instead of `{obj}.{typo}`\n"
""
msgstr "நீங்கள் `{obj}.{typo}` என்பதற்குப் பதிலாக `{obj}.{correct}` என்று எழுத நினைத்திருக்கலாம்\n"
""

#: runtime_errors\attribute_error.py:401 runtime_errors\import_error.py:125
msgid "Did you mean one of the following: `{names}`?\n"
""
msgstr "பின்வருவனவற்றில் ஒன்றைக் குறிப்பிடுகிறீர்களா: `{names}`?\n"
""

#: runtime_errors\attribute_error.py:402
msgid "Instead of writing `{obj}.{typo}`, perhaps you meant to write one of \n"
"the following names which are attributes of object `{obj}`:\n"
"`{names}`\n"
""
msgstr "`{obj}.{typo}` என்று எழுதுவதற்குப் பதிலாக, `{obj}`: `{names}` என்ற \n"
"பொருளின் பண்புக்கூறுகளான பின்வரும் பெயர்களில் ஒன்றை எழுத \n"
"நினைத்திருக்கலாம்\n"
""

#: runtime_errors\attribute_error.py:427 syntax_errors\message_analyzer.py:1619
#: syntax_errors\message_analyzer.py:1632
msgid "Did you write a comma by mistake?\n"
""
msgstr "தவறுதலாக காற்புள்ளியை எழுதினீர்களா?\n"
""

#: runtime_errors\attribute_error.py:428
msgid "`{obj_name}` is a tuple that contains a single item\n"
"which does have `'{attribute}'` as an attribute.\n"
"Perhaps you added a trailing comma by mistake at the end of the line\n"
"where you defined `{obj_name}`.\n"
""
msgstr "`{obj_name}` என்பது `'{attribute}'` பண்புக்கூறாகக் கொண்ட ஒற்றை \n"
"உருப்படியைக் கொண்ட மடங்கு ஆகும். \n"
"நீங்கள் `{obj_name}` வரையறுத்த வரியின் முடிவில் தவறுதலாக \n"
"பின்னிணைந்த காற்புள்ளியைச் சேர்த்திருக்கலாம்.\n"
""

#: runtime_errors\attribute_error.py:441
msgid "Did you mean `{str_content}.join({obj_name})`?\n"
""
msgstr "`{str_content}.join({obj_name})` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\attribute_error.py:442
msgid "The object `{obj_name}` has no attribute named `join`.\n"
"Perhaps you wanted something like `{str_content}.join({obj_name})`.\n"
""
msgstr "`{obj_name}` பொருளில் `join` என்ற பண்புக்கூறு இல்லை.\n"
"`{str_content}.join({obj_name})` போன்ற ஏதாவது ஒன்றை நீங்கள் விரும்பலாம்.\n"
""

#: runtime_errors\attribute_error.py:465
msgid "Did you mean `{known_builtin}({obj_name})`?\n"
""
msgstr "`{known_builtin}({obj_name})` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\attribute_error.py:468
msgid "The object `{obj_name}` has no attribute named `{attribute}`.\n"
"Perhaps you can use the Python builtin function `{known_builtin}` instead:\n"
"`{known_builtin}({obj_name})`."
msgstr "`{obj_name}` என்ற பொருளுக்கு `{attribute}` என்ற பண்புக்கூறு இல்லை.\n"
"அதற்குப் பதிலாக `{known_builtin}` என்ற பைதான் உள்ளமைக்கப்பட்ட செயல்பாட்டைப் பயன்படுத்தலாம்:\n"
"`{known_builtin}({obj_name})`."

#: runtime_errors\attribute_error.py:498
msgid "Did you mean `{attr}`?\n"
""
msgstr "`{attr}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\attribute_error.py:499
msgid "The object `{name}` has no attribute named `{attribute}`.\n"
""
msgstr "`{name}` என்ற பொருளுக்கு `{attribute}` என்ற பண்புக்கூறு இல்லை.\n"
""

#: runtime_errors\attribute_error.py:503
msgid "However, `{attr}` is an attribute of `{name}` with a similar meaning.\n"
""
msgstr "இருப்பினும், `{attr}` என்பது ஒத்த பொருளைக் கொண்ட `{name}` இன் பண்புக்கூறு ஆகும்.\n"
""

#: runtime_errors\attribute_error.py:507
msgid "However, `{name}` has the following attributes with similar meanings:\n"
"`{attributes}`.\n"
""
msgstr "இருப்பினும், `{name}` பின்வரும் பண்புக்கூறுகளை ஒத்த பொருள்களைக் கொண்டுள்ளது:\n"
"`{attributes}`.\n"
""

#: runtime_errors\attribute_error.py:516
msgid "Did you mean to separate object names by a comma?\n"
""
msgstr "பொருளின் பெயர்களை காற்புள்ளியால் பிரிக்க வேண்டுமா?\n"
""

#: runtime_errors\attribute_error.py:518
msgid "`{second}` is not an attribute of `{first}`.\n"
"However, both `{first}` and `{second}` are known objects.\n"
"Perhaps you wrote a period to separate these two objects, \n"
"instead of using a comma.\n"
""
msgstr "`{second}` என்பது `{first}` இன் பண்புக்கூறு அல்ல.\n"
"இருப்பினும், `{first}` மற்றும் `{second}` இரண்டும் அறியப்பட்ட பொருள்கள்.\n"
"காற்புள்ளியைப் பயன்படுத்துவதற்குப் பதிலாக, இந்த இரண்டு பொருட்களையும் \n"
"பிரிக்க நீங்கள் ஒரு நிறுத்தற்குறியை எழுதியிருக்கலாம்.\n"
""

#: runtime_errors\file_not_found_error.py:25
#: runtime_errors\file_not_found_error.py:39
msgid "In your program, the name of the\n"
"file that cannot be found is `{filename}`.\n"
""
msgstr "உங்கள் நிரலில், கண்டறிய முடியாத \n"
"கோப்பின் பெயர் `{filename}`.\n"
""

#: runtime_errors\file_not_found_error.py:33
msgid "{directory}\n"
"is not a valid directory.\n"
""
msgstr "{directory}\n"
"செல்லுபடியாகும் கோப்பகம் அல்ல.\n"
""

#: runtime_errors\file_not_found_error.py:44
msgid "It was expected to be found in the\n"
"`{directory}` directory.\n"
""
msgstr "இது `{directory}` கோப்பகத்தில் காணப்படும் \n"
"என்று எதிர்பார்க்கப்பட்டது.\n"
""

#: runtime_errors\file_not_found_error.py:48
msgid "Did you mean `{similar}`?\n"
""
msgstr "`{similar}` என்று நீங்கள் கூறுகிறீர்களா?\n"
""

#: runtime_errors\file_not_found_error.py:50
msgid "The file `{similar}` has a similar name.\n"
""
msgstr "கோப்பு `{similar}` இதே பெயரைக் கொண்டுள்ளது.\n"
""

#: runtime_errors\file_not_found_error.py:55
msgid "Perhaps you meant one of the following files with similar names:\n"
""
msgstr "இதே பெயர்களைக் கொண்ட பின்வரும் கோப்புகளில் ஒன்றை நீங்கள் குறிப்பிடலாம்:\n"
""

#: runtime_errors\file_not_found_error.py:62 runtime_errors\name_error.py:119
msgid "I have no additional information for you.\n"
""
msgstr "உங்களுக்கான கூடுதல் தகவல் எதுவும் என்னிடம் இல்லை.\n"
""

#: runtime_errors\import_error.py:78
msgid "The object that could not be imported is `{name}`.\n"
"The module or package where it was \n"
"expected to be found is `{module}`.\n"
""
msgstr "இறக்குமதி செய்ய முடியாத பொருள் `{name}`. \n"
"அது கண்டறியப்படும் என எதிர்பார்க்கப்படும் தொகுதி அல்லது \n"
"தொகுப்பு `{module}` ஆகும்.\n"
""

#: runtime_errors\import_error.py:95
msgid "Python indicated that you have a circular import.\n"
"This can occur if executing the code in module 'A'\n"
"results in executing the code in module 'B' where\n"
"an attempt to import a name from module 'A' is made\n"
"before the execution of the code in module 'A' had been completed.\n"
""
msgstr "நீங்கள் ஒரு வட்ட இறக்குமதியைக் கொண்டிருப்பதை பைதான் சுட்டிக்காட்டியது.\n"
"தொகுதி 'A' இல் குறியீட்டை இயக்குவது 'B' தொகுதியில் குறியீட்டை இயக்கும் \n"
"போது இது நிகழலாம், அங்கு தொகுதி 'A' இல் உள்ள குறியீட்டை \n"
"செயல்படுத்துவதற்கு முன்பு தொகுதி 'A' \n"
"இலிருந்து ஒரு பெயரை இறக்குமதி செய்யும் முயற்சி மேற்கொள்ளப்படுகிறது.\n"
""

#: runtime_errors\import_error.py:107
msgid "Inconsistent state: `'{module}'` was apparently not imported.\n"
"As a result, no further analysis can be done.\n"
""
msgstr "சீரற்ற நிலை: `'{module}'` வெளிப்படையாக இறக்குமதி செய்யப்படவில்லை.\n"
"இதன் விளைவாக, மேலும் பகுப்பாய்வு செய்ய முடியாது.\n"
""

#: runtime_errors\import_error.py:119
msgid "Perhaps you meant to import `{correct}` (from `{module}`) instead of `{typo}`\n"
""
msgstr "ஒருவேளை நீங்கள் `{typo}` என்பதற்குப் பதிலாக `{correct}` (from `{module}`) இறக்குமதி செய்ய நினைத்திருக்கலாம்\n"
""

#: runtime_errors\import_error.py:128
msgid "Instead of trying to import `{typo}` from `{module}`, \n"
"perhaps you meant to import one of \n"
"the following names which are found in module `{module}`:\n"
"`{candidates}`\n"
""
msgstr "`{module}` இலிருந்து `{typo}` ஐ இறக்குமதி செய்ய முயற்சிப்பதற்குப் பதிலாக, \n"
"`{module}` தொகுதியில் காணப்படும் பின்வரும் பெயர்களில் ஒன்றை நீங்கள் \n"
"இறக்குமதி செய்ய நினைத்திருக்கலாம்: \n"
"`{candidates}`\n"
""

#: runtime_errors\import_error.py:146
msgid "The object that could not be imported is `{name}`.\n"
""
msgstr "இறக்குமதி செய்ய முடியாத பொருள் `{name}`.\n"
""

#: runtime_errors\import_error.py:198
msgid "The problem was likely caused by what is known as a 'circular import'.\n"
"First, Python imported and started executing the code in file\n"
"   '{file}'.\n"
"which imports module `{last_module}`.\n"
"During this process, the code in another file,\n"
"   '{last_file}'\n"
"was executed. However in this last file, an attempt was made\n"
"to import the original module `{last_module}`\n"
"a second time, before Python had completed the first import.\n"
""
msgstr "'வட்ட இறக்குமதி' என்று அழைக்கப்படுவதால் இந்தச் சிக்கல் ஏற்பட்டிருக்கலாம்.\n"
"முதலில், பைதான் \n"
"    '{file}' \n"
"கோப்பில் குறியீட்டை இறக்குமதி செய்து செயல்படுத்தத் தொடங்கியது.\n"
"இது `{last_module}` தொகுதியை இறக்குமதி செய்கிறது.\n"
"இந்தச் செயல்பாட்டின் போது, மற்றொரு கோப்பில் உள்ள குறியீடு, \n"
"    '{last_file}' \n"
"செயல்படுத்தப்பட்டது. இருப்பினும் இந்த கடைசி கோப்பில், பைதான் முதல் \n"
"இறக்குமதியை முடிப்பதற்கு முன், அசல் தொகுதி `{last_module}` இரண்டாவது முறையாக இறக்குமதி செய்ய முயற்சி செய்யப்பட்டது.\n"
""

#: runtime_errors\index_error.py:36
msgid "You have tried to assign a value to an item of an object\n"
"of type `{obj_type}` which I cannot identify.\n"
"The index you gave was not an allowed value.\n"
""
msgstr "என்னால் அடையாளம் காண முடியாத வகை `{obj_type}` பொருளின் ஒரு \n"
"பொருளுக்கு மதிப்பை ஒதுக்க முயற்சித்தீர்கள்.\n"
"நீங்கள் கொடுத்த குறியீடு அனுமதிக்கப்பட்ட மதிப்பு அல்ல.\n"
""

#: runtime_errors\index_error.py:46
msgid "You have tried to assign a value to index `{index}` of `{name}`,\n"
"{obj_type} of length `{length}`.\n"
""
msgstr "`{name}` இன் குறியீட்டு `{index}`, {obj_type} நீளம் `{length}`க்கு மதிப்பை \n"
"ஒதுக்க முயற்சித்தீர்கள்.\n"
""

#: runtime_errors\index_error.py:57 runtime_errors\index_error.py:144
msgid "The valid index values of `{name}` are integers ranging from\n"
"`{min}` to `{max}`.\n"
""
msgstr "`{name}` இன் செல்லுபடியாகும் குறியீட்டு மதிப்புகள் `{min}` முதல் `{max}` \n"
"வரையிலான முழு எண்களாகும்.\n"
""

#: runtime_errors\index_error.py:62 runtime_errors\index_error.py:149
msgid "Remember: the first item of {obj_type} is not at index 1 but at index 0.\n"
""
msgstr "நினைவில் கொள்ளுங்கள்: {obj_type} இன் முதல் உருப்படி குறியீட்டு 1 இல் இல்லை, ஆனால் குறியீட்டு 0 இல் உள்ளது.\n"
""

#: runtime_errors\index_error.py:67 runtime_errors\index_error.py:154
msgid "`{name}` contains no item.\n"
""
msgstr "`{name}` இல் உருப்படி இல்லை.\n"
""

#: runtime_errors\index_error.py:68
msgid "You have tried to assign a value to index `{index}` of `{name}`,\n"
"{obj_type} which contains no item.\n"
""
msgstr "`{name}` இன் `{index}` குறியீட்டுக்கு மதிப்பை ஒதுக்க முயற்சித்தீர்கள்,\n"
"{obj_type} இதில் உருப்படி இல்லை.\n"
""

#: runtime_errors\index_error.py:97
msgid "You have tried to get an item of an object\n"
"of type `{obj_type}` which I cannot identify.\n"
"The index you gave was not an allowed value.\n"
""
msgstr "என்னால் அடையாளம் காண முடியாத வகை `{obj_type}` \n"
"பொருளைப் பெற முயற்சித்தீர்கள்.\n"
"நீங்கள் கொடுத்த குறியீடு அனுமதிக்கப்பட்ட மதிப்பு அல்ல.\n"
""

#: runtime_errors\index_error.py:124
msgid "You have tried to get an item from `{name}`,\n"
"{obj_type} of length `{length}`, by using a value for the index\n"
"that I cannot determine but which is not allowed.\n"
""
msgstr "`{name}` இலிருந்து உருப்படியைப் பெற முயற்சித்தீர்கள்,\n"
"{obj_type} நீளம் `{length}`, குறியீட்டிற்கான மதிப்பைப் பயன்படுத்துவதன் மூலம், \n"
"என்னால் தீர்மானிக்க முடியாது, ஆனால் இது அனுமதிக்கப்படவில்லை.\n"
""

#: runtime_errors\index_error.py:133
msgid "You have tried to get the item with index `{index}` of `{name}`,\n"
"{obj_type} of length `{length}`.\n"
""
msgstr "`{name}` இன் குறியீட்டு `{index}` உடன் உருப்படியைப் பெற முயற்சித்தீர்கள்,\n"
"{obj_type} நீளம் `{length}`.\n"
""

#: runtime_errors\index_error.py:155
msgid "You have tried to get the item with index `{index}` of `{name}`,\n"
"{obj_type} which contains no item.\n"
""
msgstr "`{name}` இன் குறியீட்டு `{index}` உடன் உருப்படியைப் பெற முயற்சித்தீர்கள்,\n"
"{obj_type} இதில் உருப்படி இல்லை.\n"
""

#: runtime_errors\key_error.py:25
msgid "You tried to retrieve an item from an empty `dict`\n"
"or a similar object which I cannot identify.\n"
""
msgstr "நான் அடையாளம் காண முடியாத வெற்று `dict` அல்லது அதுபோன்ற பொருளில் \n"
"இருந்து ஒரு பொருளை மீட்டெடுக்க முயற்சித்தீர்கள்.\n"
""

#: runtime_errors\key_error.py:31
msgid "`{name}` is an empty `dict`.\n"
""
msgstr "`{name}` என்பது வெற்று `dict`.\n"
""

#: runtime_errors\key_error.py:32
msgid "You tried to retrieve an item from `{name}` which is an empty `dict`.\n"
""
msgstr "`{name}` இலிருந்து ஒரு உருப்படியை மீட்டெடுக்க முயற்சித்தீர்கள், அது வெற்று `dict` ஆகும்.\n"
""

#: runtime_errors\key_error.py:54
msgid "You tried to retrieve an item from an empty ChainMap\n"
"or similar object which I cannot identify.\n"
""
msgstr "நான் அடையாளம் காண முடியாத வெற்று சங்கிலிவரைபடம் அல்லது அதைப் \n"
"போன்ற பொருளில் இருந்து ஒரு பொருளை மீட்டெடுக்க முயற்சித்தீர்கள்.\n"
""

#: runtime_errors\key_error.py:60
msgid "`{name}` is an empty `ChainMap`.\n"
""
msgstr "`{name}` என்பது வெற்று `ChainMap`.\n"
""

#: runtime_errors\key_error.py:61
msgid "You tried to retrieve an item from `{name}` which is an empty `ChainMap`.\n"
""
msgstr "`{name}` இலிருந்து ஒரு உருப்படியை மீட்டெடுக்க முயற்சித்தீர்கள், அது காலியான `ChainMap` ஆகும்.\n"
""

#: runtime_errors\key_error.py:103
msgid "Missing key `{key}` in a `ChainMap` or in a similar object.\n"
""
msgstr "`ChainMap` அல்லது அதைப் போன்ற பொருளில் `{key}` திறவுகோல் இல்லை.\n"
""

#: runtime_errors\key_error.py:147
msgid "A `dict` or a similar object which I cannot identify\n"
"does not have `{key}` as a key.\n"
""
msgstr "ஒரு `dict` அல்லது என்னால் அடையாளம் காண முடியாத ஒத்த பொருளுக்கு \n"
"`{key}` திறவுகோல் இல்லை.\n"
""

#: runtime_errors\key_error.py:154
msgid "The key `{key}` cannot be found in the dict `{name}`.\n"
""
msgstr "`{key}` திறவுகோலை `{name}` இல் காண முடியாது.\n"
""

#: runtime_errors\key_error.py:159
msgid "The key `{key}` cannot be found in `{name}`, an object of type `{obj_type}`.\n"
""
msgstr "`{obj_type}` வகைப் பொருளான `{name}` இல் `{key}` திறவுகோலைக் காண முடியவில்லை.\n"
""

#: runtime_errors\key_error.py:169
msgid "`{name}` contains a string key which is identical to `str({key})`.\n"
"Perhaps you forgot to convert the key into a string.\n"
""
msgstr "`{name}` இல் `str({key})` க்கு ஒத்த சரம் விசை உள்ளது.\n"
"ஒருவேளை நீங்கள் திறவுகோலை சரமாக மாற்ற மறந்துவிட்டீர்கள்.\n"
""

#: runtime_errors\key_error.py:173
msgid "Did you forget to convert `{key}` into a string?\n"
""
msgstr "`{key}` ஐ சரமாக மாற்ற மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\key_error.py:182
msgid "`{key}` is a string.\n"
"There is a key of `{name}` whose string representation\n"
"is identical to `{key}`.\n"
""
msgstr "`{key}` என்பது ஒரு சரம்.\n"
"`{name}` இன் திறவுகோல் உள்ளது, அதன் சரம் பிரதிநிதித்துவம் \n"
"`{key}` ஐ ஒத்ததாக இருக்கும்.\n"
""

#: runtime_errors\key_error.py:187
msgid "Did you convert `{key}` into a string by mistake?\n"
""
msgstr "தவறுதலாக `{key}` ஐ சரமாக மாற்றிவிட்டீர்களா?\n"
""

#: runtime_errors\key_error.py:195
msgid "`{name}` is a key of `{dict_}` which is similar to `{key}`.\n"
""
msgstr "`{name}` என்பது `{dict_}` இன் திறவுகோல், இது `{key}` போன்றது.\n"
""

#: runtime_errors\key_error.py:203
msgid "`{name}` has some keys similar to `{key}` including:\n"
"`{names}`.\n"
""
msgstr "`{name}` என்பது `{key}` போன்ற சில திறவுகோலைகளைக் கொண்டுள்ளது: \n"
"`{names}`.\n"
""

#: runtime_errors\module_not_found_error.py:38
msgid "No additional information available since `{name}` cannot be imported.\n"
""
msgstr "`{name}` இறக்குமதி செய்ய முடியாததால் கூடுதல் தகவல்கள் எதுவும் கிடைக்கவில்லை.\n"
""

#: runtime_errors\module_not_found_error.py:49
msgid "Did you mean `from {name} import {rest}`?\n"
""
msgstr "`from {name} import {rest}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\module_not_found_error.py:52
msgid "`{rest}` is not a separate module but an object that is part of `{name}`.\n"
""
msgstr "`{rest}` என்பது ஒரு தனி தொகுதி அல்ல, ஆனால் `{name}` இன் ஒரு பகுதியாகும்.\n"
""

#: runtime_errors\module_not_found_error.py:62
msgid "Did you mean `import {name}.{attr}`?\n"
""
msgstr "நீங்கள் குறிப்பிடுவது `import {name}.{attr}`?\n"
""

#: runtime_errors\module_not_found_error.py:65
msgid "Perhaps you meant `import {name}.{attr}`.\n"
"`{attr}` is a name similar to `{rest}` and is a module that\n"
"can be imported from `{name}`.\n"
""
msgstr "ஒருவேளை நீங்கள் `import {name}.{attr}` எனக் குறிப்பிட்டிருக்கலாம்.\n"
"`{attr}` என்பது `{rest}` என்பதற்கு ஒத்த பெயராகும், மேலும் இது `{name}` \n"
"இலிருந்து இறக்குமதி செய்யக்கூடிய ஒரு தொகுதியாகும்.\n"
""

#: runtime_errors\module_not_found_error.py:73
msgid "Did you mean `from {name} import {attr}`?\n"
""
msgstr "`from {name} import {attr}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\module_not_found_error.py:76
msgid "Perhaps you meant `from {name} import {attr}`.\n"
"`{attr}` is a name similar to `{rest}` and is an object that\n"
"can be imported from `{name}`.\n"
""
msgstr "ஒருவேளை நீங்கள் `from {name} import {attr}` எனக் கூறியிருக்கலாம்.\n"
"`{attr}` என்பது `{rest}` போன்ற பெயராகும், மேலும் இது `{name}` இலிருந்து \n"
"இறக்குமதி செய்யக்கூடிய ஒரு பொருளாகும்.\n"
""

#: runtime_errors\module_not_found_error.py:83
msgid "Other objects with similar names that are part of\n"
" `{name}` include `{others}`.\n"
""
msgstr "`{name}` இன் பகுதியாக உள்ள ஒத்த பெயர்களைக் கொண்ட பிற பொருள்களில் \n"
"`{others}` அடங்கும்.\n"
""

#: runtime_errors\module_not_found_error.py:89
msgid "`{rest}` cannot be imported from `{name}`.\n"
""
msgstr "`{rest}` ஐ `{name}` இலிருந்து இறக்குமதி செய்ய முடியாது.\n"
""

#: runtime_errors\module_not_found_error.py:100
msgid "The curses module is rarely installed with Python on Windows.\n"
""
msgstr "Windows இல் பைத்தானுடன் curses தொகுதி அரிதாகவே நிறுவப்பட்டுள்ளது.\n"
""

#: runtime_errors\module_not_found_error.py:102
msgid "The curses module is often not installed with Python.\n"
""
msgstr "curses தொகுதி பெரும்பாலும் பைத்தானுடன் நிறுவப்படுவதில்லை.\n"
""

#: runtime_errors\module_not_found_error.py:103
msgid "You have tried to import the curses module.\n"
""
msgstr "நீங்கள் curses தொகுதியை இறக்குமதி செய்ய முயற்சித்தீர்கள்.\n"
""

#: runtime_errors\module_not_found_error.py:122
msgid "No module named `{name}` can be imported.\n"
"Perhaps you need to install it.\n"
""
msgstr "`{name}` என்ற பெயருடைய எந்தத் தொகுதியையும் இறக்குமதி செய்ய முடியாது. \n"
"ஒருவேளை நீங்கள் அதை நிறுவ வேண்டும்.\n"
""

#: runtime_errors\module_not_found_error.py:131
msgid "The following existing modules have names that are similar \n"
"to the module you tried to import: `{names}`\n"
""
msgstr "பின்வரும் தொகுதிகள் நீங்கள் இறக்குமதி செய்ய முயற்சித்த தொகுதிக்கு ஒத்த \n"
"பெயர்களைக் கொண்டுள்ளன: `{names}`\n"
""

#: runtime_errors\module_not_found_error.py:136
msgid "`{name}` is an existing module that has a similar name.\n"
""
msgstr "`{name}` என்பது ஒரே மாதிரியான பெயரைக் கொண்ட ஏற்கனவே உள்ள தொகுதி.\n"
""

#: runtime_errors\name_error.py:18
msgid "You are already using Python!"
msgstr "நீங்கள் ஏற்கனவே பைத்தானைப் பயன்படுத்துகிறீர்கள்!"

#: runtime_errors\name_error.py:62
msgid "In your program, `{var_name}` is an unknown name\n"
"that exists in an enclosing scope,\n"
"but has not yet been assigned a value.\n"
""
msgstr "உங்கள் திட்டத்தில், `{var_name}` என்பது அறியப்படாத பெயராகும், \n"
"இது ஒரு மூடிய நோக்கத்தில் உள்ளது, \n"
"ஆனால் இன்னும் மதிப்பு ஒதுக்கப்படவில்லை.\n"
""

#: runtime_errors\name_error.py:84 runtime_errors\name_error.py:135
msgid "In your program, no object with the name `{var_name}` exists.\n"
""
msgstr "உங்கள் திட்டத்தில், `{var_name}` என்ற பெயரில் எந்தப் பொருளும் இல்லை.\n"
""

#: runtime_errors\name_error.py:134
msgid "Did you mean `1j`?\n"
""
msgstr "`1j` என்று சொன்னீர்களா?\n"
""

#: runtime_errors\name_error.py:138
msgid "However, sometimes `{name}` is intended to represent\n"
"the square root of `-1` which is written as `1j` in Python.\n"
""
msgstr "இருப்பினும், சில நேரங்களில் `{name}` என்பது பைத்தானில் `1j` என எழுதப்பட்ட \n"
"`-1` இன் வர்க்க மூலத்தைக் குறிக்கும்.\n"
""

#: runtime_errors\name_error.py:101
msgid "Did you use a colon instead of an equal sign?\n"
""
msgstr "சம அடையாளத்திற்குப் பதிலாக முக்காற்புள்ளியைப் பயன்படுத்தினீர்களா?\n"
""

#: runtime_errors\name_error.py:153
msgid "`__debug__` is a constant.\n"
""
msgstr "`__debug__` என்பது மாறிலி.\n"
""

#: runtime_errors\name_error.py:154
msgid "`__debug__` is a constant that cannot be deleted.\n"
"In future Python versions, attempting to delete it will be a SyntaxError.\n"
""
msgstr "`__debug__` என்பது நீக்க முடியாத மாறிலி.\n"
"எதிர்கால பைதான் பதிப்புகளில், அதை நீக்க முயற்சிப்பது தொடரியல் பிழையாக இருக்கும்.\n"
""

#: runtime_errors\name_error.py:162
msgid "You must be a fan of PyConAu!\n"
""
msgstr "நீங்கள் PyConAu இன் ரசிகராக இருக்க வேண்டும்!\n"
""

#: runtime_errors\name_error.py:163
msgid "I am guessing that you tried to use (one of) the flipfloperators\n"
"shown during the second Lightning Talk session of PyConAu 2018,\n"
"but that you forgot to install the module from PyPI.\n"
"\n"
"#### Note that it is still a bad idea.\n"
""
msgstr "PyConAu 2018 இன் இரண்டாவது மின்னல் பேச்சு அமர்வின் போது காட்டப்பட்ட \n"
"புரட்டல்இயக்கிகளைப் (ஒன்றைப்) பயன்படுத்த முயற்சித்தீர்கள் என்று நான் நினைக்கிறேன், \n"
"ஆனால் PyPI இலிருந்து தொகுதியை நிறுவ மறந்துவிட்டீர்கள்.\n"
"\n"
"#### இது இன்னும் மோசமான எண்ணம் என்பதை நினைவில் கொள்க.\n"
""

#: runtime_errors\name_error.py:178
msgid "Did you forget to import `{name}`?\n"
""
msgstr "`{name}` இறக்குமதி செய்ய மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\name_error.py:181
msgid "The name `{name}` is not defined in your program.\n"
"Perhaps you forgot to import `{lowercase}` which is found\n"
"in Python's standard library.\n"
""
msgstr "உங்கள் திட்டத்தில் `{name}` என்ற பெயர் வரையறுக்கப்படவில்லை.\n"
"பைத்தானின் நிலையான நூலகத்தில் காணப்படும் `{lowercase}` ஐ இறக்குமதி \n"
"செய்ய மறந்துவிட்டீர்கள்.\n"
""

#: runtime_errors\name_error.py:190
msgid "Note that the name of the module is `{lowercase}` and not `{name}`.\n"
""
msgstr "தொகுதியின் பெயர் `{lowercase}` மற்றும் `{name}` அல்ல என்பதை நினைவில் கொள்ளவும்.\n"
""

#: runtime_errors\name_error.py:208
msgid "The similar name `{name}` was found in the local scope.\n"
""
msgstr "இதேபோன்ற பெயர் `{name}` உள்ளூர் நோக்கத்தில் காணப்பட்டது.\n"
""

#: runtime_errors\name_error.py:209
msgid "The similar name `{name}` was found in the global scope.\n"
""
msgstr "இதேபோன்ற பெயர் `{name}` உலகளாவிய நோக்கத்தில் காணப்பட்டது.\n"
""

#: runtime_errors\name_error.py:210
msgid "The Python builtin `{name}` has a similar name.\n"
""
msgstr "பைதான் உள்ளமைக்கப்பட்ட `{name}` இதே பெயரைக் கொண்டுள்ளது.\n"
""

#: runtime_errors\name_error.py:219 runtime_errors\unbound_local_error.py:125
msgid "Instead of writing `{name}`, perhaps you meant one of the following:\n"
""
msgstr "`{name}` என்று எழுதுவதற்குப் பதிலாக, நீங்கள் பின்வருவனவற்றில் ஒன்றைக் குறிப்பிட்டிருக்கலாம்:\n"
""

#: runtime_errors\name_error.py:224 runtime_errors\unbound_local_error.py:129
msgid "*   Local scope: "
msgstr "*   உள்ளூர் நோக்கம்: "

#: runtime_errors\name_error.py:225
msgid "*   Global scope: "
msgstr "*   உலகளாவிய நோக்கம்: "

#: runtime_errors\name_error.py:226
msgid "*   Python builtins: "
msgstr "*   பைதான் உள்ளமைக்கப்பட்டவைகள்: "

#: runtime_errors\name_error.py:288
msgid "Did you write `self` at the wrong place?\n"
""
msgstr "நீங்கள் தவறான இடத்தில் `self` என்று எழுதினீர்களா?\n"
""

#: runtime_errors\name_error.py:289
msgid "The {scope} object `{obj}`\n"
"has an attribute named `{unknown_name}`.\n"
"Perhaps you should have written `self.{unknown_name}(...`\n"
"instead of `{unknown_name}(self, ...`.\n"
""
msgstr "{scope} பொருள் `{obj}` ஆனது `{unknown_name}` \n"
"என்ற பண்புக்கூறைக் கொண்டுள்ளது.\n"
"நீங்கள் `{unknown_name}(self, ...` என்பதற்குப் பதிலாக `self.{unknown_name}(...` \n"
"என்று எழுதியிருக்கலாம்.\n"
""

#: runtime_errors\name_error.py:296
msgid "Did you forget to add `self.`?\n"
""
msgstr "`self.` சேர்க்க மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\name_error.py:297
msgid "A {scope} object, `{obj}`,\n"
"has an attribute named `{unknown_name}`.\n"
"Perhaps you should have written `self.{unknown_name}`\n"
"instead of `{unknown_name}`.\n"
""
msgstr "ஒரு {scope} பொருள், `{obj}`, \n"
"`{unknown_name}` என்ற பண்புக்கூறைக் கொண்டுள்ளது.\n"
"ஒருவேளை நீங்கள் `{unknown_name}` என்பதற்குப் பதிலாக \n"
"`self.{unknown_name}` என்று எழுதியிருக்க வேண்டும்.\n"
""

#: runtime_errors\name_error.py:304
msgid "Did you forget to add `{name}.`?\n"
""
msgstr "`{name}.` சேர்க்க மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\name_error.py:305
msgid "The {scope} object `{name}`\n"
"has an attribute named `{unknown_name}`.\n"
"Perhaps you should have written `{name}.{unknown_name}`\n"
"instead of `{unknown_name}`.\n"
""
msgstr "{scope} பொருள் `{name}` ஆனது \n"
"`{unknown_name}` என்ற பண்புக்கூறைக் கொண்டுள்ளது.\n"
"ஒருவேளை நீங்கள் `{unknown_name}` என்பதற்குப் பதிலாக \n"
"`{name}.{unknown_name}` என்று எழுதியிருக்க வேண்டும்.\n"
""

#: runtime_errors\os_error.py:23
msgid "I suspect that you are trying to connect to a server and\n"
"that a connection cannot be made.\n"
"\n"
"If that is the case, check for typos in the URL\n"
"and check your internet connectivity.\n"
""
msgstr "நீங்கள் ஒரு சேவையகத்துடன் இணைக்க முயற்சிக்கிறீர்கள் மற்றும் இணைப்பை \n"
"உருவாக்க முடியாது என்று நான் சந்தேகிக்கிறேன்.\n"
"\n"
"அப்படியானால், URL இல் எழுத்துப் பிழைகளைச் சரிபார்த்து, \n"
"உங்கள் இணைய இணைப்பைச் சரிபார்க்கவும்.\n"
""

#: runtime_errors\os_error.py:42 syntax_errors\message_analyzer.py:1709
msgid "Perhaps you need to double the backslash characters.\n"
""
msgstr "ஒருவேளை நீங்கள் பின்சாய்வு எழுத்துகளை இரட்டிப்பாக்க வேண்டும்.\n"
""

#: runtime_errors\os_error.py:43
msgid "I suspect that you wrote a filename or path that contains\n"
"at least one backslash character, `\\`.\n"
"Python likely interpreted this as indicating the beginning of\n"
"what is known as an escape sequence.\n"
"To solve the problem, either write a so-called 'raw string'\n"
"by adding the letter `r` as a prefix in\n"
"front of the filename or path, or replace all single backslash\n"
"characters, `\\`, by double ones: `\\\\`.\n"
""
msgstr "குறைந்தது ஒரு பின்சாய்வு எழுத்து, `\\` உள்ள கோப்புப் பெயர் அல்லது பாதையை \n"
"நீங்கள் எழுதியிருக்கிறீர்கள் என்று நான் சந்தேகிக்கிறேன். \n"
"தப்பிக்கும் வரிசை என அறியப்படுவதன் தொடக்கத்தைக் குறிப்பதாக பைதான் இதை \n"
"விளக்கியிருக்கலாம். \n"
"சிக்கலைத் தீர்க்க, கோப்புப் பெயர் அல்லது பாதையின் முன் முன்னொட்டாக `r` \n"
"என்ற எழுத்தைச் சேர்ப்பதன் மூலம் 'மூல சரம்' என அழைக்கப்படுவதை எழுதுங்கள் \n"
"அல்லது அனைத்து ஒற்றை பின்சாய்வு எழுத்துகளான `\\`, இரட்டை எழுத்துக்களால் \n"
"மாற்றவும்: `\\\\`.\n"
""

#: runtime_errors\type_error.py:53
msgid "Did you forget to convert the string `{name}` into {number_type}?\n"
""
msgstr "`{name}` சரத்தை {number_type} ஆக மாற்ற மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:58
msgid "Perhaps you forgot to convert the string `{name}` into {number_type}.\n"
""
msgstr "ஒருவேளை நீங்கள் `{name}` சரத்தை {number_type} ஆக மாற்ற மறந்துவிட்டீர்கள்.\n"
""

#: runtime_errors\type_error.py:99 runtime_errors\type_error.py:123
msgid "You tried to concatenate (add) two different types of objects:\n"
"{first} and {second}.\n"
""
msgstr "நீங்கள் இரண்டு வெவ்வேறு வகையான பொருட்களை இணைக்க (சேர்க்க) முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:154
msgid "You tried to add two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருட்களைச் சேர்க்க முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:162
msgid "You tried to subtract two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருள்களைக் கழிக்க முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:170
msgid "You tried to multiply two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருட்களைப் பெருக்க முயற்சித்தீர்கள்:\n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:178
msgid "You tried to divide two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருட்களைப் வகுக்க முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:186
msgid "You tried to perform the bitwise operation {operator}\n"
"on two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருட்களைப் இருமஇலக்கபடி செயல்பாட்டை \n"
"{operator} செய்ய முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:201 runtime_errors\type_error.py:760
#: runtime_errors\type_error.py:866 syntax_errors\statement_analyzer.py:1103
#: syntax_errors\statement_analyzer.py:1334
msgid "Did you mean `{line}`?\n"
""
msgstr "`{line}` என்று சொன்னீர்களா?\n"
""

#: runtime_errors\type_error.py:202
msgid "Outside of Python, `^` is often used to indicate exponentiation.\n"
""
msgstr "பைத்தானுக்கு வெளியே, `^` என்பது அடிக்கடி அதிவேகத்தைக் குறிக்கப் பயன்படுகிறது.\n"
""

#: runtime_errors\type_error.py:205 runtime_errors\type_error.py:763
msgid "Perhaps you meant `{line}`.\n"
""
msgstr "ஒருவேளை நீங்கள் `{line}` என்று சொன்னீர்களா.\n"
""

#: runtime_errors\type_error.py:208
msgid "You tried to perform the bit shifting operation {operator}\n"
"on two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருள்களில் இருமிலக்க நகர்த்தி இயக்கி \n"
"{operator} செய்ய முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:218
msgid "You tried to exponentiate (raise to a power)\n"
"using two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருட்களைப் பயன்படுத்தி, \n"
"அடுக்குக்கு விரிவுபடுத்த (ஒரு அடுக்குக்கு உயர்த்த) முயற்சித்தீர்கள்:\n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:227
msgid "You tried to use the operator {operator}\n"
"using two incompatible types of objects:\n"
"{first} and {second}.\n"
"This operator is normally used only\n"
"for multiplication of matrices.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருட்களைப் பயன்படுத்தி இயக்கியை \n"
"{operator} பயன்படுத்த முயற்சித்தீர்கள்:\n"
"{first} மற்றும் {second}.\n"
"இந்த இயக்கி பொதுவாக அணிகளை பெருக்க மட்டுமே \n"
"பயன்படுத்தப்படுகிறது.\n"
""

#: runtime_errors\type_error.py:263
msgid "Complex numbers cannot be ordered.\n"
""
msgstr "சிக்கலெண்களை வரிசையாக அடுக்க முடியாது.\n"
""

#: runtime_errors\type_error.py:264
msgid "You tried to do an order comparison ({operator})\n"
"between two complex numbers.\n"
""
msgstr "இரண்டு சிக்கலெண்களுக்கு இடையே வரிசை ஒப்பீடு ({operator}) \n"
"செய்ய முயற்சித்தீர்கள்.\n"
""

#: runtime_errors\type_error.py:270
msgid "You tried to do an order comparison ({operator})\n"
"between two incompatible types of objects:\n"
"{first} and {second}.\n"
""
msgstr "பொருந்தாத இரண்டு வகையான பொருள்களுக்கு இடையே ({operator}) \n"
"வரிசை ஒப்பீடு செய்ய முயற்சித்தீர்கள்: \n"
"{first} மற்றும் {second}.\n"
""

#: runtime_errors\type_error.py:319
msgid "Perhaps you meant to write `{operator}=` instead of `={operator}`"
msgstr "ஒருவேளை நீங்கள் `={operator}` என்பதற்குப் பதிலாக `{operator}=` என்று எழுத நினைத்திருக்கலாம்"

#: runtime_errors\type_error.py:323
msgid "You tried to use the unary operator '{operator}'\n"
"with the following type of object: {obj}.\n"
"This operation is not defined for this type of object.\n"
""
msgstr "பின்வரும் வகை பொருளுடன் '{operator}' unary இயக்கியைப்\n"
" பயன்படுத்த முயற்சித்தீர்கள்: {obj}. \n"
"இந்த வகையான பொருளுக்கு இந்த செயல்பாடு வரையறுக்கப்படவில்லை.\n"
""

#: runtime_errors\type_error.py:349
msgid "In Python, some objects are known as immutable:\n"
"once defined, their value cannot be changed.\n"
"You tried change part of such an immutable object: {obj},\n"
"most likely by using an indexing operation.\n"
""
msgstr "பைத்தானில், சில பொருள்கள் மாறாதவை என்று அறியப்படுகின்றன: \n"
"ஒருமுறை வரையறுக்கப்பட்டால், அவற்றின் மதிப்பை மாற்ற முடியாது. \n"
"அத்தகைய ஒரு மாறாத பொருளின் பகுதியை மாற்ற முயற்சித்தீர்கள்: {obj}, \n"
"பெரும்பாலும் அட்டவணைப்படுத்தல் செயல்பாட்டைப் பயன்படுத்தி.\n"
""

#: runtime_errors\type_error.py:356
msgid "Did you mean to use a list?\n"
""
msgstr "பட்டியலைப் பயன்படுத்த விரும்புகிறீர்களா?\n"
""

#: runtime_errors\type_error.py:357
msgid "Perhaps you meant to use a list instead.\n"
""
msgstr "அதற்குப் பதிலாகப் பட்டியலைப் பயன்படுத்த நினைத்திருக்கலாம்.\n"
""

#: runtime_errors\type_error.py:370
msgid "In Python 3, exceptions must be derived from BaseException.\n"
""
msgstr "பைதான் 3 இல், விதிவிலக்குகள் BaseException இலிருந்து பெறப்பட வேண்டும்.\n"
""

#: runtime_errors\type_error.py:406
msgid "You apparently have called the function `{fn_name}` with\n"
"{nb_given} positional argument(s) while it requires {nb_required}\n"
"such positional argument(s).\n"
""
msgstr "நீங்கள் {nb_given} நிலை வாதம்(கள்) உடன் `{fn_name}` \n"
"செயல்பாட்டை அழைத்திருக்கிறீர்கள் \n"
"அதற்கு {nb_required} போன்ற நிலை வாதம்(கள்) தேவைப்படும்.\n"
""

#: runtime_errors\type_error.py:412
msgid "Perhaps you forgot `self` when defining `{fn_name}`.\n"
""
msgstr "`{fn_name}` என்பதை வரையறுக்கும்போது `self` என்பதை மறந்துவிட்டீர்கள்.\n"
""

#: runtime_errors\type_error.py:434
msgid "You apparently have called the function '{fn_name}' with\n"
"fewer positional arguments than it requires ({nb_required} missing).\n"
""
msgstr "'{fn_name}' செயல்பாட்டிற்குத் தேவையானதை விட குறைவான நிலை \n"
"வாதங்களுடன் ({nb_required} இல்லை) என்று நீங்கள் அழைத்திருக்கிறீர்கள்.\n"
""

#: runtime_errors\type_error.py:452 runtime_errors\type_error.py:840
msgid "\n"
"Note: `NoneType` means that the object has a value of `None`.\n"
""
msgstr "\n"
"குறிப்பு: `NoneType` என்பது பொருளுக்கு `None` என்ற மதிப்பு உள்ளது.\n"
""

#: runtime_errors\type_error.py:459
msgid "Python indicates that you have an object of type `{obj_type}`,\n"
"followed by something surrounded by parentheses, `(...)`,\n"
"which Python took as an indication of a function call.\n"
"Either the object of type `{obj_type}` was meant to be a function,\n"
"or you forgot a comma before `(...)`.\n"
""
msgstr "நீங்கள் `{obj_type}` வகைப் பொருளை வைத்திருப்பதை பைதான் குறிக்கிறது, \n"
"அதைத் தொடர்ந்து அடைப்புக்குறிகளால் சூழப்பட்டது `(...)`, \n"
"இது ஒரு செயல்பாட்டு அழைப்பின் அடையாளமாக பைதான் எடுத்தது. \n"
"வகையின் பொருள் `{obj_type}` ஒரு செயல்பாடாக இருக்க வேண்டும் \n"
"அல்லது `(...)` க்கு முன் காற்புள்ளியை மறந்துவிட்டீர்கள்.\n"
""

#: runtime_errors\type_error.py:481
msgid "The parenthesis `()` following `{obj_name}` are interpreted\n"
"by Python as a function call for `{obj_name}`.\n"
"However, `{obj_name}` is not a function but an object of type `{obj_type}`.\n"
""
msgstr "`{obj_name}` என்பதற்குப் பின் வரும் `()` அடைப்புக்குறியானது \n"
"`{obj_name}`க்கான செயல்பாட்டு அழைப்பாக பைத்தானால் விளக்கப்படுகிறது. \n"
"இருப்பினும், `{obj_name}` என்பது ஒரு செயல்பாடு அல்ல, மாறாக `{obj_type}` வகையின் பொருள்.\n"
""

#: runtime_errors\type_error.py:488
msgid "Because of the surrounding parenthesis, `{fn_call}` \n"
"is interpreted by Python as indicating a function call for \n"
"`{obj_name}`, which is an object of type `{obj_type}`\n"
"which cannot be called.\n"
"\n"
""
msgstr "சுற்றியுள்ள அடைப்புக்குறியின் காரணமாக, `{fn_call}` என்பது \n"
"`{obj_name}` க்கான செயல்பாட்டு அழைப்பைக் குறிக்கும் என பைத்தானால் \n"
"விளக்கப்படுகிறது, இது `{obj_type}` வகையின் ஒரு பொருளாகும், \n"
"இது அழைக்கப்பட முடியாது.\n"
"\n"
""

#: runtime_errors\type_error.py:501
msgid "However, `{fn_call}` is a `tuple`.\n"
"Either the object `{obj_name}` was meant to be a function\n"
"or you have a missing comma between the object `{obj_name}`\n"
"and the tuple `{fn_call}` and meant to write\n"
"`{obj_name}, {fn_call}`.\n"
""
msgstr "இருப்பினும், `{fn_call}` என்பது `மடங்கு`.\n"
"பொருள் `{obj_name}` ஒரு செயல்பாடாக இருக்க வேண்டும் அல்லது \n"
"`{obj_name}` மற்றும் மடங்குக்கும் `{fn_call}` ஆகியவற்றுக்கு இடையே ஒரு \n"
"காற்புள்ளி விடுபட்டுள்ளது மற்றும் இவ்வாறு எழுத நினைத்தீர்களா\n"
"`{obj_name}, {fn_call}`.\n"
""

#: runtime_errors\type_error.py:508
msgid "Did you forget a comma between `{obj_name}` and `{fn_call}`?\n"
""
msgstr "`{obj_name}` மற்றும் `{fn_call}` இடையே உள்ள காற்புள்ளியை மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:514
msgid "However, `{obj_name}` is a sequence.\n"
"Perhaps you meant to use `[]` instead of `()` and write\n"
"`{obj_name}[{slice}]`\n"
""
msgstr "இருப்பினும், `{obj_name}` என்பது ஒரு வரிசை.\n"
"ஒருவேளை நீங்கள் `()` என்பதற்குப் பதிலாக `[]` ஐப் பயன்படுத்தி \n"
"`{obj_name}[{slice}]` என்று எழுதலாம்\n"
""

#: runtime_errors\type_error.py:519
msgid "Did you mean `{obj_name}[{slice}]`?\n"
""
msgstr "`{obj_name}[{slice}]` என்பதை நீங்கள் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\type_error.py:535
msgid "Did you mean `{obj_name} * {fn_call}`?\n"
""
msgstr "`{obj_name} * {fn_call}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: runtime_errors\type_error.py:547
msgid "Did you forget to convert `{name}` into an integer?\n"
""
msgstr "`{name}`ஐ முழு எண்ணாக மாற்ற மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:548
msgid "Perhaps you forgot to convert `{name}` into an integer.\n"
""
msgstr "ஒருவேளை நீங்கள் `{name}` ஐ முழு எண்ணாக மாற்ற மறந்துவிட்டீர்கள்.\n"
""

#: runtime_errors\type_error.py:561
msgid "You can only multiply sequences, such as list, tuples,\n"
" strings, etc., by integers.\n"
""
msgstr "பட்டியல், மடங்குகள், சரங்கள், போன்ற., தொடர்களை மட்டுமே \n"
"முழு எண்களால் பெருக்க முடியும்.\n"
""

#: runtime_errors\type_error.py:583
msgid "Did you forget to convert `{name1}` and `{name2}` into integers?\n"
""
msgstr "`{name1}` மற்றும் `{name2}` ஆகியவற்றை முழு எண்களாக மாற்ற மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:586
msgid "Perhaps you forgot to convert `{name1}` and `{name2}` into integers.\n"
""
msgstr "ஒருவேளை நீங்கள் `{name1}` மற்றும் `{name2}` ஐ முழு எண்களாக மாற்ற மறந்து இருக்கலாம்.\n"
""

#: runtime_errors\type_error.py:621
msgid "You wrote an object whose value is `None` where an integer was expected.\n"
""
msgstr "ஒரு முழு எண் எதிர்பார்க்கப்படும் இடத்தில் `None` என்ற பொருளை நீங்கள் எழுதியுள்ளீர்கள்.\n"
""

#: runtime_errors\type_error.py:631
msgid "You wrote an object of type `{obj}` where an integer was expected.\n"
""
msgstr "முழு எண் எதிர்பார்க்கப்படும் `{obj}` வகைப் பொருளை நீங்கள் எழுதியுள்ளீர்கள்.\n"
""

#: runtime_errors\type_error.py:641
msgid "Did you forget to convert `{names}` into integers?\n"
""
msgstr "`{names}` முழு எண்களாக மாற்ற மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:644
msgid "Perhaps you forgot to convert `{names}` into integers."
msgstr "ஒருவேளை நீங்கள் `{names}` ஐ முழு எண்களாக மாற்ற மறந்துவிட்டீர்கள்."

#: runtime_errors\type_error.py:666
msgid "In the expression `{line}`\n"
"what is included between the square brackets, `[...]`,\n"
"must be either an integer or a slice\n"
"(`start:stop` or `start:stop:step`) \n"
"and you have used {obj_type} instead.\n"
""
msgstr "`{line}` வெளிப்பாட்டில், \n"
"சதுர அடைப்புக்குறிகளுக்கு இடையே உள்ளவை, `[...]`, \n"
"ஒரு முழு எண் அல்லது துண்டாக இருக்க வேண்டும் \n"
"(`தொடக்கம்:நிறுத்து` அல்லது `தொடக்கம்:நிறுத்தம்:படி`) \n"
"மற்றும் உங்களிடம் உள்ளது அதற்குப் பதிலாக {obj_type} பயன்படுத்தப்பட்டது.\n"
""

#: runtime_errors\type_error.py:677
msgid "Note: sometimes this exception is raised because what Python\n"
"interprets as indices was meant to be a separate list, and a comma\n"
"should have been written before the opening `[` of that list.\n"
""
msgstr "குறிப்பு: சில நேரங்களில் இந்த விதிவிலக்கு எழுப்பப்படுகிறது, ஏனெனில் பைதான் \n"
"குறியீடுகளாக விளக்குவது ஒரு தனி பட்டியலாக இருக்க வேண்டும், மேலும் அந்த \n"
"பட்டியலின் `[` திறப்பதற்கு முன் காற்புள்ளி எழுதப்பட்டிருக்க வேண்டும்.\n"
""

#: runtime_errors\type_error.py:682 syntax_errors\statement_analyzer.py:1016
#: syntax_errors\statement_analyzer.py:1330
msgid "Did you forget a comma?\n"
""
msgstr "காற்புள்ளியை மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:717
msgid "Perhaps you have forgotten a comma between two identical lists\n"
"`{container}`. The second list had been interpreted as\n"
"the indexation of the first one by the index `{new_index}`\n"
""
msgstr "ஒரே மாதிரியான இரண்டு பட்டியல்களுக்கு இடையே உள்ள காற்புள்ளியை நீங்கள் \n"
"மறந்துவிட்டீர்கள் `{container}`. இரண்டாவது பட்டியல் `{new_index}` குறியீட்டின் \n"
"மூலம் முதல் ஒன்றின் அட்டவணையாக விளக்கப்பட்டது\n"
""

#: runtime_errors\type_error.py:723
msgid "Perhaps you have forgotten a comma between the object `{container}`\n"
"and the list `{index}`.  The list `{index}` had been interpreted as\n"
"the indexation of object `{container}` by the index `{new_index}`\n"
""
msgstr "ஒருவேளை நீங்கள் பொருள் `{container}` \n"
"மற்றும் பட்டியலான `{index}` இடையே ஒரு காற்புள்ளியை மறந்துவிட்டீர்கள்.\n"
"`{index}` என்ற பட்டியல், பொருளின் `{container}` குறியீட்டின் `{new_index}` குறியீட்டால் விளக்கப்பட்டது\n"
""

#: runtime_errors\type_error.py:728
msgid "Did you forget a comma before `{index}`?\n"
""
msgstr "`{index}`க்கு முன் காற்புள்ளியை மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:790
msgid "When using a slice to extract a range of elements\n"
"from a sequence, that is something like\n"
"`[start:stop]` or `[start:stop:step]`\n"
"each of `start`, `stop`, `step` must be either an integer, `None`,\n"
"or possibly some other object having an `__index__` method.\n"
""
msgstr "ஒரு வரிசையிலிருந்து உறுப்புகளின் வரம்பைப் பிரித்தெடுக்க ஒரு துண்டைப் \n"
"பயன்படுத்தும்போது, அது `[தொடக்கம்:நிறுத்து]` அல்லது \n"
"`[தொடக்கம்:நிறுத்தம்:படி]` ஒவ்வொரு `தொடக்கம்`, `நிறுத்தம்`, `படி` போன்றவை  \n"
"ஒரு முழு எண்ணாக இருக்க வேண்டும், `None` அல்லது `__index__` முறையைக் \n"
"கொண்ட வேறு ஏதேனும் பொருள் இருக்கலாம்.\n"
""

#: runtime_errors\type_error.py:809
msgid "Only hashable objects can be used\n"
"as elements of `set` or keys of `dict`.\n"
"Hashable objects are objects that do not change value\n"
"once they have been created."
msgstr "புலபடகூடிய பொருட்களை மட்டுமே `தொகுப்பு` இன் உறுப்புகளாக \n"
"அல்லது `அகராதி` இன் திறவுகோல்களாகப் பயன்படுத்த முடியும். \n"
"புலபடகூடிய பொருள்கள், அவை உருவாக்கப்பட்டவுடன் \n"
"மதிப்பை மாற்றாத பொருள்கள்."

#: runtime_errors\type_error.py:819
msgid "Instead of using {original}, consider using {replacement}.\n"
""
msgstr "{original} ஐப் பயன்படுத்துவதற்குப் பதிலாக, {replacement} ஐப் பயன்படுத்தவும்.\n"
""

#: runtime_errors\type_error.py:846
msgid "Subscriptable objects are typically containers from which\n"
"you can retrieve item using the notation `[...]`.\n"
""
msgstr "சந்தா பெறக்கூடிய பொருள்கள் பொதுவாக கொள்கலன்களாகும், அதில் இருந்து \n"
"நீங்கள் `[...]` குறியீட்டைப் பயன்படுத்தி உருப்படியை மீட்டெடுக்கலாம்.\n"
""

#: runtime_errors\type_error.py:858
msgid "Using this notation, you attempted to retrieve an item\n"
"from an object of type `{obj_type}` which is not allowed.\n"
""
msgstr "இந்தக் குறியீட்டைப் பயன்படுத்தி, அனுமதிக்கப்படாத `{obj_type}` வகைப் \n"
"பொருளிலிருந்து ஒரு பொருளை மீட்டெடுக்க முயற்சித்தீர்கள்.\n"
""

#: runtime_errors\type_error.py:867
msgid "Perhaps you meant to write `{line}`.\n"
""
msgstr "ஒருவேளை நீங்கள் `{line}` என்று எழுத நினைத்திருக்கலாம்.\n"
""

#: runtime_errors\type_error.py:870
msgid "Using this notation, you attempted to retrieve an item\n"
"from `{name}`, an object of type `{obj_type}`. This is not allowed.\n"
""
msgstr "இந்தக் குறியீட்டைப் பயன்படுத்தி, `{obj_type}` வகைப் பொருளான `{name}` இலிருந்து ஒரு பொருளை மீட்டெடுக்க முயற்சித்தீர்கள். \n"
"இதற்கு அனுமதி இல்லை.\n"
""

#: runtime_errors\type_error.py:887
msgid "An iterable is an object capable of returning its members one at a time.\n"
"Python containers (`list, tuple, dict`, etc.) are iterables.\n"
"An iterable is required here.\n"
""
msgstr "மறுசெய்யக்கூடியவை என்பது அதன் உறுப்பினர்களை ஒரு நேரத்தில் திருப்பி அனுப்பும் திறன் கொண்ட ஒரு பொருள்.\n"
"பைதான் கொள்கலன்கள் (`பட்டியல், மடங்கு, அகராதி`, முதலியன.) மறுசெய்யக்கூடியவை. \n"
"இங்கே ஒரு மறுசெய்யக்கூடியவை தேவைப்படுகிறது.\n"
""

#: runtime_errors\type_error.py:904 runtime_errors\value_error.py:24
msgid "Unpacking is a convenient way to assign a name,\n"
"to each item of an iterable.\n"
""
msgstr "கட்டவிழ் என்பது, மறுசெய்யக்கூடிய ஒவ்வொரு பொருளுக்கும் \n"
"ஒரு பெயரை ஒதுக்க ஒரு வசதியான வழியாகும்.\n"
""

#: runtime_errors\type_error.py:908
msgid "An iterable is an object capable of returning its members one at a time.\n"
"Python containers (`list, tuple, dict`, etc.) are iterables,\n"
"but not objects of type `{obj_type}`.\n"
""
msgstr "மறுசெய்யக்கூடியவை என்பது அதன் உறுப்பினர்களை ஒரு நேரத்தில் திருப்பி அனுப்பும் திறன் கொண்ட ஒரு பொருள். \n"
"பைதான் கொள்கலன்கள் (`பட்டியல், மடங்கு, அகராதி`, முதலியன.) மறுசெய்யக்கூடியவை, \n"
"ஆனால் `{obj_type}` வகைப் பொருள்கள் அல்ல.\n"
""

#: runtime_errors\type_error.py:923
msgid "{function} does not accept a sequence as an argument.\n"
"Instead of writing `{line}`\n"
"perhaps you should use the `dict.fromkeys()` method: `{new_line}`.\n"
""
msgstr "{function} ஒரு வரிசையை ஒரு வாதமாக ஏற்கவில்லை. \n"
"`{line}` என்று எழுதுவதற்குப் \n"
"பதிலாக நீங்கள் `dict.fromkeys()` முறையைப் பயன்படுத்த வேண்டும்: `{new_line}`.\n"
""

#: runtime_errors\type_error.py:928
msgid "Perhaps you need to use the `dict.fromkeys()` method.\n"
""
msgstr "ஒருவேளை நீங்கள் `dict.fromkeys()` முறையைப் பயன்படுத்த வேண்டும்.\n"
""

#: runtime_errors\type_error.py:966 runtime_errors\type_error.py:990
msgid "Did you forget to call `{name}`?\n"
""
msgstr "`{name}` என்பதை அழைக்க மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\type_error.py:967 runtime_errors\type_error.py:991
msgid "I suspect that you forgot to add parentheses to call `{name}`.\n"
"You might have meant to write:\n"
"`{line}`\n"
""
msgstr "`{name}` என்பதை அழைக்க, அடைப்புக்குறிகளைச் சேர்க்க மறந்துவிட்டீர்கள் என்று சந்தேகிக்கிறேன். \n"
"நீங்கள் இவ்வாறு எழுத நினைத்திருக்கலாம்: \n"
"`{line}`\n"
""

#: runtime_errors\type_error.py:1005
msgid "The function `vars` is used to list the content of the\n"
"`__dict__` attribute of an object.\n"
""
msgstr "ஒரு பொருளின் `__dict__` பண்புக்கூறின் உள்ளடக்கத்தை பட்டியலிட \n"
"`vars` செயல்பாடு பயன்படுத்தப்படுகிறது.\n"
""

#: runtime_errors\type_error.py:1014
msgid "Object `{name}` uses `__slots__` instead of `__dict__`.\n"
""
msgstr "பொருள் `{name}` `__dict__` என்பதற்குப் பதிலாக `__slots__` ஐப் பயன்படுத்துகிறது.\n"
""

#: runtime_errors\type_error.py:1018
msgid "`{name}`, the argument of `vars`, is an object without such an attribute.\n"
""
msgstr "`{name}`, `vars`ன் வாதம், அத்தகைய பண்பு இல்லாத ஒரு பொருள்.\n"
""

#: runtime_errors\type_error.py:1039
msgid "You have specified the value of argument `{argument}` more than once\n"
"when calling the function named `{function}`.\n"
""
msgstr "`{function}` என்ற செயல்பாட்டை அழைக்கும் போது\n"
"வாதத்தின் மதிப்பை `{argument}` ஒன்றுக்கு மேற்பட்ட முறை குறிப்பிட்டுள்ளீர்கள்.\n"
""

#: runtime_errors\type_error.py:1060
msgid "This function has only one argument: `{arguments}`\n"
""
msgstr "இந்தச் செயல்பாட்டிற்கு ஒரே ஒரு வாதம் உள்ளது: `{arguments}`\n"
""

#: runtime_errors\type_error.py:1064
msgid "This function has the following arguments:\n"
"`{arguments}`\n"
""
msgstr "இந்தச் செயல்பாட்டு பின்வரும் வாதங்களைக் கொண்டுள்ளது: \n"
"`{arguments}`\n"
""

#: runtime_errors\unbound_local_error.py:63
msgid "The name `{var_name}` exists in both the global and nonlocal scope.\n"
"This can be rather confusing and is not recommended.\n"
"Depending on which variable you wanted to refer to, you needed to add either\n"
"\n"
"    global {var_name}\n"
"\n"
"or\n"
"\n"
"    nonlocal {var_name}\n"
"\n"
"as the first line inside your function.\n"
""
msgstr "`{var_name}` என்ற பெயர் உலகளாவிய மற்றும் உள்ளூர்அல்லாத இரண்டிலும் உள்ளது. \n"
"இது மிகவும் குழப்பமானதாக இருக்கலாம் மற்றும் பரிந்துரைக்கப்படவில்லை. \n"
"நீங்கள் எந்த மாறியைப் பார்க்க விரும்புகிறீர்கள் என்பதைப் பொறுத்து, உங்கள் செயல்பாட்டிற்குள் முதல் வரியாக \n"
"\n"
"   global {var_name} \n"
"\n"
"அல்லது\n"
"\n"
"   nonlocal {var_name} \n"
"\n"
"ஐச் சேர்க்க வேண்டும்.\n"
""

#: runtime_errors\unbound_local_error.py:73
msgid "Did you forget to add either `global {var_name}` or \n"
"`nonlocal {var_name}`?\n"
""
msgstr "`global {var_name}` அல்லது `nonlocal {var_name}` ஒன்றைச் சேர்க்க \n"
"மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\unbound_local_error.py:102
msgid "The name `{var_name}` exists in the {scope} scope.\n"
"Perhaps the statement\n"
"\n"
"    {scope} {var_name}\n"
"\n"
"should have been included as the first line inside your function.\n"
""
msgstr "`{var_name}` என்ற பெயர் {scope} நோக்கத்தில் உள்ளது.\n"
"ஒருவேளை \n"
"\n"
"   {scope} {var_name} \n"
"\n"
"என்ற கூற்று உங்கள் செயல்பாட்டிற்குள் முதல் வரியாக சேர்க்கப்பட்டிருக்க வேண்டும்.\n"
""

#: runtime_errors\unbound_local_error.py:109
msgid "Did you forget to add `{scope} {var_name}`?\n"
""
msgstr "`{scope} {var_name}` சேர்க்க மறந்துவிட்டீர்களா?\n"
""

#: runtime_errors\unbound_local_error.py:120
msgid "The similar name `{name}` was found in the local scope. "
msgstr "இதேபோன்ற பெயர் `{name}` உள்ளூர் நோக்கத்தில் காணப்பட்டது. "

#: runtime_errors\value_error.py:73 runtime_errors\value_error.py:82
msgid "In this instance, there are more names ({nb_names})\n"
"than {length}, the length of the iterable.\n"
""
msgstr "இந்த நிகழ்வில், {length} ஐ விட அதிகமான பெயர்கள் ({nb_names}) \n"
"உள்ளன, இது திரும்பச் செய்யக்கூடியது.\n"
""

#: runtime_errors\value_error.py:88
msgid "In this instance, there are more names ({nb_names})\n"
"than the length of the iterable, {iter_type} of length {length}.\n"
""
msgstr "இந்த நிகழ்வில், மறுசெய்யக்கூடிய நீளத்தை விட ({nb_names}) \n"
"அதிக பெயர்கள் உள்ளன, {iter_type} நீளம் {length}.\n"
""

#: runtime_errors\value_error.py:107 runtime_errors\value_error.py:117
msgid "In this instance, there are fewer names ({nb_names})\n"
"than the length of the iterable.\n"
""
msgstr "இந்த நிகழ்வில், மறுசெய்யக்கூடிய நீளத்தை விட குறைவான பெயர்கள் \n"
"({nb_names}) உள்ளன.\n"
""

#: runtime_errors\value_error.py:123
msgid "In this instance, there are fewer names ({nb_names})\n"
"than the length of the iterable, {iter_type} of length {length}.\n"
""
msgstr "இந்த நிகழ்வில், மறுசெய்யக்கூடிய நீளத்தை விட ({nb_names}) \n"
"குறைவான பெயர்கள் உள்ளன, {iter_type} நீளம் {length}.\n"
""

#: runtime_errors\value_error.py:141
msgid "`int()` expects an argument that looks like a number in base `{base}`\n"
"but you gave it an empty string.\n"
""
msgstr "`int()` ஆனது அடிப்படை `{base}` இல் எண்ணைப் போல் தோற்றமளிக்கும் ஒரு \n"
"வாதத்தை எதிர்பார்க்கிறது ஆனால் நீங்கள் அதற்கு வெற்று சரத்தை வழங்கியுள்ளீர்கள்.\n"
""

#: runtime_errors\value_error.py:147
msgid "`{value}` is an invalid argument for `int()` in base `{base}`.\n"
""
msgstr "`{value}` என்பது அடிப்படை `{base}` இல் உள்ள `int()` க்கான தவறான மதிப்புரு.\n"
""

#: runtime_errors\value_error.py:184
msgid "In base `{base}`, `int()` is most often use to convert a string\n"
"containing the digits `0` to `{max_n}` into an integer.\n"
""
msgstr "அடிப்படை `{base}` இல், `int()` என்பது `0` லிருந்து `{max_n}` இலக்கங்களைக் \n"
"கொண்ட சரத்தை முழு எண்ணாக மாற்றப் பயன்படுத்தப்படுகிறது.\n"
""

#: runtime_errors\value_error.py:189
msgid "In base `11`, `int()` is most often use to convert a string\n"
"containing the digits `0` to `9` and the letter `'a'` into an integer.\n"
""
msgstr "அடிப்படை `11` இல், `int()` என்பது இலக்கங்கள் `0` ஐ `9` ஆகவும், `'a'` எழுத்தை \n"
"முழு எண்ணாகவும் மாற்றுவதற்குப் பயன்படுத்தப்படுகிறது.\n"
""

#: runtime_errors\value_error.py:194
msgid "In base `base`, `int()` is most often use to convert a string\n"
"containing the digits `0` to `9` and the letters\n"
"from `'a'` to `'{max_n}'` into an integer.\n"
""
msgstr "அடிப்படை `base` இல், `int()` என்பது இலக்கங்கள் `0` ஆகவும் `9` ஆகவும், \n"
"`'a'` இலிருந்து `'{max_n}'` வரை உள்ள எழுத்துக்களையும் முழு எண்ணாக \n"
"மாற்றப் பயன்படுத்தப்படுகிறது.\n"
""

#: runtime_errors\value_error.py:210
msgid "You need to convert `'{value}'` to a float first.\n"
""
msgstr "நீங்கள் முதலில் `'{value}'` ஐ மிதவையாக மாற்ற வேண்டும்.\n"
""

#: runtime_errors\value_error.py:211
msgid "The string `'{value}'` needs to be first converted using `float()`\n"
"before the result can be converted into an integer using `int()`.\n"
""
msgstr "முடிவை `int()` ஐப் பயன்படுத்தி முழு எண்ணாக மாற்றுவதற்கு முன், \n"
"`'{value}'` சரத்தை முதலில் `float()` ஐப் பயன்படுத்தி மாற்ற வேண்டும்.\n"
""

#: runtime_errors\value_error.py:242
msgid "Did you specify an invalid month?\n"
""
msgstr "செல்லாத மாதத்தைக் குறிப்பிட்டீர்களா?\n"
""

#: runtime_errors\value_error.py:243
msgid "I am guessing that you specify an invalid value for a month\n"
"in a `date` object. Valid values are integers, from 1 to 12.\n"
""
msgstr "`தேதி` பொருளில் ஒரு மாதத்திற்கான தவறான மதிப்பை நீங்கள் குறிப்பிடுகிறீர்கள் என்று நினைக்கிறேன். \n"
"சரியான மதிப்புகள் 1 முதல் 12 வரையிலான முழு எண்களாகும்.\n"
""

#: runtime_errors\value_error.py:277
msgid "The name `{var}` is used both as the name of a class variable\n"
"and as a string item in the class `__slots__`;\n"
"this is not allowed.\n"
""
msgstr "`{var}` என்ற பெயர் வகுப்பு மாறியின் பெயராகவும், `__slots__` வகுப்பில் சரம் \n"
"உருப்படியாகவும் பயன்படுத்தப்படுகிறது; \n"
"இது அனுமதிக்கப்படவில்லை.\n"
""

#: runtime_errors\value_error.py:320
msgid "I do not recognize this error message.\n"
"I am guessing that the problem is with the function `{name}`.\n"
""
msgstr "இந்த பிழைச் செய்தியை என்னால் அடையாளம் காண முடியவில்லை. \n"
"`{name}` செயல்பாட்டில் சிக்கல் இருப்பதாக நான் நினைக்கிறேன்.\n"
""

#: runtime_errors\value_error.py:330
msgid "I have no more information.\n"
""
msgstr "எனக்கு மேலும் எந்த தகவலும் இல்லை.\n"
""

#: runtime_errors\zero_division_error.py:21
msgid "Using the modulo operator, you are dividing by zero.\n"
""
msgstr "மட்டு இயக்கியைப் பயன்படுத்தி, நீங்கள் சுழியத்தால் வகுக்கிறீர்கள்.\n"
""

#: runtime_errors\zero_division_error.py:22
msgid "You are dividing by zero.\n"
""
msgstr "நீங்கள் சுழியத்தால் வகுக்கிறீர்கள்.\n"
""

#: runtime_errors\zero_division_error.py:44
#: runtime_errors\zero_division_error.py:79
msgid "You are dividing by the following term\n"
"\n"
"    {expression}\n"
"\n"
"which is equal to zero.\n"
""
msgstr "சுழியத்திற்குச் சமமான பின்வரும் பதம் \n"
"\n"
"   {expression} \n"
"\n"
"மூலம் நீங்கள் வகுக்கிறீர்கள்.\n"
""

#: runtime_errors\zero_division_error.py:50
#: runtime_errors\zero_division_error.py:58
msgid "The following mathematical expression includes a division by zero:\n"
"\n"
"    {expression}\n"
""
msgstr "பின்வரும் கணித வெளிப்பாடு சுழியத்தால் வகுத்தல்:\n"
"\n"
"   {expression}\n"
""

#: runtime_errors\zero_division_error.py:91
#: runtime_errors\zero_division_error.py:128
msgid "Using the modulo operator, you are dividing by the following term\n"
"\n"
"    {expression}\n"
"\n"
"which is equal to zero.\n"
""
msgstr "மட்டு இயக்கியைப் பயன்படுத்தி, சுழியத்திற்குச் சமமான பின்வரும் பதம் \n"
"\n"
"{expression} \n"
"\n"
"மூலம் வகுக்கிறீர்கள்.\n"
""

#: runtime_errors\zero_division_error.py:99
msgid "The second argument of the `divmod()` function is zero.\n"
""
msgstr "`divmod()` செயல்பாட்டின் இரண்டாவது வாதம் சுழியமாகும்.\n"
""

#: runtime_errors\zero_division_error.py:112
msgid "You are attempting to raise the number 0 to a negative power\n"
"which is equivalent to dividing by zero.\n"
""
msgstr "நீங்கள் எண் 0 ஐ எதிர்மறை சக்தியாக உயர்த்த முயற்சிக்கிறீர்கள், \n"
"இது சுழியத்தால் வகுக்கும் சமமானதாகும்.\n"
""

#: runtime_errors\zero_division_error.py:134
msgid "The following mathematical expression includes a division by zero\n"
"done using the modulo operator:\n"
"\n"
"    {expression}\n"
""
msgstr "பின்வரும் கணித வெளிப்பாட்டில் சுழியத்தால் வகுத்தல் மட்டு இயக்கியைப் \n"
"பயன்படுத்தி செய்யப்படுகிறது: \n"
"\n"
"   {expression}\n"
""

#: runtime_errors\zero_division_error.py:149
msgid "The second argument of the `divmod()` function is equal to zero.\n"
""
msgstr "`divmod()` செயல்பாட்டின் இரண்டாவது வாதம் சுழியத்திற்குச் சமம்.\n"
""

#: syntax_errors\analyze_syntax.py:29
msgid "Currently, I cannot guess the likely cause of this error.\n"
"Try to examine closely the line indicated as well as the line\n"
"immediately above to see if you can identify some misspelled\n"
"word, or missing symbols, like (, ), [, ], :, etc.\n"
"\n"
"Unless your code uses type annotations, which are beyond our scope,\n"
"if you think that this is something which should be handled\n"
"by friendly, please report this case to\n"
"https://github.com/aroberge/friendly/issues\n"
"\n"
""
msgstr "தற்போது, இந்த பிழைக்கான காரணத்தை என்னால் நினைக்க முடியவில்லை. \n"
"(, ), [, ], :, போன்ற எழுத்துப்பிழைகள் அல்லது விடுபட்ட சின்னங்களை உங்களால் \n"
"அடையாளம் காண முடியுமா என்பதைப் பார்க்க, சுட்டிக்காட்டப்பட்ட வரியையும் \n"
"உடனடியாக மேலே உள்ள வரியையும் கவனமாக ஆராய முயற்சிக்கவும். \n"
"\n"
"உங்கள் குறியீடு வகை சிறுகுறிப்புகளைப் பயன்படுத்தாவிட்டால், \n"
"எங்கள் எல்லைக்கு அப்பாற்பட்டது, \n"
"இது நட்புடன் கையாளப்பட வேண்டிய ஒன்று என்று நீங்கள் நினைத்தால், இந்த வழக்கை \n"
"https://github.com/aroberge/friendly/issues க்கு புகாரளிக்கவும்\n"
"\n"
""

#: syntax_errors\analyze_syntax.py:72
msgid "Python told us that it expected a colon at the position indicated.\n"
"However, adding a colon or replacing something else by a colon\n"
"would not fix the problem.\n"
""
msgstr "சுட்டிக்காட்டப்பட்ட நிலையில் ஒரு முக்காற்புள்ளியை எதிர்பார்ப்பதாக பைதான் எங்களிடம் கூறியது. \n"
"இருப்பினும், ஒரு முக்காற்புள்ளியைச் சேர்ப்பது அல்லது முக்காற்புள்ளி மூலம் வேறு \n"
"எதையாவது மாற்றுவது சிக்கலைச் சரிசெய்யாது.\n"
""

#: syntax_errors\analyze_syntax.py:86
msgid "Python gave us the following informative message\n"
"about the possible cause of the error:\n"
"\n"
"    {message}\n"
"\n"
"However, I do not recognize this information and I have\n"
"to guess what caused the problem, but I might be wrong.\n"
"\n"
""
msgstr "பிழையின் சாத்தியமான காரணத்தைப் பற்றி பைதான் எங்களுக்கு பின்வரும் \n"
"தகவலறிந்த செய்தியை வழங்கியது:\n"
"\n"
" {message} \n"
"\n"
"இருப்பினும், இந்தத் தகவலை என்னால் அடையாளம் காண முடியவில்லை, மேலும் \n"
"சிக்கலுக்கு என்ன காரணம் என்று நான் நினைக்க வேண்டும், ஆனால் நான் தவறாக இருக்கலாம்.\n"
"\n"
""

#: syntax_errors\error_in_def.py:18 syntax_errors\statement_analyzer.py:19
msgid "However, making such a change would still not correct\n"
"all the syntax errors in the code you wrote.\n"
""
msgstr "இருப்பினும், அப்படி மாற்றுவது நீங்கள் எழுதிய குறியீட்டில் உள்ள அனைத்து \n"
"தொடரியல் பிழைகளையும் சரி செய்யாது.\n"
""

#: syntax_errors\error_in_def.py:27
msgid "The correct syntax is:\n"
"\n"
"    {async_}def name ( ... ):"
msgstr "சரியான தொடரியல்:\n"
"\n"
"   {async_}def name (... ):"

#: syntax_errors\error_in_def.py:79
msgid "A function needs a name.\n"
""
msgstr "ஒரு செயல்பாட்டிற்கு ஒரு பெயர் தேவை.\n"
""

#: syntax_errors\error_in_def.py:80
msgid "You tried to define a function and did not use the correct syntax.\n"
""
msgstr "நீங்கள் ஒரு செயல்பாட்டை வரையறுக்க முயற்சித்தீர்கள் மற்றும் சரியான தொடரியல் பயன்படுத்தவில்லை.\n"
""

#: syntax_errors\error_in_def.py:84
msgid "Functions and methods need a name.\n"
""
msgstr "செயல்பாடுகள் மற்றும் முறைகளுக்கு ஒரு பெயர் தேவை.\n"
""

#: syntax_errors\error_in_def.py:85
msgid "You tried to define a function or method and did not use the correct syntax.\n"
""
msgstr "நீங்கள் ஒரு செயல்பாடு அல்லது முறையை வரையறுக்க முயற்சித்தீர்கள் மற்றும் சரியான தொடரியல் பயன்படுத்தவில்லை.\n"
""

#: syntax_errors\error_in_def.py:109 syntax_errors\error_in_def.py:135
#: syntax_errors\message_analyzer.py:959 syntax_errors\message_analyzer.py:1463
#: syntax_errors\statement_analyzer.py:1156
#: syntax_errors\statement_analyzer.py:1175
msgid "Did you forget parentheses?\n"
""
msgstr "அடைப்புக்குறிகளை மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\error_in_def.py:110 syntax_errors\error_in_def.py:136
msgid "Perhaps you forgot to include parentheses.\n"
"You might have meant to write\n"
"\n"
"    {line}\n"
""
msgstr "ஒருவேளை நீங்கள் அடைப்புக்குறிக்குள் சேர்க்க மறந்துவிட்டீர்கள். \n"
"நீங்கள் பின்வருமாறு எழுத நினைத்திருக்கலாம்\n"
"\n"
"   {line}\n"
""

#: syntax_errors\error_in_def.py:156
msgid "A function definition statement must end with a colon.\n"
""
msgstr "ஒரு செயல்பாட்டு வரையறை அறிக்கை முக்காற்புள்ளியுடன் முடிவடைய வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:162 syntax_errors\error_in_def.py:185
msgid "Did you forget to write a colon?\n"
""
msgstr "முக்காற்புள்ளியை எழுத மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\error_in_def.py:163 syntax_errors\message_analyzer.py:709
msgid "You wrote `{bad}` instead of a colon.\n"
""
msgstr "முக்காற்புள்ளிக்குப் பதிலாக `{bad}` என்று எழுதியுள்ளீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:172
msgid "Did you write something by mistake after the colon?\n"
""
msgstr "முக்காற்புள்ளிக்குப் பிறகு தவறுதலாக ஏதாவது எழுதிவிட்டீர்களா?\n"
""

#: syntax_errors\error_in_def.py:173
msgid "A block of code must come after the colon.\n"
""
msgstr "முக்காற்புள்ளியைக்குப் பிறகு ஒரு தொகுதி குறியீடு வர வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:174
msgid "Removing `{bad}`, might fix the problem.\n"
""
msgstr "`{bad}` அகற்றினால், சிக்கலைச் சரிசெய்யலாம்.\n"
""

#: syntax_errors\error_in_def.py:199
msgid "You cannot use a Python keyword as a function name.\n"
""
msgstr "நீங்கள் பைதான் முக்கிய சொல்லை செயல்பாட்டு பெயராகப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\error_in_def.py:200
msgid "You tried to use the Python keyword `{kwd}` as a function name.\n"
""
msgstr "நீங்கள் பைதான் முக்கிய சொல்லான `{kwd}` ஐ செயல்பாட்டுப் பெயராகப் பயன்படுத்த முயற்சித்தீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:208
msgid "There are more syntax errors later in your code.\n"
""
msgstr "உங்கள் குறியீட்டில் பின்னர் அதிகமான தொடரியல் பிழைகள் உள்ளன.\n"
""

#: syntax_errors\error_in_def.py:225
msgid "You wrote an invalid function name.\n"
""
msgstr "நீங்கள் தவறான செயல்பாட்டு பெயரை எழுதியுள்ளீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:226
msgid "The name of a function must be a valid Python identifier,\n"
"that is a name that begins with a letter or an underscore character, `_`,\n"
"and which contains only letters, digits or the underscore character.\n"
""
msgstr "ஒரு செயல்பாட்டின் பெயர் செல்லுபடியாகும் பைதான் அடையாளங்காட்டியாக இருக்க வேண்டும், அது ஒரு எழுத்து அல்லது அடிக்கோடிட்ட எழுத்துடன் தொடங்கும் பெயர், \n"
"`_`, \n"
"மேலும் இதில் எழுத்துக்கள், இலக்கங்கள் அல்லது அடிக்கோடி எழுத்து மட்டுமே இருக்கும்.\n"
""

#: syntax_errors\error_in_def.py:232
msgid "You attempted to use a string as a function name.\n"
""
msgstr "நீங்கள் ஒரு சரத்தை செயல்பாட்டுப் பெயராகப் பயன்படுத்த முயற்சித்தீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:247
msgid "You forgot to name your function.\n"
""
msgstr "உங்கள் செயல்பாட்டிற்கு பெயரிட மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:255
msgid "However, there are some other syntax errors in your code.\n"
""
msgstr "இருப்பினும், உங்கள் குறியீட்டில் வேறு சில தொடரியல் பிழைகள் உள்ளன.\n"
""

#: syntax_errors\error_in_def.py:270
msgid "I am guessing that you tried to use the Python keyword\n"
"`{kwd}` as an argument in the definition of a function\n"
"where an identifier (variable name) was expected.\n"
""
msgstr "அடையாளங்காட்டி (மாறி பெயர்) எதிர்பார்க்கப்படும் செயல்பாட்டின் வரையறையில் \n"
"பைதான் முக்கிய சொல்லான `{kwd}` ஐ வாதமாகப் பயன்படுத்த முயற்சித்தீர்கள் என்று \n"
"நினைக்கிறேன்.\n"
""

#: syntax_errors\error_in_def.py:285
msgid "You cannot use dotted names as function arguments.\n"
""
msgstr "நீங்கள் புள்ளியிடப்பட்ட பெயர்களை செயல்பாட்டு வாதங்களாகப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\error_in_def.py:287
msgid "Perhaps you meant to write a comma.\n"
""
msgstr "ஒருவேளை நீங்கள் காற்புள்ளியை எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\error_in_def.py:288 syntax_errors\error_in_def.py:474
#: syntax_errors\statement_analyzer.py:729 syntax_errors\syntax_utils.py:110
msgid "Did you mean to write a comma?\n"
""
msgstr "காற்புள்ளியை எழுத நினைத்தீர்களா?\n"
""

#: syntax_errors\error_in_def.py:292
msgid "You cannot use dots in function names.\n"
""
msgstr "செயல்பாடு பெயர்களில் புள்ளிகளைப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\error_in_def.py:301
msgid "`/` indicates that the previous arguments in a function definition\n"
"are positional arguments.\n"
""
msgstr "`/` ஒரு செயல்பாட்டு வரையறையில் முந்தைய வாதங்கள் நிலை வாதங்கள் \n"
"என்பதைக் குறிக்கிறது.\n"
""

#: syntax_errors\error_in_def.py:307
msgid "Function definitions cannot include the symbol `/` in this Python version.\n"
""
msgstr "இந்த பைதான் பதிப்பில் `/` குறியீட்டை செயல்பாட்டு வரையறைகள் சேர்க்க முடியாது.\n"
""

#: syntax_errors\error_in_def.py:310
msgid "This symbol can only be used with Python versions 3.8.0 or newer.\n"
"You are using Python version {version}.\n"
""
msgstr "இந்த சின்னத்தை பைதான் பதிப்புகள் 3.8.0 அல்லது புதியவற்றில் மட்டுமே பயன்படுத்த முடியும். \n"
"நீங்கள் பைத்தான் பதிப்பு {version} ஐப் பயன்படுத்துகிறீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:319
msgid "You have unspecified keyword arguments that appear before\n"
"the symbol `/`.\n"
""
msgstr "`/` சின்னத்திற்கு முன் தோன்றும் குறிப்பிடப்படாத முக்கியச்சொல் வாதங்கள் உங்களிடம் \n"
"உள்ளன.\n"
""

#: syntax_errors\error_in_def.py:323
msgid "Keyword arguments must appear after the `/` symbol.\n"
""
msgstr "முக்கியச்சொல் வாதங்கள் `/` சின்னத்திற்குப் பிறகு தோன்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:328
msgid "However, `*` indicates that the arguments\n"
"that follow must be keyword arguments.\n"
"When they are used together, `/` must appear before `*`.\n"
""
msgstr "இருப்பினும், பின் வரும் வாதங்கள் முக்கியச்சொல் வாதங்களாக இருக்க வேண்டும் \n"
"என்பதை `*` குறிக்கிறது. அவற்றை ஒன்றாகப் பயன்படுத்தும்போது, \n"
"`*` க்கு முன் `/` தோன்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:333
msgid "`*` must appear after `/` in a function definition.\n"
""
msgstr "`*` ஒரு செயல்பாட்டு வரையறையில் `/` க்குப் பிறகு தோன்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:335
msgid "`*{name}` must appear after `/` in a function definition.\n"
""
msgstr "`*{name}` ஒரு செயல்பாட்டு வரையறையில் `/` க்குப் பிறகு தோன்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:342
msgid "You can only use `/` once in a function definition.\n"
""
msgstr "செயல்பாட்டு வரையறையில் நீங்கள் ஒரு முறை மட்டுமே `/` பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\error_in_def.py:356
msgid "You can only use `*` once in a function definition.\n"
""
msgstr "செயல்பாட்டு வரையறையில் நீங்கள் ஒரு முறை மட்டுமே `*` பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\error_in_def.py:362
msgid "You have used it twice, with `*{first}` and `*{second}`.\n"
""
msgstr "`*{first}` மற்றும் `*{second}` உடன் இருமுறை பயன்படுத்தியுள்ளீர்கள்.\n"
""

#: syntax_errors\error_in_def.py:370
msgid "It must either be used by itself, `*`,\n"
"or in the form `*{args}`, but not both.\n"
""
msgstr "இது தானாகவே பயன்படுத்தப்பட வேண்டும், \n"
"`*` அல்லது `*{args}` வடிவத்தில், ஆனால் இரண்டும் அல்ல.\n"
""

#: syntax_errors\error_in_def.py:379
msgid "`*{args}` must appear before `**{kwargs}`.\n"
""
msgstr "`**{kwargs}` க்கு முன் `*{args}` தோன்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:383
msgid "`**{kwargs}` must appear after the `*` operator.\n"
""
msgstr "`** இயக்கிக்குப் பிறகு `**{kwargs}` தோன்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:397
msgid "You cannot use numbers as function arguments.\n"
""
msgstr "நீங்கள் எண்களை செயல்பாட்டு வாதங்களாகப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\error_in_def.py:398
msgid "You used a number as an argument when defining a function.\n"
"You can only use identifiers (variable names) as function arguments.\n"
""
msgstr "ஒரு செயல்பாட்டை வரையறுக்கும்போது எண்ணை வாதமாகப் பயன்படுத்தியுள்ளீர்கள். \n"
"நீங்கள் அடையாளங்காட்டிகளை (மாறி பெயர்கள்) செயல்பாட்டு வாதங்களாக மட்டுமே பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\error_in_def.py:410
msgid "You cannot use strings as function arguments.\n"
""
msgstr "நீங்கள் சரங்களை செயல்பாட்டு வாதங்களாகப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\error_in_def.py:411
msgid "You used a string as an argument when defining a function.\n"
"You can only use identifiers (variable names) as function arguments.\n"
""
msgstr "ஒரு செயல்பாட்டை வரையறுக்கும்போது ஒரு சரத்தை வாதமாகப் பயன்படுத்தியுள்ளீர்கள். \n"
"நீங்கள் அடையாளங்காட்டிகளை (மாறி பெயர்கள்) செயல்பாட்டு வாதங்களாக மட்டுமே பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\error_in_def.py:423
msgid "You cannot have explicit tuples as function arguments.\n"
""
msgstr "செயல்பாட்டு வாதங்களாக வெளிப்படையான மடங்குகளை நீங்கள் கொண்டிருக்க முடியாது.\n"
""

#: syntax_errors\error_in_def.py:425
msgid "You can only use identifiers (variable names) as function arguments.\n"
"Assign any tuple to a parameter and unpack it\n"
"within the body of the function.\n"
""
msgstr "நீங்கள் அடையாளங்காட்டிகளை (மாறி பெயர்கள்) செயல்பாட்டு வாதங்களாக \n"
"மட்டுமே பயன்படுத்த முடியும். எந்த மடங்கையும் ஒரு அளவுருவுக்கு ஒதுக்கி, \n"
"செயல்பாட்டின் உடலில் அதைத் திறக்கவும்.\n"
""

#: syntax_errors\error_in_def.py:438
msgid "You cannot have explicit lists as function arguments.\n"
""
msgstr "செயல்பாட்டு வாதங்களாக வெளிப்படையான பட்டியல்களை நீங்கள் வைத்திருக்க முடியாது.\n"
""

#: syntax_errors\error_in_def.py:439 syntax_errors\error_in_def.py:451
msgid "You can only use identifiers (variable names) as function arguments.\n"
""
msgstr "நீங்கள் அடையாளங்காட்டிகளை (மாறி பெயர்கள்) செயல்பாட்டு வாதங்களாக மட்டுமே பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\error_in_def.py:450
msgid "You cannot have any explicit dict or set as function arguments.\n"
""
msgstr "உங்களிடம் வெளிப்படையான அகராதி அல்லது தொகுப்பு செயல்பாட்டு வாதங்களாக ஏற்க முடியாது.\n"
""

#: syntax_errors\error_in_def.py:467
msgid "You cannot have operators as function arguments.\n"
""
msgstr "நீங்கள் இயக்கிகளை செயல்பாட்டு வாதங்களாக வைத்திருக்க முடியாது.\n"
""

#: syntax_errors\error_in_def.py:475
msgid "I suspect you made a typo and wrote `{op}` instead of a comma.\n"
"The following statement contains no syntax error:\n"
"\n"
"    {new_statement}"
msgstr "நீங்கள் எழுத்துப்பிழை செய்து காற்புள்ளிக்கு பதிலாக `{op}` என்று எழுதியிருக்கிறீர்கள் என்று சந்தேகிக்கிறேன். \n"
"பின்வரும் அறிக்கையில் தொடரியல் பிழை இல்லை: \n"
"\n"
"   {new_statement}"

#: syntax_errors\error_in_def.py:487
msgid "Did you mean to write an equal sign?\n"
""
msgstr "நீங்கள் சமமான அடையாளத்தை எழுத விரும்புகிறீர்களா?\n"
""

#: syntax_errors\error_in_def.py:488
msgid "I suspect you made a typo and wrote `{op}` instead of an equal sign.\n"
"The following statement contains no syntax error:\n"
"\n"
"    {new_statement}"
msgstr "நீங்கள் எழுத்துப் பிழை செய்து, சம அடையாளத்திற்குப் பதிலாக `{op}` என்று எழுதியிருக்கிறீர்கள் என்று சந்தேகிக்கிறேன். \n"
"பின்வரும் அறிக்கையில் தொடரியல் பிழை இல்லை:\n"
"\n"
"   {new_statement}"

#: syntax_errors\error_in_def.py:500
msgid "Did you mean to write `{op}`?\n"
""
msgstr "`{op}` என்று எழுத வேண்டுமா?\n"
""

#: syntax_errors\error_in_def.py:501
msgid "I suspect you made a typo and added `{op}` by mistake.\n"
"The following statement contains no syntax error:\n"
"\n"
"    {new_statement}"
msgstr "நீங்கள் எழுத்துப்பிழை செய்து, தவறுதலாக `{op}` சேர்த்திருக்கிறீர்கள் என்று சந்தேகிக்கிறேன். \n"
"பின்வரும் அறிக்கையில் தொடரியல் பிழை இல்லை: \n"
"\n"
"   {new_statement}"

#: syntax_errors\error_in_def.py:517
msgid "You cannot use `{op}` as an argument.\n"
""
msgstr "நீங்கள் `{op}` வாதமாகப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\error_in_def.py:521
msgid "I suspect you made a typo and wrote `{op}` by mistake.\n"
"If you replace it by a unique variable name, the result\n"
"will contain no syntax error.\n"
""
msgstr "நீங்கள் எழுத்துப்பிழை செய்து, தவறுதலாக `{op}` என்று எழுதிவிட்டீர்கள் என்று சந்தேகிக்கிறேன். \n"
"நீங்கள் அதை ஒரு தனித்துவமான மாறி பெயரால் மாற்றினால், முடிவில் தொடரியல் \n"
"பிழை இருக்காது.\n"
""

#: syntax_errors\error_in_def.py:529
msgid "I suspect you made a typo and wrote `{op}` by mistake,\n"
"perhaps instead of writing an identifier (variable name).\n"
""
msgstr "நீங்கள் தட்டச்சுப் பிழையைச் செய்துவிட்டு தவறுதலாக `{op}` என்று எழுதியிருக்கலாம், \n"
"ஒருவேளை அடையாளங்காட்டியை (மாறி பெயர்) எழுதுவதற்குப் பதிலாக இருக்கலாம்.\n"
""

#: syntax_errors\error_in_def.py:538
msgid "The `**` operator needs to be followed by an identifier (variable name).\n"
""
msgstr "`**` ஆபரேட்டரை ஒரு அடையாளங்காட்டி (மாறி பெயர்) பின்பற்ற வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:561
msgid "Positional arguments must come before keyword arguments.\n"
""
msgstr "முக்கியச்சொல் வாதங்களுக்கு முன் நிலை வாதங்கள் வர வேண்டும்.\n"
""

#: syntax_errors\error_in_def.py:562
msgid "`{arg}` is a positional argument that appears after one or more\n"
"keyword arguments in your function definition.\n"
""
msgstr "`{arg}` என்பது உங்கள் செயல்பாட்டு வரையறையில் ஒன்று அல்லது அதற்கு \n"
"மேற்பட்ட முக்கியச்சொல் வாதங்களுக்குப் பிறகு தோன்றும் நிலை வாதமாகும்.\n"
""

#: syntax_errors\indentation_error.py:11
msgid "Line `{number}` identified above is more indented than expected.\n"
""
msgstr "மேலே அடையாளம் காணப்பட்ட வரி `{number}` எதிர்பார்த்ததை விட அதிகமாக உள்தள்ளப்பட்டுள்ளது.\n"
""

#: syntax_errors\indentation_error.py:15
msgid "Line `{number}` identified above was expected to begin a new indented block.\n"
""
msgstr "மேலே அடையாளம் காணப்பட்ட வரி `{number}` புதிய உள்தள்ளப்பட்ட தொகுதியைத் தொடங்கும் என எதிர்பார்க்கப்பட்டது.\n"
""

#: syntax_errors\indentation_error.py:20
msgid "Line `{number}` identified above is less indented than expected.\n"
""
msgstr "மேலே அடையாளம் காணப்பட்ட வரி `{number}` எதிர்பார்த்ததை விட குறைவாக உள்தள்ளப்பட்டுள்ளது.\n"
""

#: syntax_errors\indentation_error.py:32
msgid "However, line {number}, which is identified as having a problem,\n"
"consists of a single string which is also the case\n"
"for the preceding line.\n"
"Perhaps you meant to include a continuation character, `\\`,\n"
"at the end of line {preceding}.\n"
""
msgstr "இருப்பினும், சிக்கல் இருப்பதாக அடையாளம் காணப்பட்ட வரி {number}, \n"
"முந்தைய \n"
"வரியிலும் உள்ள ஒற்றை சரத்தைக் கொண்டுள்ளது. \n"
"வரியின் {preceding} முடிவில், `\\` என்ற தொடர்ச்சியை நீங்கள் சேர்க்க \n"
"நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\message_analyzer.py:21
msgid "You can only assign objects to identifiers (variable names).\n"
""
msgstr "அடையாளங்காட்டிகளுக்கு (மாறி பெயர்கள்) மட்டுமே நீங்கள் பொருட்களை ஒதுக்க முடியும்.\n"
""

#: syntax_errors\message_analyzer.py:25
#: syntax_errors\statement_analyzer.py:1452
msgid "You can only delete names of objects, or items in mutable containers\n"
"such as `list`, `set`, or `dict`.\n"
""
msgstr "நீங்கள் பொருள்களின் பெயர்கள் அல்லது `பட்டியல்`, `தொகுப்பு` அல்லது `அகராதி` \n"
"போன்ற மாறக்கூடிய கொள்கலன்களில் உள்ள உருப்படிகளை மட்டுமே நீக்க முடியும்.\n"
""

#: syntax_errors\message_analyzer.py:51
msgid "of type `int`"
msgstr "`முழுஎண்` வகை"

#: syntax_errors\message_analyzer.py:52
msgid "of type `complex`"
msgstr "`சிக்கலான` வகை"

#: syntax_errors\message_analyzer.py:53
msgid "of type `float`"
msgstr "`மிதவைப்புள்ளி` வகை"

#: syntax_errors\message_analyzer.py:54
msgid "of type `str`"
msgstr "`சரம்` வகை"

#: syntax_errors\message_analyzer.py:55
msgid "of type `dict`"
msgstr "`அகராதி` வகை"

#: syntax_errors\message_analyzer.py:56
msgid "of type `list`"
msgstr "`பட்டியல்` வகை"

#: syntax_errors\message_analyzer.py:57
msgid "of type `set`"
msgstr "`தொகுப்பு` வகை"

#: syntax_errors\message_analyzer.py:58
msgid "of type `tuple`"
msgstr "`மடங்கு` வகை"

#: syntax_errors\message_analyzer.py:78 syntax_errors\message_analyzer.py:88
msgid "Did you mean `{num}`?\n"
""
msgstr "`{num}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:79
msgid "Perhaps you meant to write the octal number `{num}`\n"
"and forgot the letter 'o', or perhaps you meant to write\n"
"a decimal integer and did not know that it could not start with zeros.\n"
""
msgstr "ஒருவேளை நீங்கள் `{num}` என்ற எண்ம எண்ணை எழுத எண்ணி, 'o' என்ற \n"
"எழுத்தை மறந்துவிட்டீர்கள், அல்லது ஒரு தசம முழு எண்ணை எழுத \n"
"நினைத்திருக்கலாம், அது சுழியங்களுடன் தொடங்க முடியாது என்று தெரியவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:89
msgid "Perhaps you meant to write the integer `{num}`\n"
"and did not know that it could not start with zeros.\n"
""
msgstr "ஒருவேளை நீங்கள் முழு எண்ணை `{num}` எழுத நினைத்திருக்கலாம், மேலும் \n"
"அது சுழியங்களுடன் தொடங்க முடியாது என்று தெரியவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:145
msgid "On the left-hand side of an equal sign, you have\n"
"an expression instead of the name of a variable.\n"
""
msgstr "சம அடையாளத்தின் இடது புறத்தில், மாறியின் பெயருக்குப் பதிலாக ஒரு \n"
"வெளிப்பாடு உள்ளது.\n"
""

#: syntax_errors\message_analyzer.py:172
msgid "some value"
msgstr "சில மதிப்பு"

#: syntax_errors\message_analyzer.py:173
msgid "You wrote an expression like\n"
"\n"
"    {fn_call} = {value}\n"
"\n"
"where `{fn_call}`, on the left-hand side of the equal sign, is\n"
"a function call and not the name of a variable.\n"
""
msgstr "நீங்கள் இது போன்ற ஒரு வெளிப்பாட்டை எழுதியுள்ளீர்கள், \n"
"\n"
"   {fn_call} = {value} \n"
"\n"
"அங்கு சம அடையாளத்தின் இடது பக்கத்தில் `{fn_call}` என்பது ஒரு செயல்பாட்டு \n"
"அழைப்பாகும், அது மாறியின் பெயர் அல்ல.\n"
""

#: syntax_errors\message_analyzer.py:185
msgid "You wrote the expression\n"
"\n"
"    {fn_call} = {value}\n"
"\n"
"where `{fn_call}`, on the left-hand side of the equal sign, either is\n"
"or includes a function call and is not simply the name of a variable.\n"
""
msgstr "நீங்கள் பின்வரும் சொற்றொடரை எழுதியுள்ளீர்கள்\n"
"\n"
"   {fn_call} = {value} \n"
"\n"
"இங்கு சம அடையாளத்தின் இடது பக்கத்தில் `{fn_call}` என்பது ஒரு செயல்பாட்டு \n"
"அழைப்பாகும் அல்லது அதில் உள்ளடங்கும் மற்றும் இது ஒரு மாறியின் பெயர் அல்ல.\n"
""

#: syntax_errors\message_analyzer.py:202
msgid "On the left-hand side of an equal sign, you have a\n"
"generator expression instead of the name of a variable.\n"
""
msgstr "சம அடையாளத்தின் இடது புறத்தில், மாறியின் பெயருக்குப் பதிலாக \n"
"உருவாக்கி வெளிப்பாடு உள்ளது.\n"
""

#: syntax_errors\message_analyzer.py:213 syntax_errors\message_analyzer.py:324
msgid "You wrote an expression that has the f-string `{fstring}`\n"
"on the left-hand side of the equal sign.\n"
"An f-string should only appear on the right-hand side of an equal sign.\n"
""
msgstr "சம அடையாளத்தின் இடது புறத்தில் f-சரம் `{fstring}` கொண்ட ஒரு \n"
"வெளிப்பாட்டை நீங்கள் எழுதியுள்ளீர்கள். \n"
"ஒரு f-சரம் ஒரு சம அடையாளத்தின் வலது பக்கத்தில் மட்டுமே தோன்றும்.\n"
""

#: syntax_errors\message_analyzer.py:260
msgid "You cannot assign a value to the ellipsis symbol [`...`].\n"
""
msgstr "நீள்வட்டச் சின்னத்திற்கு [`...`] மதிப்பை நீங்கள் ஒதுக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:261
msgid "The ellipsis symbol `...` is a constant in Python;you cannot assign it a different value.\n"
""
msgstr "நீள்வட்டச் சின்னம் `...` என்பது பைத்தானில் ஒரு மாறிலி; அதற்கு வேறு மதிப்பை நீங்கள் ஒதுக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:266
msgid "`{keyword}` is a constant in Python; you cannot assign it a different value.\n"
""
msgstr "`{keyword}` என்பது பைத்தானில் ஒரு மாறிலி; நீங்கள் வேறு மதிப்பை ஒதுக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:271
#: syntax_errors\statement_analyzer.py:892
msgid "You were trying to assign a value to the Python keyword `{keyword}`.\n"
"This is not allowed.\n"
"\n"
""
msgstr "பைதான் முக்கியச்சொல்லான `{keyword}` க்கு மதிப்பை ஒதுக்க முயற்சிக்கிறீர்கள். \n"
"இதற்கு அனுமதி இல்லை.\n"
"\n"
""

#: syntax_errors\message_analyzer.py:287
msgid "A for loop must have the form:\n"
"\n"
"    for ... in sequence:\n"
"\n"
"where `...` must contain only identifiers (variable names)\n"
"and not literals like `{bad_token}`.\n"
""
msgstr "ஒரு சுழல் இந்த படிவத்தைக் கொண்டிருக்க வேண்டும்:\n"
"\n"
"   for ... in sequence: \n"
"\n"
"இங்கு `...` என்பதில் அடையாளங்காட்டிகள் மட்டுமே இருக்க வேண்டும் \n"
"(மாறி பெயர்கள்) மற்றும் `{bad_token}` போன்ற எழுத்துக்கள் இருக்கக்கூடாது.\n"
""

#: syntax_errors\message_analyzer.py:333
msgid "variable_name"
msgstr "மாறி_பெயர்"

#: syntax_errors\message_analyzer.py:337
msgid "Perhaps you meant to write:\n"
"\n"
"    {name} = {literal}\n"
"\n"
""
msgstr "ஒருவேளை நீங்கள் எழுத நினைத்திருக்கலாம்:\n"
"\n"
"   {name} = {literal}\n"
"\n"
""

#: syntax_errors\message_analyzer.py:343
msgid "Perhaps you meant to write `{name} = {literal}`"
msgstr "ஒருவேளை நீங்கள் `{name} = {literal}` என்று எழுத நினைத்திருக்கலாம்"

#: syntax_errors\message_analyzer.py:362
msgid "You wrote an expression like\n"
"\n"
"    {literal} = {name}\n"
"where `{literal}`, on the left-hand side of the equal sign,\n"
"is or includes an actual object {of_type}\n"
"and is not simply the name of a variable.\n"
""
msgstr "நீங்கள் இது போன்ற ஒரு வெளிப்பாட்டை எழுதியுள்ளீர்கள், \n"
"\n"
"   {literal} = {name} \n"
"இங்கு சம அடையாளத்தின் இடது புறத்தில் `{literal}` என்பது ஒரு உண்மையான \n"
"பொருள் {of_type} அல்லது உள்ளடக்கியது \n"
"மற்றும் வெறுமனே ஒரு மாறியின் பெயர் அல்ல.\n"
""

#: syntax_errors\message_analyzer.py:384
msgid "You wrote an expression that includes some mathematical operations\n"
"on the left-hand side of the equal sign which should be\n"
"only used to assign a value to a variable.\n"
""
msgstr "சம அடையாளத்தின் இடது புறத்தில் சில கணித செயல்பாடுகளை உள்ளடக்கிய ஒரு \n"
"வெளிப்பாட்டை நீங்கள் எழுதியுள்ளீர்கள், இது மாறிக்கு மதிப்பை ஒதுக்க மட்டுமே \n"
"பயன்படுத்தப்பட வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:406
msgid "Perhaps you meant to write `{name}` instead of `{original}`\n"
""
msgstr "ஒருவேளை நீங்கள் `{original}` என்பதற்குப் பதிலாக `{name}` என்று எழுத நினைத்திருக்கலாம்\n"
""

#: syntax_errors\message_analyzer.py:411 syntax_errors\message_analyzer.py:547
#: syntax_errors\statement_analyzer.py:523
msgid "Perhaps you needed `==` instead of `=`.\n"
""
msgstr "`=` என்பதற்குப் பதிலாக `==` தேவைப்படலாம்.\n"
""

#: syntax_errors\message_analyzer.py:423
msgid "You wrote an expression that includes the `yield` keyword\n"
"on the left-hand side of the equal sign.\n"
"You cannot assign a value to such an expression.\n"
"Note that, like the keyword `return`,\n"
"`yield` can only be used inside a function.\n"
""
msgstr "சம அடையாளத்தின் இடது புறத்தில் `yield` முக்கிய சொல்லை உள்ளடக்கிய \n"
"ஒரு வெளிப்பாட்டை எழுதியுள்ளீர்கள். \n"
"அத்தகைய வெளிப்பாட்டிற்கு நீங்கள் மதிப்பை ஒதுக்க முடியாது. \n"
"முக்கியச்சொல்லான return`,\n"
"`yield` என்பது ஒரு செயல்பாட்டிற்குள் மட்டுமே பயன்படுத்தப்படும் என்பதை நினைவில் கொள்ளவும்.\n"
""

#: syntax_errors\message_analyzer.py:442 syntax_errors\message_analyzer.py:464
msgid "You are using the augmented assignment operator `:=` inside\n"
"a comprehension to assign a value to the iteration variable `{var}`.\n"
"This variable is meant to be used only inside the comprehension.\n"
"The augmented assignment operator is normally used to assign a value\n"
"to a variable so that the variable can be reused later.\n"
"This is not possible for variable `{var}`.\n"
""
msgstr "மறுசெய்கை மாறி `{var}`க்கு மதிப்பை ஒதுக்க, புரிந்துகொள்ளுதலுக்குள் `:=` \n"
"பெரிதாக்கப்பட்ட ஒதுக்கும் இயக்கியைப் பயன்படுத்துகிறீர்கள். \n"
"இந்த மாறியானது புரிதலின் உள்ளே மட்டுமே பயன்படுத்தப்பட வேண்டும். \n"
"பெரிதாக்கப்பட்ட ஒதுக்கும் இயக்கி பொதுவாக ஒரு மாறிக்கு மதிப்பை \n"
"ஒதுக்கப் பயன்படுகிறது, இதனால் மாறி பின்னர் மீண்டும் பயன்படுத்தப்படலாம். \n"
"`{var}` மாறிக்கு இது சாத்தியமில்லை.\n"
""

#: syntax_errors\message_analyzer.py:481
msgid "The object named `{name}` is defined with type annotation\n"
"as a local variable. It cannot be declared to be a global variable.\n"
""
msgstr "`{name}` என்ற பெயரிடப்பட்ட பொருள், உள்ளூர் மாறியாக வகை சிறுகுறிப்பு \n"
"மூலம் வரையறுக்கப்படுகிறது. இது உலகளாவிய மாறி என்று அறிவிக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:494
msgid "You cannot use the augmented assignment operator `:=`,\n"
"sometimes called the walrus operator, with literals like `{bad_token}`.\n"
"You can only assign objects to identifiers (variable names).\n"
""
msgstr "பெரிதாக்கப்பட்ட ஒதுக்கும் இயக்கியான `:=`, சில சமயங்களில் கடற்குதிரை \n"
"இயக்கி என அழைக்கப்படும், `{bad_token}` போன்ற எழுத்துக்களுடன் நீங்கள் பயன்படுத்த முடியாது. \n"
"அடையாளங்காட்டிகளுக்கு (மாறி பெயர்கள்) மட்டுமே நீங்கள் பொருட்களை ஒதுக்க முடியும்.\n"
""

#: syntax_errors\message_analyzer.py:505
msgid "You declared `{name}` as being both a global and nonlocal variable.\n"
"A variable can be global, or nonlocal, but not both at the same time.\n"
""
msgstr "நீங்கள் `{name}` ஆனது உலகளாவிய மற்றும் உள்ளூர் அல்லாத மாறி என அறிவித்தீர்கள். \n"
"ஒரு மாறி உலகளாவியதாகவோ அல்லது உள்ளூர் அல்லாததாகவோ இருக்கலாம், ஆனால் இரண்டும் ஒரே நேரத்தில் அல்ல.\n"
""

#: syntax_errors\message_analyzer.py:520
msgid "Python tells us that the {bracket} was never closed.\n"
""
msgstr "{bracket} ஒருபோதும் மூடப்படவில்லை என்று பைதான் சொல்கிறது.\n"
""

#: syntax_errors\message_analyzer.py:523
msgid "The {bracket} was never closed.\n"
""
msgstr "{bracket} ஒருபோதும் மூடப்படவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:535
msgid "The Python keyword `break` can only be used inside a `for` loop or inside a `while` loop.\n"
""
msgstr "பைதான் முக்கிய சொல்லான `break` என்பது `for` சுழலில் அல்லது `while` சுழலில் மட்டுமே பயன்படுத்தப்படும்.\n"
""

#: syntax_errors\message_analyzer.py:576
msgid "You cannot delete the constant `{constant}`.\n"
""
msgstr "நீங்கள் நிலையான `{constant}` ஐ நீக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:596 syntax_errors\message_analyzer.py:650
msgid "You cannot delete a Python expression.\n"
""
msgstr "நீங்கள் ஒரு பைதான் வெளிப்பாட்டை நீக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:599
msgid "You cannot delete the expression `{expression}`.\n"
""
msgstr "`{expression}` என்ற வெளிப்பாட்டை நீங்கள் நீக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:616
msgid "You attempted to delete a function call\n"
"\n"
"    {line}\n"
"instead of deleting the function's name\n"
"\n"
"    {correct}\n"
""
msgstr "செயல்பாட்டு அழைப்பை நீக்க முயற்சித்தீர்கள்\n"
"\n"
"     {line}\n"
"செயல்பாட்டின் பெயரை நீக்குவதற்கு பதிலாக\n"
"\n"
"     {correct}\n"
""

#: syntax_errors\message_analyzer.py:634
msgid "You cannot delete the literal `{literal}`.\n"
""
msgstr "நீங்கள் நேரடியான `{literal}` ஐ நீக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:653
msgid "You cannot delete the named expression `{expression}`.\n"
""
msgstr "பெயரிடப்பட்ட வெளிப்பாட்டை நீங்கள் நீக்க முடியாது `{expression}`.\n"
""

#: syntax_errors\message_analyzer.py:669
msgid "The star operator `*` is interpreted to mean that\n"
"iterable unpacking is to be used to assign a name\n"
"to each item of an iterable, which does not make sense here.\n"
""
msgstr "விண்மீன் இயக்கி `*` என்பது, மறுசெய்யக்கூடிய ஒவ்வொரு பொருளுக்கும் \n"
"ஒரு பெயரை ஒதுக்குவதற்கு, மறுசெய்யக்கூடிய கட்டவிழ் பயன்படுத்தப்பட \n"
"வேண்டும் என்று பொருள்படும், இது இங்கே பொருளற்றது.\n"
""

#: syntax_errors\message_analyzer.py:683
msgid "It looks like you surrounded a starred name by parentheses.\n"
"This was not considered a SyntaxError before Python version 3.9.\n"
""
msgstr "அடைப்புக்குறிக்குள் விண்மீன் பெயரைச் சுற்றியிருப்பது போல் தெரிகிறது. \n"
"இது பைதான் பதிப்பு 3.9க்கு முன் தொடரியல் பிழையாகக் கருதப்படவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:702
msgid "Did you forget a colon?\n"
""
msgstr "நீங்கள் ஒரு முக்காற்புள்ளியை மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:703
msgid "Python expected a colon at the position indicated.\n"
""
msgstr "பைதான் சுட்டிக்காட்டப்பட்ட நிலையில் ஒரு முக்காற்புள்ளியை எதிர்பார்த்தது.\n"
""

#: syntax_errors\message_analyzer.py:730
msgid "It looks like the error occurred as you were writing a Python dict.\n"
"Perhaps you wrote a dict key without writing the corresponding value.\n"
""
msgstr "நீங்கள் பைத்தான் அகராதி எழுதும் போது பிழை ஏற்பட்டது போல் தெரிகிறது. \n"
"ஒருவேளை நீங்கள் தொடர்புடைய மதிப்பை எழுதாமல் அகராதி திரவுகோலை எழுதியிருக்கலாம்.\n"
""

#: syntax_errors\message_analyzer.py:734 syntax_errors\message_analyzer.py:897
#: syntax_errors\statement_analyzer.py:1512
msgid "Did you forget to write a dict value?\n"
""
msgstr "அகராதி மதிப்பை எழுத மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:741
msgid "The Python keyword `continue` can only be used inside a `for` loop or inside a `while` loop.\n"
""
msgstr "பைதான் முக்கிய சொல்லான `continue` என்பது `for` சுழலில் அல்லது `while` சுழலில் மட்டுமே பயன்படுத்தப்படும்.\n"
""

#: syntax_errors\message_analyzer.py:794
msgid "Did you forget to add `else`?\n"
""
msgstr "`else` சேர்க்க மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:795
msgid "An `else some_value` clause was expected after the `if` expression.\n"
""
msgstr "`if` வெளிப்பாட்டிற்குப் பிறகு `else சில_மதிப்பு` பிரிவு எதிர்பார்க்கப்பட்டது.\n"
""

#: syntax_errors\message_analyzer.py:807
msgid "You started writing a triple-quoted string but never wrote\n"
"the triple quotes needed to end the string.\n"
""
msgstr "நீங்கள் மூன்று மேற்கோள் சரத்தை எழுதத் தொடங்கியுள்ளீர்கள் ஆனால் சரத்தை \n"
"முடிக்க தேவையான மூன்று மேற்கோள்களை எழுதவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:821
msgid "Did you forget a closing quote?\n"
""
msgstr "இறுதி மேற்கோளை மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:822
msgid "You started writing a string with a single or double quote\n"
"but never ended the string with another quote on that line.\n"
""
msgstr "நீங்கள் ஒற்றை அல்லது இரட்டை மேற்கோளுடன் ஒரு சரத்தை எழுதத் \n"
"தொடங்கியுள்ளீர்கள், ஆனால் அந்த வரியில் மற்றொரு மேற்கோளுடன் சரத்தை முடிக்கவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:829
msgid "Perhaps you meant to write the backslash character, `\\`\n"
"as the last character in the string and forgot that you\n"
"needed to escape it by writing two `\\` in a row.\n"
""
msgstr "ஒருவேளை நீங்கள் பின்சாய்வு எழுத்தை எழுத நினைத்திருக்கலாம், சரத்தின் கடைசி \n"
"எழுத்தாக `\\` மற்றும் ஒரு வரிசையில் இரண்டு `\\` எழுதுவதன் மூலம் அதிலிருந்து \n"
"தப்பிக்க வேண்டும் என்பதை மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:834
msgid "Did you forget to escape a backslash character?\n"
""
msgstr "பின்சாய்வுக் எழுத்திலிருந்து தப்பிக்க மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:893
#: syntax_errors\statement_analyzer.py:1503
msgid "It looks like the error occurred as you were writing a Python dict.\n"
"Perhaps you forgot to write a value after a colon.\n"
""
msgstr "நீங்கள் பைத்தான் அகராதி எழுதும் போது பிழை ஏற்பட்டது போல் தெரிகிறது.\n"
"ஒரு முக்காற்புள்ளிக்குப் பிறகு ஒரு மதிப்பை எழுத மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:906
msgid "You have written an f-string whose content `{...}`\n"
"includes a backslash; this is not allowed.\n"
"Perhaps you can replace the part that contains a backslash by\n"
"some variable. For example, suppose that you have an f-string like:\n"
"\n"
"    f\"{... 'hello\\n' ...}\"\n"
"\n"
"you could write this as\n"
"\n"
"    hello = 'hello\\n'\n"
"    f\"{... hello ...}\"\n"
""
msgstr "நீங்கள் ஒரு f-சரத்தை எழுதியுள்ளீர்கள், அதன் உள்ளடக்கம் `{...}` \n"
"பின்சாய்வு கொண்டதாகும்; இது அனுமதிக்கப்படவில்லை. \n"
"ஒருவேளை நீங்கள் பின்சாய்வு கொண்ட பகுதியை ஏதேனும் மாறி மூலம் மாற்றலாம். \n"
"எடுத்துக்காட்டாக, உங்களிடம் இது போன்ற f-சரம் இருப்பதாக வைத்துக்கொள்வோம்:\n"
"\n"
" f\"{... 'hello\\n' ...}\" \n"
"\n"
"இதை பின்வருமாறு எழுதலாம்\n"
"\n"
"hello = 'hello\\n'\n"
"f\"{... hello ...}\"\n"
""

#: syntax_errors\message_analyzer.py:951
#: syntax_errors\statement_analyzer.py:1128
msgid "I am guessing that you were writing a comprehension or a generator expression\n"
"and forgot to include parentheses around tuples.\n"
"As an example, instead of writing\n"
"\n"
"    [i, i**2 for i in range(10)]\n"
"\n"
"you would need to write\n"
"\n"
"    [(i, i**2) for i in range(10)]\n"
"\n"
""
msgstr "நீங்கள் ஒரு புரிதல் அல்லது உருவாக்கி வெளிப்பாடு எழுதுகிறீர்கள் என்று நினைக்கிறேன், மேலும் மடங்குகளைச் சுற்றி அடைப்புக்குறிகளைச் சேர்க்க மறந்துவிட்டீர்கள். எடுத்துக்காட்டாக,\n"
"\n"
"[ஐ, ஐ**2 for ஐ in range(10)]\n"
"\n"
"எழுதுவதற்குப் பதிலாக, \n"
"\n"
"[(ஐ, ஐ**2) for ஐ in range(10)]\n"
"\n"
"என்று எழுத வேண்டும்\n"
"\n"
""

#: syntax_errors\message_analyzer.py:968
msgid "A `from __future__ import` statement changes the way Python\n"
"interprets the code in a file.\n"
"It must appear at the beginning of the file."
msgstr "ஒரு கோப்பில் உள்ள குறியீட்டை பைதான் விளக்கும் விதத்தை \n"
"`from __future__ import` அறிக்கை மாற்றுகிறது. \n"
"இது கோப்பின் தொடக்கத்தில் தோன்ற வேண்டும்."

#: syntax_errors\message_analyzer.py:984
msgid "The available features are `{names}`.\n"
""
msgstr "கிடைக்கக்கூடிய அம்சங்கள் `{names}`.\n"
""

#: syntax_errors\message_analyzer.py:989
msgid "When using a `from __future__ import` statement,\n"
"you must import specific named features.\n"
""
msgstr "`from __future__ import` அறிக்கையைப் பயன்படுத்தும் போது, குறிப்பிட்ட \n"
"பெயரிடப்பட்ட அம்சங்களை நீங்கள் இறக்குமதி செய்ய வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1000
msgid "Instead of `{feature}`, perhaps you meant to import `{name}`.\n"
""
msgstr "`{feature}` என்பதற்குப் பதிலாக, நீங்கள் `{name}` ஐ இறக்குமதி செய்ய நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\message_analyzer.py:1005
msgid "`{feature}` is not a valid feature of module `__future__`.\n"
""
msgstr "`{feature}` என்பது `__future__` தொகுதியின் சரியான அம்சம் அல்ல.\n"
""

#: syntax_errors\message_analyzer.py:1030
msgid "You are using a generator expression, something of the form\n"
"\n"
"    x for x in thing\n"
"\n"
"You must add parentheses enclosing that expression.\n"
""
msgstr "நீங்கள் உருவாக்கி வெளிப்பாட்டை, பின்வரும் வடிவத்தில் உள்ள ஏதாவது ஒன்றை பயன்படுத்துகிறீர்கள்\n"
"\n"
"    ஐ for ஐ in பொருள்\n"
"\n"
"நீங்கள் அந்த வெளிப்பாட்டுடன் அடைப்புக்குறிக்குள் சேர்க்க வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1043
msgid "I suspect you wrote `from __future__ import braces` following\n"
"someone else's suggestion. This will never work.\n"
"\n"
"Unlike other programming languages, Python's code block are defined by\n"
"their indentation level, and not by using some curly braces, like `{...}`.\n"
""
msgstr "வேறொருவரின் ஆலோசனையைப் பின்பற்றி நீங்கள் `from __future__ import braces` என்று எழுதியிருக்கிறீர்கள் என்று சந்தேகிக்கிறேன். இது ஒருபோதும் வேலை செய்யாது. \n"
"\n"
"பிற நிரலாக்க மொழிகளைப் போலல்லாமல், பைத்தானின் குறியீட்டுத் தொகுதி \n"
"அவற்றின் உள்தள்ளல் மட்டத்தால் வரையறுக்கப்படுகிறது, மேலும் `{...}` போன்ற சில \n"
"சுருள் அடைப்புக்குறிகளைப் பயன்படுத்தி அல்ல.\n"
""

#: syntax_errors\message_analyzer.py:1058
#: syntax_errors\statement_analyzer.py:164
msgid "Did you use copy-paste?\n"
""
msgstr "நீங்கள் நகல்-ஒட்டு பயன்படுத்தினீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:1059
msgid "Python indicates that you used the unicode character `{bad_character}`\n"
"which is not allowed.\n"
""
msgstr "அனுமதியில்லாத `{bad_character}` என்ற ஒருங்குறி எழுத்தைப் \n"
"பயன்படுத்தியுள்ளீர்கள் என்பதை பைதான் குறிக்கிறது.\n"
""

#: syntax_errors\message_analyzer.py:1087
msgid "Python tells us that you have written an invalid number."
msgstr "நீங்கள் தவறான எண்ணை எழுதியுள்ளீர்கள் என்று பைதான் எங்களிடம் கூறுகிறது."

#: syntax_errors\message_analyzer.py:1088
msgid "However, I think that the problem might be the following."
msgstr "இருப்பினும், சிக்கல் பின்வருவனவாக இருக்கலாம் என்று நான் நினைக்கிறேன்."

#: syntax_errors\message_analyzer.py:1124
msgid "I have no suggestion to offer to fix this problem.\n"
""
msgstr "இந்தச் சிக்கலைச் சரிசெய்வதற்கு என்னிடம் எந்த ஆலோசனையும் இல்லை.\n"
""

#: syntax_errors\message_analyzer.py:1136
#: syntax_errors\statement_analyzer.py:655
msgid "The double star operator `**` is likely interpreted to mean that\n"
"dict unpacking is to be used which is not allowed or does not make sense here.\n"
""
msgstr "இரட்டை விண்மீன் இயக்கி `**` என்பது அகராதி கட்டவிழ் பயன்படுத்தப்பட வேண்டும் \n"
"என்று பொருள்படலாம், இது இங்கே அனுமதிக்கப்படாத அல்லது பொருளற்றது.\n"
""

#: syntax_errors\message_analyzer.py:1227
msgid "You have called a function repeating the same keyword argument (`{arg}`).\n"
"Each keyword argument should appear only once in a function call.\n"
""
msgstr "அதே முக்கியச்சொல் வாதத்தை (`{arg}`) திரும்பத் திரும்பச் செய்யும் செயல்பாட்டை \n"
"நீங்கள் அழைத்தீர்கள். ஒவ்வொரு முக்கியச்சொல் வாதமும் ஒரு செயல்பாட்டு அழைப்பில் ஒரு முறை மட்டுமே தோன்றும்.\n"
""

#: syntax_errors\message_analyzer.py:1292
msgid "Python tells us that the closing `{closing}` on the last line shown\n"
"does not match the opening `{opening}` on line {lineno}.\n"
"\n"
""
msgstr "கடைசியாகக் காட்டப்பட்டுள்ள வரியில் உள்ள மூடும் `{closing}`, வரி {lineno} இல் \n"
"திறக்கும் `{opening}` உடன் பொருந்தவில்லை என்று பைதான் நமக்குச் சொல்கிறது.\n"
"\n"
""

#: syntax_errors\message_analyzer.py:1297
msgid "Python tells us that the closing `{closing}` on the last line shown\n"
"does not match the opening `{opening}`.\n"
"\n"
""
msgstr "கடைசியாகக் காட்டப்பட்டுள்ள வரியில் உள்ள மூடும் `{closing}` திறப்பு `{opening}` \n"
"உடன் பொருந்தவில்லை என்று பைதான் சொல்கிறது.\n"
"\n"
""

#: syntax_errors\message_analyzer.py:1311
msgid "Did you forget something after `*`?\n"
""
msgstr "`*` பிறகு எதையாவது மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:1312
msgid "Assuming you were defining a function, you need\n"
"to replace `*` by either `*arguments` or\n"
"by `*, named_argument=value`.\n"
""
msgstr "நீங்கள் ஒரு செயல்பாட்டை வரையறுக்கிறீர்கள் என்று வைத்துக் கொண்டால், \n"
"நீங்கள் `*` ஐ `*வாதங்கள்` அல்லது `*, name_argument=value` மூலம் மாற்ற \n"
"வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1327
msgid "You assigned a value to the variable `{name}`\n"
"before declaring it as a global variable.\n"
""
msgstr "உலகளாவிய மாறியாக அறிவிக்கும் முன், `{name}` மாறிக்கு மதிப்பை \n"
"ஒதுக்கியுள்ளீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:1341
msgid "Did you forget to add `nonlocal`?\n"
""
msgstr "`nonlocal` சேர்க்க மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:1342
msgid "You assigned a value to the variable `{name}`\n"
"before declaring it as a nonlocal variable.\n"
""
msgstr "நீங்கள் `{name}` மாறிக்கு ஒரு மதிப்பை ஒதுக்கியுள்ளீர்கள், \n"
"அதை உள்ளூர் அல்லாத மாறியாக அறிவிக்கும் முன்.\n"
""

#: syntax_errors\message_analyzer.py:1362
msgid "You are including the statement\n"
"\n"
"    {newline}\n"
"\n"
"indicating that `{name}` is a variable defined outside a function.\n"
"You are also using the same `{name}` as an argument for that\n"
"function, thus indicating that it should be variable known only\n"
"inside that function, which is the contrary of what `global` implied.\n"
""
msgstr "`{name}` என்பது ஒரு செயல்பாட்டிற்கு வெளியே வரையறுக்கப்பட்ட மாறி என்பதைக் குறிக்கும் \n"
"\n"
"    {newline} \n"
"\n"
"அறிக்கையைச் சேர்த்துள்ளீர்கள். \n"
"அந்தச் செயல்பாட்டிற்கான வாதமாக அதே `{name}` ஐப் பயன்படுத்துகிறீர்கள், \n"
"இதனால் அது அந்தச் செயல்பாட்டிற்குள் மட்டுமே அறியப்படும் மாறியாக இருக்க \n"
"வேண்டும் என்பதைக் குறிக்கிறது, இது `global` என்பதற்கு முரணானது.\n"
""

#: syntax_errors\message_analyzer.py:1379
msgid "You used `{name}` as a parameter for a function\n"
"before declaring it also as a nonlocal variable:\n"
"`{name}` cannot be both at the same time.\n"
""
msgstr "ஒரு செயல்பாட்டிற்கான அளவுருவாக `{name}` ஐப் பயன்படுத்தியுள்ளீர்கள், அதை \n"
"உள்ளூர்அல்லாத மாறியாகவும் அறிவிக்கும் முன்: \n"
"`{name}` இரண்டும் ஒரே நேரத்தில் இருக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:1394
msgid "You used the variable `{name}`\n"
"before declaring it as a global variable.\n"
""
msgstr "உலகளாவிய மாறியாக அறிவிக்கும் முன் \n"
"`{name}` மாறியைப் பயன்படுத்தியுள்ளீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:1406
msgid "Did you forget to write `nonlocal` first?\n"
""
msgstr "முதலில் `nonlocal` என்று எழுத மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:1408
msgid "You used the variable `{name}`\n"
"before declaring it as a nonlocal variable.\n"
""
msgstr "நீங்கள் `{name}` என்ற மாறியைப் பயன்படுத்தியுள்ளீர்கள், \n"
"அதை உள்ளூர் அல்லாத மாறியாக அறிவிக்கும் முன்.\n"
""

#: syntax_errors\message_analyzer.py:1421
msgid "You declared the variable `{name}` as being a\n"
"nonlocal variable but it cannot be found.\n"
""
msgstr "நீங்கள் `{name}` மாறியை உள்ளூர் அல்லாத மாறி என \n"
"அறிவித்தீர்கள் ஆனால் அதைக் கண்டுபிடிக்க முடியவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:1432
msgid "You used the nonlocal keyword at a module level.\n"
"The nonlocal keyword refers to a variable inside a function\n"
"given a value outside that function."
msgstr "நீங்கள் தொகுதி அளவில் nonlocal முக்கிய சொல்லைப் பயன்படுத்தியுள்ளீர்கள். \n"
"nonlocal முக்கிய சொல் என்பது அந்தச் செயல்பாட்டிற்கு வெளியே ஒரு மதிப்பைக் \n"
"கொடுக்கப்பட்ட ஒரு செயல்பாட்டிற்குள் இருக்கும் மாறியைக் குறிக்கிறது."

#: syntax_errors\message_analyzer.py:1444
msgid "In Python, you can define functions with only positional arguments\n"
"\n"
"    def test(a, b, c): ...\n"
"\n"
"or only keyword arguments\n"
"\n"
"    def test(a=1, b=2, c=3): ...\n"
"\n"
"or a combination of the two\n"
"\n"
"    def test(a, b, c=3): ...\n"
"\n"
"but with the keyword arguments appearing after all the positional ones.\n"
"According to Python, you used positional arguments after keyword ones.\n"
""
msgstr "பைத்தானில், நீங்கள் பின்வருமாறு செயல்பாடுகளை வரையறுக்க முடியும், நிலை வாதங்கள் மட்டுமே கொண்டது\n"
"\n"
"   def test(a, b, c): ...\n"
"\n"
"அல்லது முக்கியச்சொல் வாதங்கள் மட்டும் கொண்டது \n"
"\n"
"   def test(a=1, b=2, c=3): ... \n"
"\n"
"அல்லது இந்த இரண்டின் ஒரு கலவையுடன் கொண்டது\n"
"\n"
"   def test(a, b, c=3): ... \n"
"\n"
"ஆனால் அனைத்து நிலைவாதங்களுக்குப் பிறகு தோன்றும் முக்கியச்சொல் வாதங்களுடன். \n"
"பைத்தானின் கூற்றுப்படி, நீங்கள் முக்கியச்சொல் வாதங்களுக்குப் பிறகு நிலை வாதங்களைப் பயன்படுத்துகிறீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:1464
#: syntax_errors\statement_analyzer.py:1176
msgid "I am guessing that you wanted to use an `except` statement\n"
"with multiple exception types. If that is the case, you must\n"
"surround them with parentheses.\n"
""
msgstr "நீங்கள் பல விதிவிலக்கு வகைகளைக் கொண்ட `except` அறிக்கையைப் \n"
"பயன்படுத்த விரும்புகிறீர்கள் என்று நினைக்கிறேன். அப்படியானால், \n"
"அடைப்புக்குறிக்குள் அவற்றைச் சுற்றி வர வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1476
msgid "In Python, you can call functions with only positional arguments\n"
"\n"
"    test(1, 2, 3)\n"
"\n"
"or only keyword arguments\n"
"\n"
"    test(a=1, b=2, c=3)\n"
"\n"
"or a combination of the two\n"
"\n"
"    test(1, 2, c=3)\n"
"\n"
"but with the keyword arguments appearing after all the positional ones.\n"
"According to Python, you used positional arguments after keyword ones.\n"
""
msgstr "பைத்தானில், நீங்கள் பின்வருமாறு செயல்பாடுகளை அழைக்க முடியும், நிலை வாதங்கள் மட்டுமே கொண்டது\n"
"\n"
"    test(1, 2, 3)\n"
"\n"
"அல்லது முக்கியச்சொல் வாதங்கள் மட்டும் கொண்டது \n"
"\n"
"    test(a=1, b=2, c=3) \n"
"\n"
"அல்லது இந்த இரண்டின் ஒரு கலவையுடன் கொண்டது \n"
"\n"
"    test(1, 2, c=3) \n"
"\n"
"ஆனால் அனைத்து நிலைவாதங்களுக்குப் பிறகு தோன்றும் முக்கியச்சொல் வாதங்களுடன்.  \n"
"பைத்தானின் கூற்றுப்படி, நீங்கள் முக்கியச்சொல் வாதங்களுக்குப் பிறகு நிலை வாதங்களைப் பயன்படுத்துகிறீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:1507
msgid "Perhaps you need to type\n"
"\n"
"     print({message})\n"
"\n"
"In older version of Python, `print` was a keyword.\n"
"Now, `print` is a function; you need to use parentheses to call it.\n"
""
msgstr "நீங்கள் பின்வருமாறு தட்டச்சு செய்ய வேண்டியிருக்கலாம்\n"
"\n"
"print({message}) \n"
"\n"
"பைத்தானின் பழைய பதிப்பில் `print` என்பது ஒரு முக்கிய சொல்லாகும். \n"
"இப்போது, `print` என்பது ஒரு செயல்பாடு; அதை அழைக்க நீங்கள் அடைப்புக்குறிகளைப் பயன்படுத்த வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1514
#: syntax_errors\statement_analyzer.py:587
msgid "Note that arguments of `print` must be separated by commas.\n"
""
msgstr "`print` வாதங்கள் காற்புள்ளிகளால் பிரிக்கப்பட வேண்டும் என்பதை நினைவில் கொள்ளவும்.\n"
""

#: syntax_errors\message_analyzer.py:1515
msgid "Did you mean `print({message})`?\n"
""
msgstr "நீங்கள் `print({message})` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: syntax_errors\message_analyzer.py:1524
msgid "You can only use a `return` statement inside a function or method.\n"
""
msgstr "ஒரு செயல்பாடு அல்லது முறைக்குள் மட்டுமே நீங்கள் `return` அறிக்கையைப் பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\message_analyzer.py:1533
msgid "A star assignment must be of the form:\n"
"\n"
"    ... *name = list_or_tuple\n"
"\n"
""
msgstr "ஒரு விண்மீன் ஒதுக்கீடு இந்த வடிவத்தில் இருக்க வேண்டும்: \n"
"\n"
"   ... *பெயர் = பட்டியல்_அல்லது_மடங்கு\n"
"\n"
""

#: syntax_errors\message_analyzer.py:1564
msgid "Your code is too complex for Python:\n"
"you need to reduce the number of indented code blocks\n"
"contained inside other code blocks.\n"
""
msgstr "உங்கள் குறியீடு பைத்தானுக்கு மிகவும் சிக்கலானது: \n"
"பிற குறியீடு தொகுதிகளுக்குள் உள்ள உள்தள்ளப்பட்ட \n"
"குறியீடு தொகுதிகளின் எண்ணிக்கையை நீங்கள் குறைக்க வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1577
msgid "Your code is too complex for Python:\n"
"you need to reduce the number of parentheses\n"
"contained inside other parentheses.\n"
""
msgstr "உங்கள் குறியீடு பைத்தானுக்கு மிகவும் சிக்கலானது: \n"
"பிற அடைப்புக்குறிக்குள் உள்ள அடைப்புக்குறிகளின் \n"
"எண்ணிக்கையை நீங்கள் குறைக்க வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1592
msgid "Python indicates that you need to surround an expression\n"
"ending with a comma by parentheses.\n"
""
msgstr "அடைப்புக்குறிக்குள் காற்புள்ளியுடன் முடிவடையும் வெளிப்பாட்டைச் சுற்றி வர \n"
"வேண்டும் என்பதை பைதான் குறிக்கிறது.\n"
""

#: syntax_errors\message_analyzer.py:1596
msgid "Perhaps you meant to write\n"
"\n"
"`{new_statement}`\n"
""
msgstr "ஒருவேளை நீங்கள் \n"
"`{new_statement}` \n"
"என்று எழுத நினைத்திருக்கலாம்\n"
""

#: syntax_errors\message_analyzer.py:1604
msgid "However, I suspect that you wrote the keyword `{boolean}` by mistake.\n"
""
msgstr "இருப்பினும், `{boolean}` என்ற முக்கிய சொல்லை நீங்கள் தவறுதலாக எழுதிவிட்டீர்கள் என்று சந்தேகிக்கிறேன்.\n"
""

#: syntax_errors\message_analyzer.py:1608
msgid "The Python keyword `{boolean}` can only be used for boolean expressions.\n"
""
msgstr "பைதான் முக்கியச்சொல் `{boolean}` பூலியன் வெளிப்பாடுகளுக்கு மட்டுமே பயன்படுத்தப்படும்.\n"
""

#: syntax_errors\message_analyzer.py:1620
#: syntax_errors\message_analyzer.py:1633
msgid "However, if you remove the last comma, there will be no syntax error.\n"
""
msgstr "இருப்பினும், கடைசி காற்புள்ளியை நீக்கினால், தொடரியல் பிழை இருக்காது.\n"
""

#: syntax_errors\message_analyzer.py:1640
msgid "I have no additional suggestion to offer.\n"
"Please feel free to report this case.\n"
""
msgstr "நான் வழங்குவதற்கு கூடுதல் பரிந்துரை எதுவும் இல்லை. \n"
"இந்த வழக்கை தயங்காமல் புகாரளிக்கவும்.\n"
""

#: syntax_errors\message_analyzer.py:1653
msgid "You are using the continuation character `\\` outside of a string,\n"
"and it is followed by some other character(s).\n"
""
msgstr "நீங்கள் ஒரு சரத்திற்கு வெளியே `\\` என்ற தொடர்ச்சி எழுத்தைப் \n"
"பயன்படுத்துகிறீர்கள், அதைத் தொடர்ந்து வேறு சில எழுத்து(கள்) வருகின்றன.\n"
""

#: syntax_errors\message_analyzer.py:1676
msgid "I am guessing that you wanted to divide by the number {number} \n"
"and wrote \\ instead of /."
msgstr "நீங்கள் எண்ணை {number} ஆல் வகுக்க விரும்பி, / என்பதற்குப் பதிலாக \\ \n"
"என்று எழுதியிருக்கிறீர்கள் என்று நினைக்கிறேன்."

#: syntax_errors\message_analyzer.py:1680
msgid "Did you mean to divide by {number}?\n"
""
msgstr "{number} வகுக்க வேண்டுமா?\n"
""

#: syntax_errors\message_analyzer.py:1683
msgid "I am guessing that you forgot to enclose some content in a string.\n"
""
msgstr "ஒரு சரத்தில் சில உள்ளடக்கத்தை இணைக்க மறந்துவிட்டீர்கள் என்று நினைக்கிறேன்.\n"
""

#: syntax_errors\message_analyzer.py:1692
msgid "Python tells us that it reached the end of the file\n"
"and expected more content.\n"
"\n"
""
msgstr "பைதான் கோப்பின் முடிவை அடைந்து மேலும் உள்ளடக்கத்தை எதிர்பார்க்கிறது \n"
"என்று கூறுகிறது.\n"
"\n"
""

#: syntax_errors\message_analyzer.py:1699
msgid "I will attempt to be give a bit more information.\n"
"\n"
""
msgstr "நான் இன்னும் கொஞ்சம் தகவல் கொடுக்க முயற்சிப்பேன்.\n"
"\n"
""

#: syntax_errors\message_analyzer.py:1710
msgid "I suspect that you wrote a string that contains\n"
"one backslash character, `\\` followed by an uppercase `U`\n"
"and some more characters.\n"
"Python likely interpreted this as indicating the beginning of\n"
"what is known as an escape sequence for special unicode characters.\n"
"To solve the problem, either write a so-called 'raw string'\n"
"by adding the letter `r` as a prefix in\n"
"front of the string, or replace `\\U`, by `\\\\U`.\n"
""
msgstr "ஒரு பின்சாய்வு எழுத்து, `\\` அதைத் தொடர்ந்து பெரிய எழுத்து `U` மற்றும் இன்னும் \n"
"சில எழுத்துகளைக் கொண்ட சரத்தை நீங்கள் எழுதியிருக்கிறீர்கள் என்று நான் \n"
"சந்தேகிக்கிறேன். \n"
"சிறப்பு ஒருங்குறி எழுத்துகளுக்கான விடுபடு தொடர் என அழைக்கப்படும் \n"
"தொடக்கத்தை பைதான் இது குறிக்கிறது. \n"
"சிக்கலைத் தீர்க்க, சரத்தின் முன் முன்னொட்டாக `r` என்ற எழுத்தைச் சேர்ப்பதன் \n"
"மூலம் 'மூல சரம்' என்று அழைக்கப்படுவதை எழுதவும் அல்லது `\\U` ஐ `\\\\U` ஆல் \n"
"மாற்றவும்.\n"
""

#: syntax_errors\message_analyzer.py:1734
#: syntax_errors\statement_analyzer.py:108
msgid "The closing {bracket} on line {linenumber} does not match anything.\n"
""
msgstr "வரி {linenumber} இல் மூடும் {bracket} எதனுடனும் பொருந்தவில்லை.\n"
""

#: syntax_errors\message_analyzer.py:1745
msgid "Perhaps you forgot a closing quote.\n"
""
msgstr "ஒருவேளை நீங்கள் ஒரு இறுதி மேற்கோளை மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:1762
msgid "Inside the f-string `{fstring}`, \n"
"you have another string, which starts with either a\n"
"single quote (') or double quote (\"), without a matching closing one.\n"
""
msgstr "f-சரம் `{fstring}` இன் உள்ளே, உங்களிடம் மற்றொரு சரம் உள்ளது, \n"
"இது ஒரு மேற்கோளுடன் (') அல்லது இரட்டை மேற்கோளில் (\") தொடங்கும்\n"
"ஒரு பொருத்தும் மூடுதல் இல்லாமல்.\n"
""

#: syntax_errors\message_analyzer.py:1775
msgid "You can only use a `yield` statement inside a function.\n"
""
msgstr "ஒரு செயல்பாட்டிற்குள் மட்டுமே நீங்கள் `yield` அறிக்கையை பயன்படுத்த முடியும்.\n"
""

#: syntax_errors\message_analyzer.py:1784
msgid "This is a message that was added in Python 3.9\n"
"to prevent redefining `__peg_parser__`.\n"
"It should not be present in other versions.\n"
""
msgstr "இது `__peg_parser__` என்பதை மறுவரையறை செய்வதைத் தடுக்க \n"
"பைதான் 3.9 இல் சேர்க்கப்பட்ட செய்தி. \n"
"இது மற்ற பதிப்புகளில் இருக்கக்கூடாது.\n"
""

#: syntax_errors\statement_analyzer.py:143
msgid "The closing {bracket} on line {close_lineno} does not match the opening {open_bracket} on line {open_lineno}.\n"
""
msgstr "{close_lineno} வரியில் உள்ள மூடும் {bracket}, {open_lineno} வரியில் திறக்கும் {open_bracket} உடன் பொருந்தவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:170
msgid "It looks like you copy-pasted code from an interactive interpreter.\n"
"The Python prompt, `>>>`, should not be included in your code.\n"
""
msgstr "ஊடாடும் மொழிபெயர்ப்பாளரிடமிருந்து நீங்கள் குறியீட்டை நகலெடுத்து ஒட்டியது போல் தெரிகிறது. \n"
"பைதான் உடனுக்குடன், `>>>`, உங்கள் குறியீட்டில் சேர்க்கப்படக்கூடாது.\n"
""

#: syntax_errors\statement_analyzer.py:179
msgid "It looks like you copy-pasted code from an interactive interpreter.\n"
"The Python prompt, `...`, should not be included in your code.\n"
""
msgstr "ஊடாடும் மொழிபெயர்ப்பாளரிடமிருந்து நீங்கள் குறியீட்டை நகலெடுத்து ஒட்டியது போல் தெரிகிறது. \n"
"பைதான் உடனுக்குடன், `...`, உங்கள் குறியீட்டில் சேர்க்கப்படக்கூடாது.\n"
""

#: syntax_errors\statement_analyzer.py:193
msgid "You should not use the backquote character.\n"
""
msgstr "பின்மேற்கோள் எழுத்தை நீங்கள் பயன்படுத்தக்கூடாது.\n"
""

#: syntax_errors\statement_analyzer.py:194
msgid "You are using the backquote character.\n"
"Either you meant to write a single quote, ', or copied Python 2 code;\n"
"in this latter case, use the function `repr(x)`."
msgstr "நீங்கள் பின்மேற்கோள் எழுத்தைப் பயன்படுத்துகிறீர்கள். \n"
"நீங்கள் ஒற்றை மேற்கோளை எழுத வேண்டும், ', அல்லது பைதான் 2 குறியீட்டை நகலெடுத்திருக்க வேண்டும்; \n"
"இந்த பிந்தைய வழக்கில், `repr(x)` செயல்பாட்டைப் பயன்படுத்தவும்."

#: syntax_errors\statement_analyzer.py:215
msgid "You forgot to add a condition.\n"
""
msgstr "நிபந்தனையைச் சேர்க்க மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:217
msgid "An `if` statement requires a condition:\n"
"\n"
"    if condition:\n"
"        ...\n"
"\n"
""
msgstr "`if` அறிக்கைக்கு ஒரு நிபந்தனை தேவை: \n"
"\n"
"   if நிபந்தனை:\n"
"        ...\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:223
msgid "A `while` loop requires a condition:\n"
"\n"
"    while condition:\n"
"        ...\n"
"\n"
""
msgstr "ஒரு `while` சுழலுக்கு ஒரு நிபந்தனை தேவை:\n"
"\n"
"    while நிபந்தனை:\n"
"        ...\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:229
msgid "A `for` loop requires at least 3 more terms.\n"
""
msgstr "ஒரு `for` சுழலூக்கு குறைந்தது 3 விதிமுறைகள் தேவை.\n"
""

#: syntax_errors\statement_analyzer.py:230
msgid "A `for` loop is an iteration over a sequence:\n"
"\n"
"    for element in sequence:\n"
"        ...\n"
"\n"
""
msgstr "ஒரு `for` சுழல் என்பது ஒரு வரிசையின் மீள் மறு செய்கை: \n"
"\n"
"    for உறுப்பு in வரிசை: \n"
"        ...\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:236
msgid "A class needs a name.\n"
""
msgstr "ஒரு வகுப்பிற்கு ஒரு பெயர் தேவை.\n"
""

#: syntax_errors\statement_analyzer.py:237
msgid "A `class` statement requires a name:\n"
"\n"
"    class SomeName:\n"
"        ...\n"
"\n"
""
msgstr "ஒரு `வகுப்பு` அறிக்கைக்கு ஒரு பெயர் தேவை: \n"
"\n"
"   class வகுப்புப்பெயர்:\n"
"        ...\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:254
msgid "You cannot use the Python keyword `{word}` as an attribute.\n"
"\n"
""
msgstr "நீங்கள் பைதான் முக்கிய சொல்லான `{word}` ஐ பண்புக்கூறாகப் பயன்படுத்த முடியாது.\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:260
msgid "`{word}` cannot be used as an attribute.\n"
""
msgstr "`{word}` ஐ பண்புக்கூறாகப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:273
msgid "Perhaps you meant to write `elif`.\n"
""
msgstr "ஒருவேளை நீங்கள் 'elif' என்று எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:274
msgid "You likely meant to use Python's `elif` keyword\n"
"but wrote `{name}` instead.\n"
"\n"
""
msgstr "நீங்கள் பைத்தானின் `elif` முக்கிய சொல்லைப் பயன்படுத்த நினைத்திருக்கலாம், \n"
"ஆனால் அதற்குப் பதிலாக `{name}` என்று எழுதியிருக்கலாம்.\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:291
msgid "Did you mean `from {module} import {function}`?\n"
""
msgstr "`from {module} import {function}` என்று நீங்கள் சொன்னீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:294
msgid "You wrote something like\n"
"\n"
"    import {function} from {module}\n"
"instead of\n"
"\n"
"    from {module} import {function}\n"
"\n"
"\n"
""
msgstr "பின்வருமாறு ஒன்றை எழுதியுள்ளீர்கள்\n"
"\n"
"    import {function} from {module} \n"
"பின்வருவதற்குப் பதிலாக \n"
"\n"
"    from {module} import {function}\n"
"\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:317
msgid "Perhaps you misplaced a quote.\n"
""
msgstr "ஒருவேளை நீங்கள் ஒரு மேற்கோளை தவறாகப் பயன்படுத்தியிருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:318
msgid "There appears to be a Python identifier (variable name)\n"
"immediately following a string.\n"
"I suspect that you were trying to use a quote inside a string\n"
"that was enclosed in quotes of the same kind.\n"
""
msgstr "ஒரு சரத்தைத் தொடர்ந்து உடனடியாக பைதான் அடையாளங்காட்டி (மாறி பெயர்) \n"
"இருப்பதாகத் தோன்றுகிறது. \n"
"அதே வகையான மேற்கோள்களில் இணைக்கப்பட்ட ஒரு சரத்திற்குள் நீங்கள் \n"
"மேற்கோளைப் பயன்படுத்த முயற்சிக்கிறீர்கள் என்று நான் சந்தேகிக்கிறேன்.\n"
""

#: syntax_errors\statement_analyzer.py:349
msgid "The augmented assignment operator is not allowed in Python version {version}.\n"
""
msgstr "பைதான் பதிப்பில் {version} விரிவாக்கப்பட்ட ஒதுக்கல் இயக்கி அனுமதிக்கப்படவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:352
msgid "You appear to be using the operator `:=`, sometimes called\n"
"the walrus operator. This operator requires the use of\n"
"Python 3.8 or newer. You are using version {version}.\n"
""
msgstr "நீங்கள் `:=` இயக்கியைப் பயன்படுத்துகிறீர்கள், சில சமயங்களில் கடற்குதிரை \n"
"இயக்கி என்று அழைக்கப்படுகிறது. இந்த இயக்கிக்கு Python 3.8 அல்லது \n"
"புதியது தேவை. நீங்கள் பதிப்பு {version} ஐப் பயன்படுத்துகிறீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:390
msgid "Did you write operators in an incorrect order?\n"
""
msgstr "இயக்கிகளை தவறான வரிசையில் எழுதினீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:391
msgid "It looks like you wrote two operators (`{first}` and `{second}`)\n"
"in the wrong order: `{wrong}` instead of `{correct}`.\n"
""
msgstr "நீங்கள் இரண்டு இயக்கிகளை (`{first}` மற்றும் `{second}`) தவறான \n"
"வரிசையில் எழுதியது போல் தெரிகிறது: `{correct}` என்பதற்குப் பதிலாக `{wrong}`.\n"
""

#: syntax_errors\statement_analyzer.py:422
msgid "You wrote three equal signs in a row which is allowed in some\n"
"programming languages, but not in Python. To check if two objects\n"
"are equal, use two equal signs, `==`; to see if two names represent\n"
"the exact same object, use the operator `is`.\n"
""
msgstr "நீங்கள் ஒரு வரிசையில் மூன்று சமமான அடையாளங்களை எழுதியுள்ளீர்கள், \n"
"இது சில நிரலாக்க மொழிகளில் அனுமதிக்கப்படுகிறது, ஆனால் பைத்தானில் \n"
"இல்லை. இரண்டு பொருள்கள் சமமாக உள்ளதா என்பதைச் சரிபார்க்க, இரண்டு சம அடையாளங்களைப் பயன்படுத்தவும், `==`; இரண்டு பெயர்கள் ஒரே பொருளைக் \n"
"குறிக்கின்றனவா என்பதைப் பார்க்க, `is` இயக்கியைப் பயன்படுத்தவும்.\n"
""

#: syntax_errors\statement_analyzer.py:428
msgid "Did you mean to use `is` instead of `===`?\n"
""
msgstr "`===` என்பதற்குப் பதிலாக `is` ஐப் பயன்படுத்த விரும்புகிறீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:432
msgid "You cannot have write the same operator, `{op}`, twice in a row.\n"
"Perhaps you wrote one of them by mistake\n"
"or forgot to write something between them.\n"
""
msgstr "நீங்கள் ஒரே இயக்கியை, `{op}`, ஒரு வரிசையில் இரண்டு முறை எழுத முடியாது. \n"
"ஒருவேளை நீங்கள் அவற்றில் ஒன்றை தவறுதலாக எழுதியிருக்கலாம் \n"
"அல்லது அவற்றுக்கிடையே ஏதாவது எழுத மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:443
msgid "You cannot have these two operators, `{first}` and `{second}`,\n"
"following each other.\n"
"It looks like you tried to use a starred expression as a dict value;\n"
"this is not allowed.\n"
""
msgstr "நீங்கள் இந்த இரண்டு இயக்கிகள், `{first}` மற்றும் `{second}`, ஒருவரையொருவர் பின்பற்ற முடியாது. \n"
"நீங்கள் விண்மீனிடப்பட்ட வெளிப்பாட்டை அகராதி மதிப்பாகப் பயன்படுத்த முயற்சித்தது போல் தெரிகிறது; \n"
"\n"
"இது அனுமதிக்கப்படவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:457
msgid "You cannot have these two operators, `{first}` and `{second}`,\n"
"following each other. Perhaps you wrote one of them by mistake\n"
"or forgot to write something between them.\n"
""
msgstr "நீங்கள் இந்த இரண்டு இயக்கிகள், `{first}` மற்றும் `{second}`, ஒருவரையொருவர் \n"
"பின்பற்ற முடியாது. ஒருவேளை நீங்கள் அவற்றில் ஒன்றை தவறுதலாக \n"
"எழுதியிருக்கலாம் அல்லது அவற்றுக்கிடையே ஏதாவது எழுத மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:464
msgid "Or perhaps you included a space by mistake between the two operators\n"
"and meant to write `{oper}` as a single operator.\n"
""
msgstr "அல்லது இரண்டு இயக்கிகளுக்கு இடையே தவறுதலாக இடைவெளியைச் சேர்த்துவிட்டு, \n"
"`{oper}` என்பதை ஒற்றை ஆபரேட்டராக எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:492
msgid "Did you mean to use `=`?\n"
""
msgstr "`=` ஐப் பயன்படுத்த விரும்புகிறீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:493
msgid "You use the augmented assignment operator `:=` where\n"
"the normal assignment operator `=` was required.\n"
""
msgstr "சாதாரண ஒதுக்கல் இயக்கி `=` தேவைப்படும் இடத்தில் `:=` அதிகரிக்கப்பட்ட \n"
"ஒதுக்கல் இயக்கியைப் பயன்படுத்துகிறீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:548
#: syntax_errors\statement_analyzer.py:524
msgid "You likely used an assignment operator `=` instead of an equality operator `==`.\n"
""
msgstr "சமத்துவ இயக்கிக்குப் பதிலாக `=` ஒதுக்கீட்டு இயக்கிகளைப் பயன்படுத்தியிருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:539
msgid "Perhaps you needed `==` or `:=` instead of `=`.\n"
""
msgstr "ஒருவேளை உங்களுக்கு `=` என்பதற்குப் பதிலாக `==` அல்லது `:=` தேவைப்படலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:540
msgid "You used an assignment operator `=`; perhaps you meant to use \n"
"an equality operator, `==`, or the walrus operator `:=`.\n"
""
msgstr "நீங்கள் ஒரு ஒதுக்கல் இயக்கியைப் பயன்படுத்தியுள்ளீர்கள் `=`; ஒருவேளை நீங்கள் \n"
"சமத்துவ இயக்கி, `==` அல்லது கடற்குதிரை இயக்கி `:=` ஐப் பயன்படுத்த நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:562
msgid "In older version of Python, `print` was a keyword.\n"
"Now, `print` is a function; you need to use parentheses to call it.\n"
""
msgstr "பைத்தானின் பழைய பதிப்பில், `print` என்பது ஒரு முக்கிய சொல்லாகும். \n"
"இப்போது, `print` என்பது ஒரு செயல்பாடு; அதை அழைக்க நீங்கள் அடைப்புக்குறிகளைப் பயன்படுத்த வேண்டும்.\n"
""

#: syntax_errors\statement_analyzer.py:585
msgid "Did you mean `{new_line}`?\n"
""
msgstr "`{new_line}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:603
msgid "It looks as if you are attempting to use pip to install a module.\n"
"`pip` is a command that needs to run in a terminal,\n"
"not from a Python interpreter.\n"
""
msgstr "நீங்கள் ஒரு தொகுதியை நிறுவ பிப்பைப் பயன்படுத்த முயற்சிப்பது போல் தெரிகிறது. \n"
"`pip` என்பது முனையத்தில் இயங்க வேண்டிய கட்டளை, \n"
"பைதான் மொழிபெயர்ப்பாளரிடமிருந்து அல்ல.\n"
""

#: syntax_errors\statement_analyzer.py:611
msgid "Pip cannot be used in a Python interpreter.\n"
""
msgstr "பைதான் மொழிபெயர்ப்பாளரில் பிப்பைப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:614
msgid "I am guessing that you are attempting to use Python to run a program.\n"
"You must do so from a terminal and not from a Python interpreter.\n"
""
msgstr "நீங்கள் ஒரு நிரலை இயக்க பைத்தானைப் பயன்படுத்த முயற்சிக்கிறீர்கள் என்று நினைக்கிறேன். \n"
"நீங்கள் ஒரு முனையத்திலிருந்து அவ்வாறு செய்ய வேண்டும், பைதான் மொழிபெயர்ப்பாளரிடமிருந்து அல்ல.\n"
""

#: syntax_errors\statement_analyzer.py:624
msgid "You cannot have a dot `.` followed by `{bracket}`.\n"
""
msgstr "உங்களிடம் `.` புள்ளியை தொடர்ந்து `{bracket}` இருக்க முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:634
msgid "Perhaps you need to replace the dot by a comma.\n"
""
msgstr "ஒருவேளை நீங்கள் புள்ளியை காற்புள்ளியால் மாற்ற வேண்டும்.\n"
""

#: syntax_errors\statement_analyzer.py:645
msgid "It looks like you are trying to raise an exception using Python 2 syntax.\n"
""
msgstr "நீங்கள் Python 2 தொடரியல் பயன்படுத்தி விதிவிலக்கை உருவாக்க முயற்சிப்பது போல் தெரிகிறது.\n"
""

#: syntax_errors\statement_analyzer.py:700
msgid "Did you forget a colon `:`?\n"
""
msgstr "`:` என்ற முக்காற்புள்ளியை மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:703
msgid "You wrote a `{for_while}` loop but\n"
"forgot to add a colon `:` at the end\n"
"\n"
""
msgstr "நீங்கள் `{for_while}` வளையத்தை எழுதினீர்கள் ஆனால் இறுதியில் `:` என்ற \n"
"முக்காற்புள்ளியைச் சேர்க்க மறந்துவிட்டீர்கள்\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:710
msgid "You wrote a statement beginning with\n"
"`{name}` but forgot to add a colon `:` at the end.\n"
"\n"
""
msgstr "நீங்கள் `{name}` என்று தொடங்கும் அறிக்கையை எழுதியுள்ளீர்கள் ஆனால் இறுதியில் `:` \n"
"என்ற முக்காற்புள்ளியைச் சேர்க்க மறந்துவிட்டீர்கள்.\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:728
msgid "You wrote a semi-colon, `;`, where a comma was expected.\n"
""
msgstr "காற்புள்ளியை , எதிர்பார்க்கப்படும் இடத்தில் `;` என்ற அரைப்புள்ளியை எழுதியுள்ளீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:748
msgid "You wrote semi-colons, `;`, where commas were expected.\n"
""
msgstr "காற்புள்ளிகள் , எதிர்பார்க்கப்பட்ட இடத்தில் `;` என்ற அரைப்புள்ளிகளை எழுதியுள்ளீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:749
msgid "Did you mean to write commas?\n"
""
msgstr "காற்புள்ளிகளை எழுத வேண்டும் என்று சொன்னீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:767
msgid "Did you made a mistake in writing an hexadecimal integer?\n"
""
msgstr "பதின்ம முழு எண்ணை எழுதுவதில் தவறிழைத்தீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:768
msgid "It looks like you used an invalid character (`{character}`) in an hexadecimal number.\n"
"\n"
"Hexadecimal numbers are base 16 integers that use the symbols `0` to `9`\n"
"to represent values 0 to 9, and the letters `a` to `f` (or `A` to `F`)\n"
"to represent values 10 to 15.\n"
"In Python, hexadecimal numbers start with either `0x` or `0X`,\n"
"followed by the characters used to represent the value of that integer.\n"
""
msgstr "நீங்கள் பதின்ம எண்ணில் தவறான எழுத்தை (`{character}`) பயன்படுத்தியிருப்பது போல் தெரிகிறது. \n"
"\n"
"பதின்ம எண்கள் அடிப்படை 16 முழு எண்களாகும்,  0 முதல் 9 வரை மதிப்பை குறிக்க `0` முதல் `9` ,\n"
"மற்றும் 10 முதல் 15 வரை மதிப்புகளைக் குறிக்க `a` முதல் `f` (அல்லது `A` முதல் `F`) \n"
"வரையிலான குறியீடுகளை பயன்படுத்துகின்றன. \n"
"பைத்தானில், பதின்ம எண்கள் `0x` அல்லது `0X` உடன் தொடங்கும், அதைத் \n"
"தொடர்ந்து வரும் எழுத்துக்கள் அந்த முழு எண்ணின் மதிப்பைக் குறிக்கப் பயன்படுத்தப்படும்.\n"
""

#: syntax_errors\statement_analyzer.py:787
msgid "Did you made a mistake in writing an octal integer?\n"
""
msgstr "எண் முழு எண்ணை எழுதுவதில் தவறு செய்துவிட்டீர்களா?\n"
""

#. I think the word hexadecimal is wrong in this context. The right word is Octal.
#: syntax_errors\statement_analyzer.py:788
msgid "It looks like you used an invalid character (`{character}`) in an octal number.\n"
"\n"
"Octal numbers are base 8 integers that only use the symbols `0` to `7`\n"
"to represent values.\n"
"In Python, hexadecimal numbers start with either `0o` or `0O`,\n"
"(the digit zero followed by the letter `o`)\n"
"followed by the characters used to represent the value of that integer.\n"
""
msgstr "நீங்கள் எண்ம எண்ணில் தவறான எழுத்தை (`{character}`) பயன்படுத்தியது போல் தெரிகிறது. \n"
"\n"
"எண்ம எண்கள் அடிப்படை 8 முழு எண்களாகும், அவை மதிப்புகளைக் குறிக்க \n"
"`0` முதல் `7` வரையிலான குறியீடுகளை மட்டுமே பயன்படுத்துகின்றன. \n"
"பைத்தானில், எண்ம எண்கள் `0o` அல்லது `0O`, (இலக்க சுழியத்தைத் தொடர்ந்து \n"
"`o` என்ற எழுத்து) உடன் தொடங்கும், அதைத் தொடர்ந்து வரும் எழுத்துக்கள் அந்த \n"
"முழு எண்ணின் மதிப்பைக் குறிக்கப் பயன்படுத்தப்படும்.\n"
""

#: syntax_errors\statement_analyzer.py:815
msgid "Valid names cannot begin with a number.\n"
""
msgstr "சரியான பெயர்கள் எண்ணுடன் தொடங்க முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:822
msgid "Did you mean `{number}j`?\n"
""
msgstr "நீங்கள் `{number}j` என்று கூறுகிறீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:823
msgid "Perhaps you thought that `i` could be used to represent\n"
"the square root of `-1`. In Python, the symbol used for this is `j`\n"
"and the complex part is written as `some_number` immediately\n"
"followed by `j`, with no spaces in between.\n"
"Perhaps you meant to write `{number}j`.\n"
""
msgstr "`-1` இன் வர்க்க மூலத்தைக் குறிக்க `i` பயன்படுத்தப்படலாம் என்று நீங்கள் \n"
"நினைத்திருக்கலாம். பைத்தானில், இதற்குப் பயன்படுத்தப்படும் குறியீடு `j` மற்றும் \n"
"சிக்கலான பகுதி `சில_எண்` என எழுதப்பட்ட உடனே `j`, இடையில் \n"
"இடைவெளிகள் இல்லாமல். \n"
"ஒருவேளை நீங்கள் `{number}j` என்று எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:833
msgid "[Note: `{first} * {second}` would also be valid\n"
"since `{first}` is a complex number.]\n"
""
msgstr "[குறிப்பு: `{first}` ஒரு கலப்பு எண் என்பதால் `{first} * {second}` \n"
"என்பதும் செல்லுபடியாகும்.]\n"
""

#: syntax_errors\statement_analyzer.py:844
msgid "Perhaps you forgot a multiplication operator, `{first} * {second}`.\n"
""
msgstr "ஒருவேளை நீங்கள் பெருக்கல் இயக்கியை மறந்துவிட்டீர்கள், `{first} * {second}`.\n"
""

#: syntax_errors\statement_analyzer.py:859
msgid "Your Python version does not support this f-string feature.\n"
""
msgstr "உங்கள் பைதான் பதிப்பு இந்த f-சரம் அம்சத்தை ஆதரிக்கவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:860
msgid "You are likely using a 'debug' syntax of f-strings introduced\n"
"in Python version 3.8. You are using version {version}.\n"
""
msgstr "பைதான் பதிப்பு 3.8 இல் அறிமுகப்படுத்தப்பட்ட f-சரத்தின் 'பிழைத்திருத்த' தொடரியலை நீங்கள் பயன்படுத்துகிறீர்கள். \n"
"நீங்கள் பதிப்பு {version} ஐப் பயன்படுத்துகிறீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:866
msgid "You are likely trying to assign a value within an f-string.\n"
"This is not allowed.\n"
""
msgstr "நீங்கள் ஒரு f-சரத்தில் மதிப்பை ஒதுக்க முயற்சிக்கிறீர்கள். \n"
"இதற்கு அனுமதி இல்லை.\n"
""

#: syntax_errors\statement_analyzer.py:881
msgid "The content of your f-string is invalid. Please consult the documentation:\n"
"https://docs.python.org/3/reference/lexical_analysis.html#f-strings\n"
""
msgstr "உங்கள் f-சர உள்ளடக்கம் தவறானது. ஆவணங்களைப் பார்க்கவும்: \n"
"https://docs.python.org/3/reference/lexical_analysis.html#f-strings\n"
""

#: syntax_errors\statement_analyzer.py:891
msgid "Python keywords cannot be used as identifiers (variable names).\n"
""
msgstr "பைதான் முக்கியச்சொற்களை அடையாளங்காட்டிகளாகப் பயன்படுத்த முடியாது (மாறி பெயர்கள்).\n"
""

#: syntax_errors\statement_analyzer.py:912
msgid "`lambda` does not allow parentheses around its arguments.\n"
"This was allowed in Python 2 but it not allowed in Python 3.\n"
""
msgstr "`lambda` அதன் வாதங்களைச் சுற்றி அடைப்புக்குறிகளை அனுமதிக்காது. \n"
"இது பைதான் 2 இல் அனுமதிக்கப்பட்டது ஆனால் பைதான் 3 இல் அனுமதிக்கப்படவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:929
msgid "You cannot have explicit tuples as arguments.\n"
"Assign any tuple to a parameter and unpack it\n"
"within the body of the function.\n"
""
msgstr "நீங்கள் வெளிப்படையான மடங்குகளை வாதங்களாக வைத்திருக்க முடியாது. \n"
"எந்த மடங்கையும் ஒரு அளவுருவுக்கு ஒதுக்கி, செயல்பாட்டின் உடலில் \n"
"அதைத் திறக்கவும்.\n"
""

#: syntax_errors\statement_analyzer.py:962
msgid "If you remove `{type_decl}`, you will have a valid Python statement.\n"
""
msgstr "நீங்கள் `{type_decl}` ஐ அகற்றினால், உங்களிடம் சரியான பைதான் அறிக்கை இருக்கும்.\n"
""

#: syntax_errors\statement_analyzer.py:966
msgid "However, even if you remove `{type_decl}`, there would still be some\n"
"some syntax errors.\n"
""
msgstr "இருப்பினும், நீங்கள் `{type_decl}` ஐ அகற்றினாலும், சில தொடரியல் \n"
"பிழைகள் இருக்கும்.\n"
""

#: syntax_errors\statement_analyzer.py:971
msgid "You do not need to declare variables in Python.\n"
""
msgstr "நீங்கள் பைத்தானில் மாறிகளை அறிவிக்க வேண்டியதில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:972
msgid "It looks like you were trying to declare that `{var}` was\n"
"a variable using the word `{type_decl}`.\n"
""
msgstr "`{var}` என்பது `{type_decl}` என்ற வார்த்தையைப் பயன்படுத்தி ஒரு மாறி என்று \n"
"நீங்கள் அறிவிக்க முயற்சிப்பது போல் தெரிகிறது.\n"
""

#: syntax_errors\statement_analyzer.py:1005
msgid "I am guessing that you forgot a comma between two strings\n"
"when defining a dict.\n"
"\n"
""
msgstr "ஒரு அகராதியை வரையறுக்கும்போது இரண்டு சரங்களுக்கு இடையே உள்ள \n"
"காற்புள்ளியை நீங்கள் மறந்துவிட்டீர்கள் என்று நினைக்கிறேன்.\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:1048
msgid "Did you forget to write `in`?\n"
""
msgstr "`in` எழுத மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:1049
msgid "It looks as though you forgot to use the keyword `in`\n"
"as part of a `for` statement. Perhaps you meant:\n"
"\n"
"    {new_statement}\n"
"\n"
""
msgstr "`for` அறிக்கையின் ஒரு பகுதியாக `in` என்ற முக்கிய சொல்லைப் பயன்படுத்த \n"
"மறந்துவிட்டது போல் தெரிகிறது. ஒருவேளை நீங்கள் இவ்வாறு குறிப்பிட்டிருக்கலாம்:\n"
"\n"
"   {new_statement}\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:1071
msgid "Did you forget to write parenthesis?\n"
""
msgstr "அடைப்புக்குறி எழுத மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:1072
msgid "It looks as though you forgot to use to use parenthesis with `range`.\n"
"Perhaps you meant:\n"
"\n"
"    {new_statement}\n"
"\n"
""
msgstr "`range` உடன் அடைப்புக்குறியைப் பயன்படுத்த மறந்துவிட்டது போல் தெரிகிறது. \n"
"ஒருவேளை நீங்கள் இவ்வாறு குறிப்பிட்டிருக்கலாம்: \n"
"\n"
"   {new_statement}\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:1104
msgid "Perhaps you meant to write `{keyword}` and made a typo.\n"
"The correct line might be `{line}`\n"
""
msgstr "ஒருவேளை நீங்கள் `{keyword}` என்று எழுத நினைத்திருக்கலாம் மற்றும் எழுத்துப் பிழை செய்திருக்கலாம். \n"
"சரியான வரி `{line}` ஆக இருக்கலாம்\n"
""

#: syntax_errors\statement_analyzer.py:1117
msgid "I am guessing that you were writing a comprehension or a generator expression\n"
"and use the wrong order for a condition.\n"
"The correct order depends if there is an `else` clause or not.\n"
"For example, the correct order for a list comprehensions with\n"
"condition can be either\n"
"\n"
"    [f(x) if condition else other for x in sequence]  # 'if' before 'for'\n"
"\n"
"or, if there is no `else`\n"
"\n"
"    [f(x) for x in sequence if condition]  # 'if' after 'for'\n"
"\n"
""
msgstr "நீங்கள் ஒரு புரிதல் அல்லது உருவாக்கி வெளிப்பாடு எழுதுகிறீர்கள் என்று நான் \n"
"நினைக்கிறேன் மற்றும் ஒரு நிபந்தனைக்கு தவறான வரிசையைப் பயன்படுத்துகிறீர்கள். \n"
"சரியான வரிசையானது `else` பிரிவு இருக்கிறதா இல்லையா என்பதைப் பொறுத்தது. \n"
"எடுத்துக்காட்டாக, நிபந்தனையுடன் கூடிய பட்டியலைப் புரிந்துகொள்வதற்கான \n"
"சரியான வரிசையானது \n"
"\n"
"    [f(x) if நிபந்தனை else மற்றது for ஐ in வரிசை]  # 'for'க்கு முன் 'if'\n"
"\n"
"அல்லது, `else` இல்லை என்றால்\n"
"\n"
"    [f(x) for ஐ in வரிசை if நிபந்தனை]  # 'for'க்கு பிறகு 'if' \n"
"\n"
""

#: syntax_errors\statement_analyzer.py:1220
msgid "You cannot have spaces in identifiers (variable names).\n"
""
msgstr "அடையாளங்காட்டிகளில் (மாறி பெயர்கள்) நீங்கள் இடைவெளிகளைக் கொண்டிருக்க முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:1239
msgid "`bf` is an illegal string prefix.\n"
""
msgstr "`bf` என்பது ஒரு சட்டவிரோத சரம் முன்னொட்டு.\n"
""

#: syntax_errors\statement_analyzer.py:1240
msgid "I am guessing that you wanted a binary f-string;\n"
"this is not allowed.\n"
""
msgstr "உங்களுக்கு ஒரு பைனரி f-சரம் வேண்டும் என்று நான் நினைக்கிறேன்; \n"
"இது அனுமதிக்கப்படவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:1264
msgid "It is possible that you forgot a comma between items in a tuple, \n"
"or between function arguments, \n"
"before the position indicated by ^.\n"
""
msgstr "^ஆல் சுட்டிக்காட்டப்பட்ட நிலைக்கு முன், ஒரு மடங்கில் உள்ள உருப்படிகளுக்கு \n"
"இடையில் அல்லது செயல்பாட்டு வாதங்களுக்கு இடையில் நீங்கள் காற்புள்ளியை \n"
"மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:1272
msgid "It is possible that you forgot a comma between items in a list\n"
"before the position indicated by ^.\n"
""
msgstr "^ ஆல் குறிப்பிடப்பட்ட நிலைக்கு முன் பட்டியலில் உள்ள உருப்படிகளுக்கு இடையே \n"
"உள்ள காற்புள்ளியை நீங்கள் மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:1278
msgid "It is possible that you forgot a comma between items in a set or dict\n"
"before the position indicated by ^.\n"
""
msgstr "^ ஆல் குறிப்பிடப்பட்ட நிலைக்கு முன் ஒரு தொகுப்பு அல்லது அகராதியில் உள்ள \n"
"உருப்படிகளுக்கு இடையே உள்ள காற்புள்ளியை நீங்கள் மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\statement_analyzer.py:1302
msgid "Python indicates that the error is caused by `{second}` written immediately after `{first}`.\n"
""
msgstr "`{first}` க்குப் பிறகு உடனடியாக எழுதப்பட்ட `{second}` மூலம் பிழை ஏற்பட்டது என்பதை பைதான் குறிக்கிறது.\n"
""

#: syntax_errors\statement_analyzer.py:1332
msgid "Perhaps you meant\n"
"\n"
"    {line}\n"
""
msgstr "ஒருவேளை நீங்கள் பின்வருமாறு சொல்கிறீர்கள்\n"
"\n"
"   {line}\n"
""

#: syntax_errors\statement_analyzer.py:1339
msgid "Did you forget something between `{first}` and `{second}`?\n"
""
msgstr "`{first}` மற்றும் `{second}` இடையே ஏதாவது மறந்துவிட்டீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:1354
msgid "Perhaps you meant to insert an operator like `{operators}`\n"
"between `{first}` and `{second}`.\n"
"The following lines of code would not cause any `SyntaxError`:\n"
"\n"
""
msgstr "`{first}` மற்றும் `{second}` இடையே `{operators}` போன்ற இயக்கியைச் செருக \n"
"நினைத்திருக்கலாம். பின்வரும் குறியீடு வரிகள் எந்த `தொடரியல்பிழை` யையும் \n"
"ஏற்படுத்தாது:\n"
"\n"
""

#: syntax_errors\statement_analyzer.py:1363
msgid "Note: these are just some of the possible choices and that\n"
"some of them might raise other types of exceptions.\n"
""
msgstr "குறிப்பு: இவை சாத்தியமான சில தேர்வுகள் மற்றும் அவற்றில் சில வேறு வகையான \n"
"விதிவிலக்குகளை எழுப்பலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:1385
msgid "It is possible that you used an equal sign `=` instead of a colon `:`\n"
"to assign values to keys in a dict\n"
"before or at the position indicated by ^.\n"
""
msgstr "^ ஆல் சுட்டிக்காட்டப்பட்ட நிலையில் உள்ள ஒரு அகராதியில் உள்ள விசைகளுக்கு \n"
"மதிப்புகளை ஒதுக்க, முக்காற்புள்ளி `:` என்பதற்குப் பதிலாக `=` என்ற சம \n"
"அடையாளத்தைப் பயன்படுத்தியிருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:1402
msgid "The Python keyword `{boolean}` can only be used for boolean expressions.\n"
"Perhaps you meant to write\n"
"\n"
"`{new_statement}`\n"
""
msgstr "பைதான் முக்கியச்சொல் `{boolean}` பூலியன் வெளிப்பாடுகளுக்கு மட்டுமே பயன்படுத்தப்படும். \n"
"ஒருவேளை நீங்கள் பின்வருமாறு எழுத நினைத்திருக்கலாம்\n"
"\n"
"`{new_statement}`\n"
""

#: syntax_errors\statement_analyzer.py:1434
msgid "I am guessing that you are trying to import at least one object\n"
"from module `{module}` and rename it using the Python keyword `as`;\n"
"this keyword can only be used to rename one object at a time\n"
"using a well defined syntax.\n"
"I suggest that you split up any such import statement with each object\n"
"renamed on a separate line as follows:\n"
"\n"
"    from {module} import object_1 as name_1\n"
"    from {module} import object_2 as name_2  # if needed\n"
""
msgstr "நீங்கள் தொகுதி `{module}` இலிருந்து குறைந்தபட்சம் ஒரு பொருளை இறக்குமதி செய்து, பைதான் முக்கிய சொல்லான `as` ஐப் பயன்படுத்தி மறுபெயரிட \n"
"முயற்சிக்கிறீர்கள் என்று நினைக்கிறேன்; \n"
"நன்கு வரையறுக்கப்பட்ட தொடரியல் மூலம் ஒரே நேரத்தில் ஒரு பொருளை \n"
"மறுபெயரிட மட்டுமே இந்த முக்கிய சொல்லைப் பயன்படுத்த முடியும். \n"
"ஒவ்வொரு பொருளுக்கும் தனித்தனி வரியில் மறுபெயரிடப்பட்ட அத்தகைய \n"
"இறக்குமதி அறிக்கையைப் பின்வருமாறு பிரிக்குமாறு நான் பரிந்துரைக்கிறேன்: \n"
"\n"
"    from {module} import பொருள்_1 as பெயர்_1\n"
"    from {module} import பொருள்_2 as பெயர்_2  # ஆக தேவைப்பட்டால்\n"
""

#: syntax_errors\statement_analyzer.py:1464
msgid "I am guessing that you wrote {bad_token} twice in a row by mistake.\n"
"If that is the case, you need to remove the second one.\n"
""
msgstr "நீங்கள் தவறுதலாக இரண்டு முறை {bad_token} என்று எழுதிவிட்டீர்கள் என்று நினைக்கிறேன். \n"
"அப்படியானால், நீங்கள் இரண்டாவதாக அகற்ற வேண்டும்.\n"
""

#: syntax_errors\statement_analyzer.py:1468
msgid "Did you write {bad_token} twice by mistake?\n"
""
msgstr "தவறுதலாக இரண்டு முறை {bad_token} என்று எழுதிவிட்டீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:1487
msgid "I am guessing that you wrote {bad_token} by mistake.\n"
"Removing it and writing `{line}` seems to fix the error.\n"
""
msgstr "நீங்கள் தவறுதலாக {bad_token} எழுதிவிட்டீர்கள் என்று நினைக்கிறேன். \n"
"அதை நீக்கிவிட்டு `{line}` எழுதுவது பிழையை சரிசெய்வதாகத் தெரிகிறது.\n"
""

#: syntax_errors\statement_analyzer.py:1491
msgid "Did you write {bad_token} by mistake?\n"
""
msgstr "தவறுதலாக {bad_token} என்று எழுதிவிட்டீர்களா?\n"
""

#: syntax_errors\statement_analyzer.py:1508
msgid "It looks like the error occurred as you were writing a Python dict.\n"
"Perhaps wrote a dict key without writing the corresponding value.\n"
""
msgstr "நீங்கள் பைதான் அகராதியை எழுதும் போது பிழை ஏற்பட்டது போல் தெரிகிறது. \n"
"தொடர்புடைய மதிப்பை எழுதாமல் ஒரு அகராதி திறவுகோலை எழுதியிருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:1619
msgid "The opening {bracket} on line {linenumber} is not closed.\n"
""
msgstr "வரி {linenumber} இல் திறப்பு {bracket} மூடப்படவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:1633
msgid "If this is incorrect, please report this case.\n"
""
msgstr "இது தவறாக இருந்தால், இந்த வழக்கைப் புகாரளிக்கவும்.\n"
""

#: syntax_errors\syntax_utils.py:21
msgid "parenthesis `(`"
msgstr "அடைப்புக்குறி `(`"

#: syntax_errors\syntax_utils.py:22
msgid "parenthesis `)`"
msgstr "அடைப்புக்குறி `)`"

#: syntax_errors\syntax_utils.py:23
msgid "square bracket `[`"
msgstr "சதுர அடைப்புக்குறி `[`"

#: syntax_errors\syntax_utils.py:24
msgid "square bracket `]`"
msgstr "சதுர அடைப்புக்குறி `]`"

#: syntax_errors\syntax_utils.py:25
msgid "curly bracket `{`"
msgstr "சுருள் அடைப்புக்குறி `{`"

#: syntax_errors\syntax_utils.py:26
msgid "curly bracket `}`"
msgstr "சுருள் அடைப்புக்குறி `}`"

#: syntax_errors\syntax_utils.py:55
msgid "Did you mean to use a normal quote character, `'` or `\"`?\n"
""
msgstr "சாதாரண மேற்கோள் எழுத்தான `'` அல்லது `\"` ஐப் பயன்படுத்த விரும்புகிறீர்களா?\n"
""

#: syntax_errors\syntax_utils.py:56
msgid "I suspect that you used a fancy unicode quotation mark\n"
"whose name is {name}\n"
"instead of a normal single or double quote for a string.\n"
""
msgstr "ஒரு சரத்திற்கான சாதாரண ஒற்றை அல்லது இரட்டை மேற்கோளுக்கு பதிலாக \n"
"{name} \n"
"என்ற ஆடம்பரமான ஒருங்குறி மேற்கோள் குறியைப் பயன்படுத்தியுள்ளீர்கள் என்று நான் சந்தேகிக்கிறேன்.\n"
""

#: syntax_errors\syntax_utils.py:71
msgid "Or perhaps, you meant to write a less than sign, `<`.\n"
""
msgstr "அல்லது ஒருவேளை, `<` என்ற விட குறைவாக அடையாளத்தை எழுத வேண்டும் என்று நீங்கள் நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\syntax_utils.py:73
msgid "Or perhaps, you meant to write a greater than sign, `>`.\n"
""
msgstr "அல்லது ஒருவேளை, நீங்கள் பெரியது `>` அடையாளத்தை எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\syntax_utils.py:75
msgid "Or perhaps, you meant to write a comma.\n"
""
msgstr "அல்லது ஒருவேளை, நீங்கள் காற்புள்ளியை எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\syntax_utils.py:88
msgid "I suspect that you used a fancy unicode quotation mark\n"
"whose name is {name}.\n"
"\n"
""
msgstr "நீங்கள் {name} என்ற ஆடம்பரமான ஒருங்குறி மேற்கோள் குறிகளைப் \n"
"பயன்படுத்தியுள்ளீர்கள் என்று சந்தேகிக்கிறேன்.\n"
"\n"
""

#: syntax_errors\syntax_utils.py:103
msgid "Perhaps, you meant to write a less than sign, `<`.\n"
""
msgstr "ஒருவேளை, நீங்கள் ஒரு சிறியது `<` அடையாளத்தை எழுத வேண்டும்.\n"
""

#: syntax_errors\syntax_utils.py:104
msgid "Did you mean to write a less than sign, `<`?\n"
""
msgstr "சிறியது `<` என்ற அடையாளத்தை எழுத நினைத்தீர்களா?\n"
""

#: syntax_errors\syntax_utils.py:106
msgid "Perhaps, you meant to write a greater than sign, `>`.\n"
""
msgstr "ஒருவேளை, நீங்கள் ஒரு பெரியது `>` அடையாளத்தை எழுத வேண்டும்.\n"
""

#: syntax_errors\syntax_utils.py:107
msgid "Did you mean to write a greater than sign, `>`?\n"
""
msgstr "பெரியது `>` என்ற அடையாளத்தை எழுத நினைத்தீர்களா?\n"
""

#: syntax_errors\syntax_utils.py:109
msgid "Perhaps, you meant to write a comma.\n"
""
msgstr "ஒருவேளை, நீங்கள் காற்புள்ளியை எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\syntax_utils.py:123
msgid "I suspect that you used the unicode character known as\n"
"'FRACTION SLASH', which looks similar to\n"
"but is different from the division operator `/`.\n"
""
msgstr "'FRACTION SLASH' எனப்படும் ஒருங்குறி எழுத்தை நீங்கள் பயன்படுத்தியுள்ளீர்கள் என்று \n"
"சந்தேகிக்கிறேன், இது போல் தோற்றமளிக்கும் ஆனால் பிரிவு \n"
"இயக்கி `/` இலிருந்து வேறுபட்டது.\n"
""

#: syntax_errors\syntax_utils.py:130
msgid "Did you use a unicode fraction?\n"
""
msgstr "ஒருங்குறி பின்னத்தைப் பயன்படுத்துகிறீர்களா?\n"
""

#: syntax_errors\syntax_utils.py:131
msgid "I suspect that you used the unicode character `{char}`meant to represent a fraction.\n"
"The name of this unicode character is {name}.\n"
""
msgstr "நீங்கள் ஒருங்குறி எழுத்தான `{char}`ஐப் பயன்படுத்தியிருப்பதை நான் சந்தேகிக்கிறேன்.\n"
"இந்த ஒருங்குறி எழுத்தின் பெயர் {name}.\n"
""

#: syntax_errors\syntax_utils.py:168
msgid "Did you mean `{num}/{denom}`?\n"
""
msgstr "`{num}/{denom}` எனக் குறிப்பிடுகிறீர்களா?\n"
""

#: syntax_errors\syntax_utils.py:169
msgid "You used the unicode character {char} which is known as\n"
"{name}\n"
"I suspect that you meant to write the fraction `{num}/{denom}` instead.\n"
""
msgstr "நீங்கள் ஒருங்குறி எழுத்தை {char} பயன்படுத்தியுள்ளீர்கள்\n"
"{name}\n"
"அதற்குப் பதிலாக `{num}/{denom}` என்ற பின்னத்தை எழுத நினைத்தீர்கள் என்று சந்தேகிக்கிறேன்.\n"
""

#: syntax_errors\statement_analyzer.py:1571
msgid "You used square brackets, `[...]` instead of parentheses.\n"
""
msgstr "அடைப்புக்குறிகளுக்குப் பதிலாக சதுர அடைப்புக்குறிகளைப் பயன்படுத்தியுள்ளீர்கள், `[...]`.\n"
""

#: syntax_errors\statement_analyzer.py:1575
msgid "Write the following instead:\n"
"\n"
"{new_statement}"
msgstr "அதற்கு பதிலாக பின்வருவனவற்றை எழுதவும்:\n"
"\n"
"{new_statement}"

#: runtime_errors\type_error.py:70
msgid "The second argument of the function `getattr()` must be a string.\n"
""
msgstr "`getattr()` செயல்பாட்டின் இரண்டாவது வாதம் ஒரு சரமாக இருக்க வேண்டும்.\n"
""

#: runtime_errors\type_error.py:80
msgid "The second argument of the function `hasattr()` must be a string.\n"
""
msgstr "`hasattr()` செயல்பாட்டின் இரண்டாவது வாதம் ஒரு சரமாக இருக்க வேண்டும்.\n"
""

#: runtime_errors\unbound_local_error.py:85
msgid "`{name}` is a Python builtin function.\n"
"You have tried to assign a value to `{name}` inside a function\n"
"while also using its original meaning in the function.\n"
"\n"
"Note that it is generally not a good idea to give a local variable\n"
"the same name as a Python builtin function (like `{name}`).\n"
""
msgstr "`{name}` என்பது பைதான் உள்ளமைக்கப்பட்ட செயல்பாடு.\n"
"செயல்பாட்டில் அதன் அசல் பொருளைப் பயன்படுத்தும் போது, ஒரு \n"
"செயல்பாட்டிற்குள் `{name}` க்கு மதிப்பை ஒதுக்க முயற்சித்தீர்கள்.\n"
"\n"
"பைதான் உள்ளமைக்கப்பட்ட செயல்பாட்டின் அதே பெயரை உள்ளூர் மாறிக்கு \n"
"வழங்குவது பொதுவாக நல்ல யோசனையல்ல என்பதை நினைவில் கொள்க (`{name}` போன்றவை).\n"
""

#: syntax_errors\message_analyzer.py:257 syntax_errors\message_analyzer.py:866
msgid "You cannot assign a value to `{keyword}`.\n"
""
msgstr "`{keyword}`க்கு மதிப்பை ஒதுக்க முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:868
msgid "You likely called a function using the Python keyword `{keyword}` as an argument:\n"
"\n"
"    a_function({keyword}=something) \n"
"\n"
"which Python interpreted as trying to assign a value to a Python keyword.\n"
"\n"
""
msgstr "நீங்கள் பைதான் முக்கிய சொல்லான `{keyword}` ஐ ஒரு வாதமாகப் பயன்படுத்தி ஒரு செயல்பாட்டை அழைக்கலாம்:\n"
"\n"
"     ஒரு_செயல்பாடு({keyword}=ஏதாவது)\n"
"\n"
"பைதான் முக்கிய சொல்லுக்கு மதிப்பை ஒதுக்க முயற்சிப்பதாக பைதான் விளக்குகிறது.\n"
"\n"
""

#: syntax_errors\message_analyzer.py:879
msgid "You likely called a function with a named argument:\n"
"\n"
"    a_function(invalid=something) \n"
"\n"
"where `invalid` is not a valid variable name in Python\n"
"either because it starts with a number, or is a string,\n"
"or contains a period, etc.\n"
""
msgstr "பெயரிடப்பட்ட வாதத்துடன் ஒரு செயல்பாட்டை நீங்கள் அழைக்கலாம்:\n"
"\n"
"     ஒரு_செயல்பாடு(invalid=ஏதோ)\n"
"\n"
"இங்கு `invalid` என்பது பைத்தானில் செல்லுபடியாகும் மாறிப் பெயர் அல்ல\n"
"அது ஒரு எண்ணுடன் தொடங்குவதால், அல்லது ஒரு சரம்,\n"
"அல்லது ஒரு காலகட்டம் போன்றவை உள்ளன.\n"
""

#: syntax_errors\statement_analyzer.py:1370
msgid "There is an additional possibility.\n"
""
msgstr "கூடுதல் வாய்ப்பு உள்ளது.\n"
""

#: functions_help.py:15
msgid "Changes the prompt style to be used in the console."
msgstr "கன்சோலில் பயன்படுத்த வேண்டிய ப்ராம்ட் ஸ்டைலை மாற்றுகிறது."

#: runtime_errors\value_error.py:342
msgid "The value you gave for the time is not in the format you specified.\n"
"Make sure to use the same separator between items\n"
"(for example, between day and month) and keep the order the same\n"
"in both the data provided and the format you specified.\n"
"The following table might be useful:\n"
"https://docs.python.org/3/library/time.html#time.strftime\n"
"The following site might also be useful: https://www.strfti.me/\n"
""
msgstr "நேரத்திற்கு நீங்கள் கொடுத்த மதிப்பு நீங்கள் குறிப்பிட்ட வடிவத்தில் இல்லை.\n"
"உருப்படிகளுக்கு இடையில் ஒரே பிரிப்பானைப் பயன்படுத்துவதை உறுதிசெய்து \n"
"(உதாரணமாக, நாள் மற்றும் மாதத்திற்கு இடையில்) மற்றும் வழங்கப்பட்ட தரவு \n"
"மற்றும் நீங்கள் குறிப்பிட்ட வடிவமைப்பு இரண்டிலும் வரிசையை ஒரே மாதிரியாக வைத்திருக்கவும்.\n"
"பின்வரும் அட்டவணை பயனுள்ளதாக இருக்கும்:\n"
"https://docs.python.org/3/library/time.html#time.strftime\n"
"பின்வரும் தளமும் பயனுள்ளதாக இருக்கும்: https://www.strfti.me/\n"
""

#: syntax_errors\message_analyzer.py:923
msgid "You have written an f-string which has an unmatched `}`.\n"
"If you want to print a single `}`, you need to write `}}` in the f-string;\n"
"otherwise, you need to add an opening `{`.\n"
""
msgstr "நீங்கள் ஒரு f-சரம் எழுதியுள்ளீர்கள், அதில் பொருந்தாத `}` உள்ளது.\n"
"நீங்கள் ஒற்றை `}` ஐ அச்சிட விரும்பினால், f-சரத்தில் `}}` எழுத வேண்டும்; \n"
"இல்லையெனில், நீங்கள் திறக்கும் `{` ஐச் சேர்க்க வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:935
msgid "You have written an f-string which has an unmatched `{`.\n"
"If you want to print a single `{`, you need to write `{{` in the f-string;\n"
"otherwise, you need to add a closing `}`.\n"
""
msgstr "நீங்கள் ஒரு f-சரம் எழுதியுள்ளீர்கள், அதில் பொருந்தாத `{` உள்ளது.\n"
"நீங்கள் ஒற்றை `{` ஐ அச்சிட விரும்பினால், f-சரத்தில் `{{` எழுத வேண்டும்; \n"
"இல்லையெனில், நீங்கள் மூடும் `}` ஐச் சேர்க்க வேண்டும்.\n"
""

#: syntax_errors\message_analyzer.py:1194
msgid "You cannot use the `*` operator to unpack the iteration variable\n"
"in a comprehension.\n"
""
msgstr "புரிந்துகொள்ளுதலில் மறு செய்கை மாறியைத் திறக்க நீங்கள் `*` \n"
"இயக்கியைப் பயன்படுத்த முடியாது.\n"
""

#: syntax_errors\message_analyzer.py:1206
#: syntax_errors\message_analyzer.py:1553
#: syntax_errors\statement_analyzer.py:453
msgid "The following statement has no syntax error:\n"
"\n"
"    {statement}\n"
""
msgstr "பின்வரும் அறிக்கையில் தொடரியல் பிழை இல்லை:\n"
"\n"
"     {statement}\n"
""

#: syntax_errors\message_analyzer.py:1543
msgid "It looks like you tried to use a starred expression as a dict value;\n"
"this is not allowed.\n"
""
msgstr "நட்சத்திரமிடப்பட்ட வெளிப்பாட்டை அகராதி மதிப்பாகப் பயன்படுத்த முயற்சித்தது போல் தெரிகிறது; \n"
"இது அனுமதிக்கப்படவில்லை.\n"
""

#: syntax_errors\statement_analyzer.py:1524
msgid "The `else` keyword does not begin a code block that matches\n"
"a valid code block, possibly because `else` is not indented correctly.\n"
""
msgstr "`else` முக்கிய சொல் சரியான குறியீடு தொகுதியுடன் பொருந்தக்கூடிய குறியீடு \n"
"தொகுதியைத் தொடங்காது, ஒருவேளை `else` சரியாக உள்தள்ளப்படாததால் இருக்கலாம்.\n"
""

#: syntax_errors\statement_analyzer.py:1539
msgid "The `elif` keyword does not begin a code block that matches\n"
"an `if` block, possibly because `elif` is not indented correctly.\n"
""
msgstr "`elif` முக்கிய சொல்லானது, `if` தொகுதியுடன் பொருந்தக்கூடிய குறியீடுத் \n"
"தொகுதியைத் தொடங்கவில்லை, ஒருவேளை `elif` சரியாக உள்தள்ளப்படாததால் இருக்கலாம்.\n"
""

#: runtime_errors\name_error.py:33
msgid "`{name}` is a name found in module `{mod}`.\n"
"Perhaps you forgot to write\n"
"\n"
"    from {mod} import {name}\n"
""
msgstr "`{name}` என்பது தொகுதி `{mod}` இல் காணப்படும் பெயர்.\n"
"ஒருவேளை நீங்கள் எழுத மறந்துவிட்டீர்கள்\n"
"\n"
"    from {mod} import {name}\n"
""

#: runtime_errors\name_error.py:37
msgid "`{name}` is a name found in the following modules from the standard library:\n"
"{modules}.\n"
"Perhaps you forgot to import `{name}` from one of these modules.\n"
""
msgstr "`{name}` என்பது நிலையான நூலகத்திலிருந்து பின்வரும் தொகுதிகளில் காணப்படும் பெயர்:\n"
"{modules}.\n"
"இந்த தொகுதிகளில் ஒன்றிலிருந்து `{name}` ஐ இறக்குமதி செய்ய மறந்துவிட்டீர்கள்.\n"
""

#: syntax_errors\message_analyzer.py:128
msgid "On the left-hand side of an equal sign, you have a\n"
"conditional expression instead of the name of a variable.\n"
"A conditional expression has the following form:\n"
"\n"
"    variable = object if condition else other_object\n"
""
msgstr "சம அடையாளத்தின் இடது புறத்தில், மாறியின் பெயருக்குப் பதிலாக \n"
"நிபந்தனை வெளிப்பாடு உள்ளது.\n"
"நிபந்தனை வெளிப்பாடு பின்வரும் வடிவத்தைக் கொண்டுள்ளது:\n"
"\n"
"     மாறி = பொருள் if நிபந்தனை else மற்ற_பொருள்\n"
""

#: syntax_errors\message_analyzer.py:556
msgid "The following statement would not contain a syntax error:\n"
"\n"
"    {new_statement}\n"
""
msgstr "பின்வரும் அறிக்கையில் தொடரியல் பிழை இருக்காது:\n"
"\n"
"     {new_statement}\n"
""

#: syntax_errors\statement_analyzer.py:533
msgid "The following statement would not contain a syntax error:\n"
"\n"
"    {new_statement}"
msgstr "பின்வரும் அறிக்கையில் தொடரியல் பிழை இருக்காது:\n"
"\n"
"     {new_statement}"

#: runtime_errors\unbound_local_error.py:32
msgid "You're trying to use the name `{name}` identified by Python as being\n"
"in the local scope of a function before having assigned it a value.\n"
""
msgstr "பைத்தானால் அடையாளம் காணப்பட்ட `{name}` என்ற பெயரைப் பயன்படுத்த முயல்கிறீர்கள், \n"
"அதற்கு மதிப்பை வழங்குவதற்கு முன், செயல்பாட்டின் உள்ளூர் நோக்கத்தில் உள்ளது.\n"
""

#: runtime_errors\value_error.py:326
msgid "Its docstring is:\n"
"\n"
"{docstring}\n"
""
msgstr "அதன் ஆவணசரம்:\n"
"\n"
"{docstring}\n"
""

#: runtime_errors\value_error.py:166
msgid "The following characters are not allowed: `{invalid}`.\n"
""
msgstr "பின்வரும் எழுத்துகள் அனுமதிக்கப்படாது: `{invalid}`.\n"
""

#: runtime_errors\value_error.py:178
msgid "When base `0` is specified, `int()` expects the argument\n"
"to be an integer literal, written in\n"
"base 2 (`0b...`), 8 (`0o...`), 10, or 16 (`0x...`).\n"
""
msgstr "அடிப்படை `0` குறிப்பிடப்பட்டால், `int()` வாதமானது அடிப்படை \n"
"2 (`0b...`), 8 (`0o...`), 10 அல்லது 16 (`0x...`)\n"
"இல் எழுதப்பட்ட முழு எண்ணாக இருக்க வேண்டும் என்று எதிர்பார்க்கிறது.\n"
""

#: runtime_errors\value_error.py:223
msgid "The argument `base` of `int()` must be either zero\n"
"or any integer from 2 to 36.\n"
""
msgstr "`int()` இன் வாதத்தின் `base` சுழியமாகவோ அல்லது \n"
"2 முதல் 36 வரையிலான முழு எண்ணாகவோ இருக்க வேண்டும்.\n"
""

#: runtime_errors\value_error.py:231
msgid "You wrote {base} which is not allowed.\n"
""
msgstr "அனுமதிக்கப்படாத {base} என்று எழுதியுள்ளீர்கள்.\n"
""

#: runtime_errors\value_error.py:262
msgid "The string `{string}` cannot be converted to a `float`.\n"
""
msgstr "`{string}` சரத்தை `float` ஆக மாற்ற முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:1645
msgid "Perhaps you wrote a statement beginning a code block\n"
"intended to be part of a generator expression.\n"
"You cannot have separate code blocks inside generator expressions.\n"
""
msgstr "உருவாக்கி வெளிப்பாட்டின் ஒரு பகுதியாக இருக்க வேண்டும் என்பதற்காக,\n"
"குறியீடு தொகுதியைத் தொடங்கி அறிக்கையை நீங்கள் எழுதியிருக்கலாம்.\n"
"உருவாக்கி வெளிப்பாடுகளுக்குள் தனி குறியீடு தொகுதிகள் இருக்க முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:1651
msgid "Perhaps you wrote a statement beginning a code block\n"
"intended to be part of a list comprehension.\n"
"You cannot have separate code blocks inside list comprehensions.\n"
""
msgstr "பட்டியல் புரிந்துகொள்ளுதலின் ஒரு பகுதியாக இருக்க வேண்டும் என்பதற்காக, \n"
"குறியீடு தொகுதியைத் தொடங்கி அறிக்கையை நீங்கள் எழுதியிருக்கலாம்.\n"
"பட்டியல் புரிதல்களுக்குள் தனி குறியீடு தொகுதிகள் இருக்க முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:1657
msgid "Perhaps you wrote a statement beginning a code block\n"
"intended to be part of a dict or set comprehension.\n"
"You cannot have separate code blocks inside dict or set comprehensions.\n"
""
msgstr "ஒரு அகராதியின் அல்லது தொகுப்பின் புரிதலின் ஒரு பகுதியாக இருக்க வேண்டும் \n"
"என்பதற்காக, குறியீடு தொகுதியைத் தொடங்கி அறிக்கையை நீங்கள் எழுதியிருக்கலாம்.\n"
"அகராதி அல்லது தொகுப்பு புரிதல்களுக்குள் நீங்கள் தனி குறியீடு தொகுதிகளை வைத்திருக்க முடியாது.\n"
""

#: syntax_errors\statement_analyzer.py:1663
msgid "If this explanation is incorrect, please report this case.\n"
""
msgstr "இந்த விளக்கம் தவறாக இருந்தால், இந்த வழக்கைப் புகாரளிக்கவும்.\n"
""

#: runtime_errors\value_error.py:291
msgid "The third argument of the function `pow()` cannot be zero.\n"
""
msgstr "`pow()` செயல்பாட்டின் மூன்றாவது வாதம் சுழியமாக இருக்க முடியாது.\n"
""

#: core.py:686
msgid "The entire content of `{filename}` is not available.\n"
""
msgstr "`{filename}` இன் முழு உள்ளடக்கமும் கிடைக்கவில்லை.\n"
""

#: debug_helper.py:51
msgid "Please report this issue."
msgstr "இந்தச் சிக்கலைப் புகாரளிக்கவும்."

#: debug_helper.py:72
msgid "Fatal error - aborting"
msgstr "கொடிய பிழை - கலைக்கிறது"

#: functions_help.py:16
msgid "Shows the generic meaning of a given exception."
msgstr "கொடுக்கப்பட்ட விதிவிலக்கின் பொதுவான பொருளைக் காட்டுகிறது."

#: info_generic.py:211
msgid "A `RuntimeError` is raised when an error is detected that doesn't fall in any\n"
"of the more specific exception types defined by Python.\n"
""
msgstr "பைத்தானால் வரையறுக்கப்பட்ட எந்த குறிப்பிட்ட விதிவிலக்கு வகைகளிலும்\n"
"வராத பிழை கண்டறியப்பட்டால் இயக்கநேரப்பிழை`RuntimeError` எழுப்பப்படுகிறது.\n"
""

#: runtime_errors\runtime_error.py:50
msgid "While you were iterating over the items of `{name}` ({container_type})\n"
"in a `{for_while}` loop, you either tried to add or remove items from it.\n"
"Suggestion: start by making a copy of `{name}` and iterate over the items\n"
"of that copy if you want to change `{name}` inside a loop.\n"
"You might want to do this as follows:\n"
"\n"
"    my_{name} = {name}.copy()\n"
"    for item in my_{name}:\n"
"        # Change {name}\n"
""
msgstr "`{for_while}` சுழலில் `{name}` ({container_type}) உருப்படிகளை மீண்டும்\n"
"மீண்டும் செய்துகொண்டிருந்தீர்கள், அதிலிருந்து உருப்படிகளைச் சேர்க்க அல்லது அகற்ற முயற்சித்தீர்கள்.\n"
"பரிந்துரை: `{name}` இன் நகலை உருவாக்கி, சுழலில் `{name}` ஐ மாற்ற\n"
"விரும்பினால், அந்த நகலின் உருப்படிகளை மீண்டும் செய்யவும்.\n"
"இதை நீங்கள் பின்வருமாறு செய்ய விரும்பலாம்:\n"
"\n"
"    எனது_{name} = {name}.copy()\n"
"    for item in எனது_{name}:\n"
"        # {name} இதனை மாற்றவும்\n"
""

#: runtime_errors\runtime_error.py:61
msgid "While you were iterating over the items of a container ({container_type})\n"
"in a `{for_while}` loop, you either tried to add or remove items from it.\n"
"Suggestion: start by making a copy of the container and iterate over the items\n"
"of that copy if you want to change that container inside a loop.\n"
""
msgstr "`{for_while}` சுழலில் உள்ள ஒரு கொள்கலனின் ({container_type})\n"
"உருப்படிகளை மீண்டும் மீண்டும் செய்துகொண்டிருந்தீர்கள், அதிலிருந்து உருப்படிகளைச் சேர்க்க அல்லது அகற்ற முயற்சித்தீர்கள்.\n"
"பரிந்துரை: கொள்கலனின் நகலை உருவாக்குவதன் மூலம் தொடங்கவும்,\n"
"அந்த கொள்கலனை ஒரு சுழலுகுள் மாற்ற விரும்பினால், அந்த நகலின் உருப்படிகளை மீண்டும் செய்யவும்.\n"
""

#: runtime_errors\type_error.py:530
msgid "However, both `{obj_name}` and `{fn_call}` are numbers.\n"
"Perhaps you forgot a multiplication operator, `*`,\n"
"and meant to write `{obj_name} * {fn_call}`.\n"
""
msgstr "இருப்பினும், `{obj_name}` மற்றும் `{fn_call}` இரண்டும் எண்கள்.\n"
"ஒருவேளை நீங்கள் பெருக்கல் இயக்கியான `*` ஐ மறந்துவிட்டீர்கள், \n"
"மேலும் `{obj_name} * {fn_call}` என்று எழுத நினைத்திருக்கலாம்.\n"
""

#: syntax_errors\message_analyzer.py:753
msgid "You have defined a function repeating the argument\n"
"\n"
"    {name}\n"
"Each argument should appear only once in a function definition.\n"
""
msgstr "வாதத்தை மீண்டும் செய்யும் செயல்பாட்டை நீங்கள் வரையறுத்துள்ளீர்கள்\n"
"\n"
"     {name}\n"
"ஒவ்வொரு வாதமும் ஒரு செயல்பாடு வரையறையில் ஒரு முறை மட்டுமே தோன்ற வேண்டும்.\n"
""

#: functions_help.py:31
msgid "Use True (default) or False to set the debug flag."
msgstr "பிழைத்திருத்தக் கொடியை அமைக்க True (இயல்புநிலை) அல்லது False என்பதைப் பயன்படுத்தவும்."

